-- 000001_core: shared helpers, identity (users, sessions, tokens, 2FA), organizations,
-- teams and the audit log.
-- Conventions (see docs/database.md):
--   * UUID v7 primary keys (time-ordered → index-friendly), generated by uuid_generate_v7()
--     unless the application supplies one.
--   * created_at / updated_at are timestamptz (UTC); updated_at is maintained by trigger.
--   * deleted_at marks soft-deleted rows; unique constraints are partial on deleted_at IS NULL.

CREATE EXTENSION IF NOT EXISTS citext;

-- RFC 9562 UUID v7: 48-bit unix-ms timestamp + random bits. PostgreSQL 17 has no native
-- uuidv7() (added in 18). We take a v4 UUID, overlay the timestamp on the first 6 bytes
-- and flip the version nibble from 0100 (4) to 0111 (7); variant bits are already correct.
CREATE FUNCTION uuid_generate_v7() RETURNS uuid
LANGUAGE sql VOLATILE PARALLEL SAFE AS $$
  SELECT encode(
    set_bit(set_bit(
      overlay(uuid_send(gen_random_uuid())
              PLACING substring(int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint) FROM 3)
              FROM 1 FOR 6),
      52, 1), 53, 1),
    'hex')::uuid
$$;

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

-- ───────────────────────────── Users ─────────────────────────────

CREATE TABLE users (
  id                 uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  email              citext NOT NULL,
  display_name       text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 100),
  password_hash      text,                         -- Argon2id PHC string; NULL for SSO-only accounts
  email_verified_at  timestamptz,
  locale             text NOT NULL DEFAULT 'en' CHECK (locale IN ('en', 'km')),
  timezone           text NOT NULL DEFAULT 'Asia/Phnom_Penh',
  khmer_numerals     boolean NOT NULL DEFAULT false,
  totp_secret_enc    bytea,                        -- AES-256-GCM encrypted TOTP seed (active)
  totp_pending_enc   bytea,                        -- seed awaiting confirmation during 2FA setup
  totp_enabled_at    timestamptz,
  totp_last_step     bigint,                       -- last accepted TOTP time step (replay protection)
  failed_login_count integer NOT NULL DEFAULT 0,
  lockout_level      integer NOT NULL DEFAULT 0,   -- lock duration doubles per level
  locked_until       timestamptz,
  password_changed_at timestamptz,
  is_platform_admin  boolean NOT NULL DEFAULT false,
  disabled_at        timestamptz,
  last_login_at      timestamptz,
  version            integer NOT NULL DEFAULT 1,   -- optimistic locking
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  deleted_at         timestamptz
);
CREATE UNIQUE INDEX users_email_key ON users (email) WHERE deleted_at IS NULL;
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- External identities for OIDC SSO (GitHub, Google, Keycloak, ...).
CREATE TABLE user_identities (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  provider    text NOT NULL,
  subject     text NOT NULL,
  email       citext,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, subject)
);
CREATE INDEX user_identities_user_id_idx ON user_identities (user_id);
CREATE TRIGGER user_identities_updated_at BEFORE UPDATE ON user_identities FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- A session is one signed-in device: a family of rotating refresh tokens. The access JWT
-- carries the session id (sid). Revoking the session revokes the whole family.
CREATE TABLE sessions (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id         uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  auth_method     text NOT NULL CHECK (auth_method IN ('password', 'oidc')),
  ip              inet,
  user_agent      text,
  expires_at      timestamptz NOT NULL,           -- absolute lifetime of the family
  last_used_at    timestamptz NOT NULL DEFAULT now(),
  revoked_at      timestamptz,
  revoke_reason   text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id, created_at DESC);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- Refresh tokens rotate on every use. Presenting a token that was already used means it
-- was stolen (or replayed): the whole session is revoked. Only SHA-256 hashes are stored.
CREATE TABLE refresh_tokens (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  session_id  uuid NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
  parent_id   uuid REFERENCES refresh_tokens (id) ON DELETE SET NULL,
  token_hash  bytea NOT NULL UNIQUE,
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_session_id_idx ON refresh_tokens (session_id);

-- Bridges the password step and the TOTP step of a 2FA login (single use, 5 minutes).
CREATE TABLE mfa_challenges (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash   bytea NOT NULL UNIQUE,
  auth_method  text NOT NULL CHECK (auth_method IN ('password', 'oidc')),
  attempts     integer NOT NULL DEFAULT 0,
  expires_at   timestamptz NOT NULL,
  used_at      timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX mfa_challenges_user_id_idx ON mfa_challenges (user_id);

-- Personal API tokens: "ohp_<prefix>_<secret>"; prefix is shown in the UI, secret is hashed.
CREATE TABLE api_tokens (
  id            uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id       uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name          text NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
  token_prefix  text NOT NULL,
  token_hash    bytea NOT NULL UNIQUE,
  scopes        text[] NOT NULL DEFAULT '{}',
  expires_at    timestamptz,
  last_used_at  timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX api_tokens_user_id_idx ON api_tokens (user_id);
CREATE TRIGGER api_tokens_updated_at BEFORE UPDATE ON api_tokens FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Single-use tokens for email verification and password reset (hashed).
CREATE TYPE email_token_purpose AS ENUM ('verify_email', 'reset_password');
CREATE TABLE email_tokens (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  purpose     email_token_purpose NOT NULL,
  token_hash  bytea NOT NULL UNIQUE,
  expires_at  timestamptz NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX email_tokens_user_id_idx ON email_tokens (user_id, purpose);

-- TOTP recovery codes (hashed, single use).
CREATE TABLE user_recovery_codes (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  code_hash   bytea NOT NULL,
  used_at     timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX user_recovery_codes_user_id_idx ON user_recovery_codes (user_id);

-- ───────────────────────── Organizations & teams ─────────────────────────

CREATE TYPE member_role AS ENUM ('owner', 'admin', 'developer', 'viewer');

CREATE TABLE organizations (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  slug        text NOT NULL CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$'),
  name        text NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
  settings    jsonb NOT NULL DEFAULT '{}',
  version     integer NOT NULL DEFAULT 1,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);
CREATE UNIQUE INDEX organizations_slug_key ON organizations (slug) WHERE deleted_at IS NULL;
CREATE TRIGGER organizations_updated_at BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE organization_members (
  organization_id  uuid NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  user_id          uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role             member_role NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (organization_id, user_id)
);
CREATE INDEX organization_members_user_id_idx ON organization_members (user_id);
CREATE TRIGGER organization_members_updated_at BEFORE UPDATE ON organization_members FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE teams (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  organization_id  uuid NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  slug             text NOT NULL CHECK (slug ~ '^[a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?$'),
  name             text NOT NULL CHECK (length(name) BETWEEN 1 AND 100),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  deleted_at       timestamptz
);
CREATE UNIQUE INDEX teams_org_slug_key ON teams (organization_id, slug) WHERE deleted_at IS NULL;
CREATE TRIGGER teams_updated_at BEFORE UPDATE ON teams FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE team_members (
  team_id     uuid NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (team_id, user_id)
);
CREATE INDEX team_members_user_id_idx ON team_members (user_id);

-- ───────────────────────────── Audit log ─────────────────────────────
-- Append-only: UPDATE and DELETE are rejected by trigger. Retention/archival, if ever
-- needed, must be done by a privileged maintenance role that disables the trigger.

CREATE TABLE audit_log (
  id               uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  organization_id  uuid REFERENCES organizations (id) ON DELETE SET NULL,
  actor_user_id    uuid REFERENCES users (id) ON DELETE SET NULL,
  actor_type       text NOT NULL CHECK (actor_type IN ('user', 'api_token', 'runner', 'system')),
  action           text NOT NULL,          -- e.g. "project.create", "secret.read"
  resource_type    text NOT NULL,
  resource_id      text,
  ip               inet,
  user_agent       text,
  before           jsonb,
  after            jsonb,
  metadata         jsonb NOT NULL DEFAULT '{}',
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_org_created_idx ON audit_log (organization_id, created_at DESC);
CREATE INDEX audit_log_actor_created_idx ON audit_log (actor_user_id, created_at DESC);
CREATE INDEX audit_log_resource_idx ON audit_log (resource_type, resource_id);

CREATE FUNCTION audit_log_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only' USING ERRCODE = 'insufficient_privilege';
END $$;
CREATE TRIGGER audit_log_no_update BEFORE UPDATE OR DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();
CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
  FOR EACH STATEMENT EXECUTE FUNCTION audit_log_immutable();

-- ─────────────────────── Least-privilege application role ───────────────────────
-- In production the API connects as opshub_app (DML only) and migrations run as the
-- schema owner. The roles are created outside migrations (cluster-level objects; see
-- deploy/compose/postgres/init-roles.sql). When present, make the audit log insert-only
-- for the application role.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'opshub_app') THEN
    REVOKE UPDATE, DELETE, TRUNCATE ON audit_log FROM opshub_app;
  END IF;
END $$;
