// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts SET acknowledged_by = $1, acknowledged_at = now(), next_step_at = NULL
WHERE id = $2 AND status = 'firing' AND acknowledged_at IS NULL
RETURNING id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at
`

type AcknowledgeAlertParams struct {
	UserID *uuid.UUID `json:"user_id"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.UserID, arg.ID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleKind,
		&i.Severity,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectLabels,
		&i.Status,
		&i.Details,
		&i.PendingSince,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.NextStep,
		&i.NextStepAt,
	)
	return i, err
}

const activeSilences = `-- name: ActiveSilences :many
SELECT id, organization_id, rule_id, subject_id, label, severity, comment, starts_at, ends_at, created_by, created_at FROM silences WHERE organization_id = $1 AND starts_at <= now() AND ends_at > now()
`

func (q *Queries) ActiveSilences(ctx context.Context, organizationID uuid.UUID) ([]Silence, error) {
	rows, err := q.db.Query(ctx, activeSilences, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Silence{}
	for rows.Next() {
		var i Silence
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RuleID,
			&i.SubjectID,
			&i.Label,
			&i.Severity,
			&i.Comment,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const advanceAlertStep = `-- name: AdvanceAlertStep :exec
UPDATE alerts SET next_step = $1, next_step_at = $2 WHERE id = $3
`

type AdvanceAlertStepParams struct {
	NextStep   int32      `json:"next_step"`
	NextStepAt *time.Time `json:"next_step_at"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) AdvanceAlertStep(ctx context.Context, arg AdvanceAlertStepParams) error {
	_, err := q.db.Exec(ctx, advanceAlertStep, arg.NextStep, arg.NextStepAt, arg.ID)
	return err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (organization_id, name, kind, target_id, label, threshold, metric, for_seconds, severity, escalation, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12)
RETURNING id, organization_id, name, kind, target_id, label, threshold, metric, for_seconds, severity, escalation, enabled, created_by, version, created_at, updated_at
`

type CreateAlertRuleParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	Name           string        `json:"name"`
	Kind           AlertRuleKind `json:"kind"`
	TargetID       *uuid.UUID    `json:"target_id"`
	Label          *string       `json:"label"`
	Threshold      *float64      `json:"threshold"`
	Metric         *string       `json:"metric"`
	ForSeconds     int32         `json:"for_seconds"`
	Severity       AlertSeverity `json:"severity"`
	Escalation     []byte        `json:"escalation"`
	Enabled        bool          `json:"enabled"`
	CreatedBy      *uuid.UUID    `json:"created_by"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.OrganizationID,
		arg.Name,
		arg.Kind,
		arg.TargetID,
		arg.Label,
		arg.Threshold,
		arg.Metric,
		arg.ForSeconds,
		arg.Severity,
		arg.Escalation,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.TargetID,
		&i.Label,
		&i.Threshold,
		&i.Metric,
		&i.ForSeconds,
		&i.Severity,
		&i.Escalation,
		&i.Enabled,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSilence = `-- name: CreateSilence :one
INSERT INTO silences (organization_id, rule_id, subject_id, label, severity, comment, starts_at, ends_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, rule_id, subject_id, label, severity, comment, starts_at, ends_at, created_by, created_at
`

type CreateSilenceParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	RuleID         *uuid.UUID     `json:"rule_id"`
	SubjectID      *uuid.UUID     `json:"subject_id"`
	Label          *string        `json:"label"`
	Severity       *AlertSeverity `json:"severity"`
	Comment        string         `json:"comment"`
	StartsAt       time.Time      `json:"starts_at"`
	EndsAt         time.Time      `json:"ends_at"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
}

func (q *Queries) CreateSilence(ctx context.Context, arg CreateSilenceParams) (Silence, error) {
	row := q.db.QueryRow(ctx, createSilence,
		arg.OrganizationID,
		arg.RuleID,
		arg.SubjectID,
		arg.Label,
		arg.Severity,
		arg.Comment,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Silence
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.SubjectID,
		&i.Label,
		&i.Severity,
		&i.Comment,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlertRule = `-- name: DeleteAlertRule :execrows
DELETE FROM alert_rules WHERE id = $1
`

func (q *Queries) DeleteAlertRule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlertRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingAlert = `-- name: DeletePendingAlert :exec
DELETE FROM alerts WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingAlert, id)
	return err
}

const dueEscalations = `-- name: DueEscalations :many
SELECT id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at FROM alerts
WHERE status = 'firing' AND acknowledged_at IS NULL AND next_step_at <= now()
ORDER BY next_step_at LIMIT $1 FOR UPDATE SKIP LOCKED
`

// Firing, unacknowledged alerts whose next escalation step is due.
func (q *Queries) DueEscalations(ctx context.Context, maxAlerts int32) ([]Alert, error) {
	rows, err := q.db.Query(ctx, dueEscalations, maxAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RuleID,
			&i.RuleName,
			&i.RuleKind,
			&i.Severity,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectLabels,
			&i.Status,
			&i.Details,
			&i.PendingSince,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.NextStep,
			&i.NextStepAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enabledAlertRules = `-- name: EnabledAlertRules :many
SELECT id, organization_id, name, kind, target_id, label, threshold, metric, for_seconds, severity, escalation, enabled, created_by, version, created_at, updated_at FROM alert_rules WHERE enabled ORDER BY organization_id, id
`

func (q *Queries) EnabledAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, enabledAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertRule{}
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.TargetID,
			&i.Label,
			&i.Threshold,
			&i.Metric,
			&i.ForSeconds,
			&i.Severity,
			&i.Escalation,
			&i.Enabled,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const evalCertificates = `-- name: EvalCertificates :many
SELECT a.id, a.name, a.tags, c.not_after, c.error, c.last_checked_at
FROM infra_assets a JOIN ssl_certificates c ON c.asset_id = a.id
WHERE a.organization_id = $1 AND a.kind = 'domain'
`

type EvalCertificatesRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Tags          []string   `json:"tags"`
	NotAfter      *time.Time `json:"not_after"`
	Error         string     `json:"error"`
	LastCheckedAt time.Time  `json:"last_checked_at"`
}

func (q *Queries) EvalCertificates(ctx context.Context, organizationID uuid.UUID) ([]EvalCertificatesRow, error) {
	rows, err := q.db.Query(ctx, evalCertificates, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalCertificatesRow{}
	for rows.Next() {
		var i EvalCertificatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tags,
			&i.NotAfter,
			&i.Error,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const evalMonitors = `-- name: EvalMonitors :many
SELECT id, name, labels, enabled, last_up, last_latency_ms, last_error, down_since, last_checked_at
FROM monitors WHERE organization_id = $1
`

type EvalMonitorsRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	Labels        []string   `json:"labels"`
	Enabled       bool       `json:"enabled"`
	LastUp        *bool      `json:"last_up"`
	LastLatencyMs *int32     `json:"last_latency_ms"`
	LastError     string     `json:"last_error"`
	DownSince     *time.Time `json:"down_since"`
	LastCheckedAt *time.Time `json:"last_checked_at"`
}

func (q *Queries) EvalMonitors(ctx context.Context, organizationID uuid.UUID) ([]EvalMonitorsRow, error) {
	rows, err := q.db.Query(ctx, evalMonitors, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalMonitorsRow{}
	for rows.Next() {
		var i EvalMonitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Labels,
			&i.Enabled,
			&i.LastUp,
			&i.LastLatencyMs,
			&i.LastError,
			&i.DownSince,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const evalServers = `-- name: EvalServers :many
SELECT id, name, tags, (agent_token_hash IS NOT NULL)::boolean AS has_agent, last_heartbeat_at, last_metrics
FROM infra_assets WHERE organization_id = $1 AND kind = 'server'
`

type EvalServersRow struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	Tags            []string   `json:"tags"`
	HasAgent        bool       `json:"has_agent"`
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at"`
	LastMetrics     []byte     `json:"last_metrics"`
}

func (q *Queries) EvalServers(ctx context.Context, organizationID uuid.UUID) ([]EvalServersRow, error) {
	rows, err := q.db.Query(ctx, evalServers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalServersRow{}
	for rows.Next() {
		var i EvalServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tags,
			&i.HasAgent,
			&i.LastHeartbeatAt,
			&i.LastMetrics,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireSilence = `-- name: ExpireSilence :one
UPDATE silences SET ends_at = greatest(now(), starts_at + interval '1 millisecond') WHERE id = $1 AND ends_at > now()
RETURNING id, organization_id, rule_id, subject_id, label, severity, comment, starts_at, ends_at, created_by, created_at
`

func (q *Queries) ExpireSilence(ctx context.Context, id uuid.UUID) (Silence, error) {
	row := q.db.QueryRow(ctx, expireSilence, id)
	var i Silence
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.SubjectID,
		&i.Label,
		&i.Severity,
		&i.Comment,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const fireAlert = `-- name: FireAlert :one
UPDATE alerts SET status = 'firing', started_at = now(), next_step = 0, next_step_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at
`

func (q *Queries) FireAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, fireAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleKind,
		&i.Severity,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectLabels,
		&i.Status,
		&i.Details,
		&i.PendingSince,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.NextStep,
		&i.NextStepAt,
	)
	return i, err
}

const getAlert = `-- name: GetAlert :one
SELECT a.id, a.organization_id, a.rule_id, a.rule_name, a.rule_kind, a.severity, a.subject_type, a.subject_id, a.subject_name, a.subject_labels, a.status, a.details, a.pending_since, a.started_at, a.resolved_at, a.acknowledged_by, a.acknowledged_at, a.next_step, a.next_step_at, u.display_name AS acknowledged_by_name
FROM alerts a LEFT JOIN users u ON u.id = a.acknowledged_by
WHERE a.id = $1
`

type GetAlertRow struct {
	Alert              Alert   `json:"alert"`
	AcknowledgedByName *string `json:"acknowledged_by_name"`
}

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.Alert.ID,
		&i.Alert.OrganizationID,
		&i.Alert.RuleID,
		&i.Alert.RuleName,
		&i.Alert.RuleKind,
		&i.Alert.Severity,
		&i.Alert.SubjectType,
		&i.Alert.SubjectID,
		&i.Alert.SubjectName,
		&i.Alert.SubjectLabels,
		&i.Alert.Status,
		&i.Alert.Details,
		&i.Alert.PendingSince,
		&i.Alert.StartedAt,
		&i.Alert.ResolvedAt,
		&i.Alert.AcknowledgedBy,
		&i.Alert.AcknowledgedAt,
		&i.Alert.NextStep,
		&i.Alert.NextStepAt,
		&i.AcknowledgedByName,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT id, organization_id, name, kind, target_id, label, threshold, metric, for_seconds, severity, escalation, enabled, created_by, version, created_at, updated_at FROM alert_rules WHERE id = $1
`

func (q *Queries) GetAlertRule(ctx context.Context, id uuid.UUID) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, id)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.TargetID,
		&i.Label,
		&i.Threshold,
		&i.Metric,
		&i.ForSeconds,
		&i.Severity,
		&i.Escalation,
		&i.Enabled,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSilence = `-- name: GetSilence :one
SELECT id, organization_id, rule_id, subject_id, label, severity, comment, starts_at, ends_at, created_by, created_at FROM silences WHERE id = $1
`

func (q *Queries) GetSilence(ctx context.Context, id uuid.UUID) (Silence, error) {
	row := q.db.QueryRow(ctx, getSilence, id)
	var i Silence
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.SubjectID,
		&i.Label,
		&i.Severity,
		&i.Comment,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertAlertEvent = `-- name: InsertAlertEvent :exec
INSERT INTO alert_events (alert_id, kind, channel_id, channel_name, user_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAlertEventParams struct {
	AlertID     uuid.UUID  `json:"alert_id"`
	Kind        string     `json:"kind"`
	ChannelID   *uuid.UUID `json:"channel_id"`
	ChannelName string     `json:"channel_name"`
	UserID      *uuid.UUID `json:"user_id"`
	Detail      string     `json:"detail"`
}

func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) error {
	_, err := q.db.Exec(ctx, insertAlertEvent,
		arg.AlertID,
		arg.Kind,
		arg.ChannelID,
		arg.ChannelName,
		arg.UserID,
		arg.Detail,
	)
	return err
}

const insertPendingAlert = `-- name: InsertPendingAlert :one
INSERT INTO alerts (organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (rule_id, subject_id) WHERE status <> 'resolved' DO NOTHING
RETURNING id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at
`

type InsertPendingAlertParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	RuleID         *uuid.UUID    `json:"rule_id"`
	RuleName       string        `json:"rule_name"`
	RuleKind       AlertRuleKind `json:"rule_kind"`
	Severity       AlertSeverity `json:"severity"`
	SubjectType    string        `json:"subject_type"`
	SubjectID      uuid.UUID     `json:"subject_id"`
	SubjectName    string        `json:"subject_name"`
	SubjectLabels  []string      `json:"subject_labels"`
	Details        []byte        `json:"details"`
}

func (q *Queries) InsertPendingAlert(ctx context.Context, arg InsertPendingAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, insertPendingAlert,
		arg.OrganizationID,
		arg.RuleID,
		arg.RuleName,
		arg.RuleKind,
		arg.Severity,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectName,
		arg.SubjectLabels,
		arg.Details,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleKind,
		&i.Severity,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectLabels,
		&i.Status,
		&i.Details,
		&i.PendingSince,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.NextStep,
		&i.NextStepAt,
	)
	return i, err
}

const lastAlertEventKind = `-- name: LastAlertEventKind :one
SELECT kind FROM alert_events WHERE alert_id = $1 ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastAlertEventKind(ctx context.Context, alertID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastAlertEventKind, alertID)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const listAlertEvents = `-- name: ListAlertEvents :many
SELECT e.id, e.alert_id, e.at, e.kind, e.channel_id, e.channel_name, e.user_id, e.detail, u.display_name AS user_name
FROM alert_events e LEFT JOIN users u ON u.id = e.user_id
WHERE e.alert_id = $1 ORDER BY e.id
`

type ListAlertEventsRow struct {
	ID          int64      `json:"id"`
	AlertID     uuid.UUID  `json:"alert_id"`
	At          time.Time  `json:"at"`
	Kind        string     `json:"kind"`
	ChannelID   *uuid.UUID `json:"channel_id"`
	ChannelName string     `json:"channel_name"`
	UserID      *uuid.UUID `json:"user_id"`
	Detail      string     `json:"detail"`
	UserName    *string    `json:"user_name"`
}

func (q *Queries) ListAlertEvents(ctx context.Context, alertID uuid.UUID) ([]ListAlertEventsRow, error) {
	rows, err := q.db.Query(ctx, listAlertEvents, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertEventsRow{}
	for rows.Next() {
		var i ListAlertEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.At,
			&i.Kind,
			&i.ChannelID,
			&i.ChannelName,
			&i.UserID,
			&i.Detail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT r.id, r.organization_id, r.name, r.kind, r.target_id, r.label, r.threshold, r.metric, r.for_seconds, r.severity, r.escalation, r.enabled, r.created_by, r.version, r.created_at, r.updated_at,
       (SELECT count(*) FROM alerts a WHERE a.rule_id = r.id AND a.status = 'firing')::integer AS firing
FROM alert_rules r WHERE r.organization_id = $1 ORDER BY r.name
`

type ListAlertRulesRow struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	Name           string        `json:"name"`
	Kind           AlertRuleKind `json:"kind"`
	TargetID       *uuid.UUID    `json:"target_id"`
	Label          *string       `json:"label"`
	Threshold      *float64      `json:"threshold"`
	Metric         *string       `json:"metric"`
	ForSeconds     int32         `json:"for_seconds"`
	Severity       AlertSeverity `json:"severity"`
	Escalation     []byte        `json:"escalation"`
	Enabled        bool          `json:"enabled"`
	CreatedBy      *uuid.UUID    `json:"created_by"`
	Version        int32         `json:"version"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	Firing         int32         `json:"firing"`
}

func (q *Queries) ListAlertRules(ctx context.Context, organizationID uuid.UUID) ([]ListAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, listAlertRules, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertRulesRow{}
	for rows.Next() {
		var i ListAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.TargetID,
			&i.Label,
			&i.Threshold,
			&i.Metric,
			&i.ForSeconds,
			&i.Severity,
			&i.Escalation,
			&i.Enabled,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Firing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.organization_id, a.rule_id, a.rule_name, a.rule_kind, a.severity, a.subject_type, a.subject_id, a.subject_name, a.subject_labels, a.status, a.details, a.pending_since, a.started_at, a.resolved_at, a.acknowledged_by, a.acknowledged_at, a.next_step, a.next_step_at, u.display_name AS acknowledged_by_name
FROM alerts a LEFT JOIN users u ON u.id = a.acknowledged_by
WHERE a.organization_id = $1 AND a.status <> 'pending'
  AND ($2::alert_status IS NULL OR a.status = $2)
  AND ($3::alert_severity IS NULL OR a.severity = $3)
  AND ($4::timestamptz IS NULL OR a.started_at < $4)
ORDER BY a.status = 'firing' DESC, a.started_at DESC
LIMIT $5
`

type ListAlertsParams struct {
	OrganizationID uuid.UUID      `json:"organization_id"`
	Status         *AlertStatus   `json:"status"`
	Severity       *AlertSeverity `json:"severity"`
	Before         *time.Time     `json:"before"`
	MaxAlerts      int32          `json:"max_alerts"`
}

type ListAlertsRow struct {
	Alert              Alert   `json:"alert"`
	AcknowledgedByName *string `json:"acknowledged_by_name"`
}

// Firing and resolved alerts, newest first (pending ones aren't alerts yet).
func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.OrganizationID,
		arg.Status,
		arg.Severity,
		arg.Before,
		arg.MaxAlerts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.Alert.ID,
			&i.Alert.OrganizationID,
			&i.Alert.RuleID,
			&i.Alert.RuleName,
			&i.Alert.RuleKind,
			&i.Alert.Severity,
			&i.Alert.SubjectType,
			&i.Alert.SubjectID,
			&i.Alert.SubjectName,
			&i.Alert.SubjectLabels,
			&i.Alert.Status,
			&i.Alert.Details,
			&i.Alert.PendingSince,
			&i.Alert.StartedAt,
			&i.Alert.ResolvedAt,
			&i.Alert.AcknowledgedBy,
			&i.Alert.AcknowledgedAt,
			&i.Alert.NextStep,
			&i.Alert.NextStepAt,
			&i.AcknowledgedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSilences = `-- name: ListSilences :many
SELECT s.id, s.organization_id, s.rule_id, s.subject_id, s.label, s.severity, s.comment, s.starts_at, s.ends_at, s.created_by, s.created_at, u.display_name AS created_by_name, r.name AS rule_name
FROM silences s
LEFT JOIN users u ON u.id = s.created_by
LEFT JOIN alert_rules r ON r.id = s.rule_id
WHERE s.organization_id = $1 AND ($2::boolean OR s.ends_at > now())
ORDER BY s.ends_at <= now(), s.starts_at DESC
LIMIT 200
`

type ListSilencesParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	IncludeExpired bool      `json:"include_expired"`
}

type ListSilencesRow struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	RuleID         *uuid.UUID     `json:"rule_id"`
	SubjectID      *uuid.UUID     `json:"subject_id"`
	Label          *string        `json:"label"`
	Severity       *AlertSeverity `json:"severity"`
	Comment        string         `json:"comment"`
	StartsAt       time.Time      `json:"starts_at"`
	EndsAt         time.Time      `json:"ends_at"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	CreatedByName  *string        `json:"created_by_name"`
	RuleName       *string        `json:"rule_name"`
}

// Active and upcoming silences, then (with include_expired) the last 100 expired ones.
func (q *Queries) ListSilences(ctx context.Context, arg ListSilencesParams) ([]ListSilencesRow, error) {
	rows, err := q.db.Query(ctx, listSilences, arg.OrganizationID, arg.IncludeExpired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSilencesRow{}
	for rows.Next() {
		var i ListSilencesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RuleID,
			&i.SubjectID,
			&i.Label,
			&i.Severity,
			&i.Comment,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifiedChannelIDs = `-- name: NotifiedChannelIDs :many
SELECT DISTINCT channel_id::uuid FROM alert_events
WHERE alert_id = $1 AND kind = 'notified' AND channel_id IS NOT NULL AND detail = 'firing'
`

// Channels that received this alert's firing message (they also get the resolution).
func (q *Queries) NotifiedChannelIDs(ctx context.Context, alertID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, notifiedChannelIDs, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openAlertsForRule = `-- name: OpenAlertsForRule :many
SELECT id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at FROM alerts WHERE rule_id = $1 AND status <> 'resolved'
`

func (q *Queries) OpenAlertsForRule(ctx context.Context, ruleID *uuid.UUID) ([]Alert, error) {
	rows, err := q.db.Query(ctx, openAlertsForRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RuleID,
			&i.RuleName,
			&i.RuleKind,
			&i.Severity,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectLabels,
			&i.Status,
			&i.Details,
			&i.PendingSince,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.NextStep,
			&i.NextStepAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts SET status = 'resolved', resolved_at = now(), next_step_at = NULL
WHERE id = $1 AND status = 'firing'
RETURNING id, organization_id, rule_id, rule_name, rule_kind, severity, subject_type, subject_id, subject_name, subject_labels, status, details, pending_since, started_at, resolved_at, acknowledged_by, acknowledged_at, next_step, next_step_at
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RuleID,
		&i.RuleName,
		&i.RuleKind,
		&i.Severity,
		&i.SubjectType,
		&i.SubjectID,
		&i.SubjectName,
		&i.SubjectLabels,
		&i.Status,
		&i.Details,
		&i.PendingSince,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.NextStep,
		&i.NextStepAt,
	)
	return i, err
}

const updateAlertObservation = `-- name: UpdateAlertObservation :exec
UPDATE alerts SET details = $1, subject_name = $2, subject_labels = $3, severity = $4, rule_name = $5
WHERE id = $6
`

type UpdateAlertObservationParams struct {
	Details       []byte        `json:"details"`
	SubjectName   string        `json:"subject_name"`
	SubjectLabels []string      `json:"subject_labels"`
	Severity      AlertSeverity `json:"severity"`
	RuleName      string        `json:"rule_name"`
	ID            uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateAlertObservation(ctx context.Context, arg UpdateAlertObservationParams) error {
	_, err := q.db.Exec(ctx, updateAlertObservation,
		arg.Details,
		arg.SubjectName,
		arg.SubjectLabels,
		arg.Severity,
		arg.RuleName,
		arg.ID,
	)
	return err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules SET name = $1, target_id = $2, label = $3, threshold = $4,
  metric = $5, for_seconds = $6, severity = $7, escalation = $8, enabled = $9,
  version = version + 1
WHERE id = $10 AND version = $11
RETURNING id, organization_id, name, kind, target_id, label, threshold, metric, for_seconds, severity, escalation, enabled, created_by, version, created_at, updated_at
`

type UpdateAlertRuleParams struct {
	Name            string        `json:"name"`
	TargetID        *uuid.UUID    `json:"target_id"`
	Label           *string       `json:"label"`
	Threshold       *float64      `json:"threshold"`
	Metric          *string       `json:"metric"`
	ForSeconds      int32         `json:"for_seconds"`
	Severity        AlertSeverity `json:"severity"`
	Escalation      []byte        `json:"escalation"`
	Enabled         bool          `json:"enabled"`
	ID              uuid.UUID     `json:"id"`
	ExpectedVersion int32         `json:"expected_version"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.Name,
		arg.TargetID,
		arg.Label,
		arg.Threshold,
		arg.Metric,
		arg.ForSeconds,
		arg.Severity,
		arg.Escalation,
		arg.Enabled,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.TargetID,
		&i.Label,
		&i.Threshold,
		&i.Metric,
		&i.ForSeconds,
		&i.Severity,
		&i.Escalation,
		&i.Enabled,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
