// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (
  organization_id, actor_user_id, actor_type, action, resource_type, resource_id,
  ip, user_agent, before, after, metadata
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11
)
RETURNING id, organization_id, actor_user_id, actor_type, action, resource_type, resource_id, ip, user_agent, before, after, metadata, created_at
`

type InsertAuditLogParams struct {
	OrganizationID *uuid.UUID  `json:"organization_id"`
	ActorUserID    *uuid.UUID  `json:"actor_user_id"`
	ActorType      string      `json:"actor_type"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     *string     `json:"resource_id"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
	Before         []byte      `json:"before"`
	After          []byte      `json:"after"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.ActorType,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.Before,
		arg.After,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorUserID,
		&i.ActorType,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Ip,
		&i.UserAgent,
		&i.Before,
		&i.After,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, organization_id, actor_user_id, actor_type, action, resource_type, resource_id, ip, user_agent, before, after, metadata, created_at FROM audit_log
WHERE organization_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditLogParams struct {
	OrganizationID  *uuid.UUID `json:"organization_id"`
	BeforeCreatedAt *time.Time `json:"before_created_at"`
	BeforeID        *uuid.UUID `json:"before_id"`
	PageSize        int32      `json:"page_size"`
}

// Keyset pagination on (created_at, id) newest first.
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.OrganizationID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.ActorType,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
