// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO notification_channels (id, organization_id, name, kind, config, secrets_enc, locale, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, kind, config, secrets_enc, locale, last_test_at, last_test_ok, created_by, version, created_at, updated_at
`

type CreateChannelParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Kind           ChannelKind `json:"kind"`
	Config         []byte      `json:"config"`
	SecretsEnc     []byte      `json:"secrets_enc"`
	Locale         *string     `json:"locale"`
	CreatedBy      *uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.SecretsEnc,
		arg.Locale,
		arg.CreatedBy,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.Locale,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM notification_channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, organization_id, name, kind, config, secrets_enc, locale, last_test_at, last_test_ok, created_by, version, created_at, updated_at FROM notification_channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.Locale,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgSlugName = `-- name: GetOrgSlugName :one
SELECT slug, name FROM organizations WHERE id = $1
`

type GetOrgSlugNameRow struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) GetOrgSlugName(ctx context.Context, id uuid.UUID) (GetOrgSlugNameRow, error) {
	row := q.db.QueryRow(ctx, getOrgSlugName, id)
	var i GetOrgSlugNameRow
	err := row.Scan(&i.Slug, &i.Name)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, organization_id, name, kind, config, secrets_enc, locale, last_test_at, last_test_ok, created_by, version, created_at, updated_at FROM notification_channels WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context, organizationID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listChannels, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.SecretsEnc,
			&i.Locale,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberLocalesByEmail = `-- name: MemberLocalesByEmail :many
SELECT lower(u.email)::text AS email, u.locale
FROM users u JOIN organization_members m ON m.user_id = u.id
WHERE m.organization_id = $1 AND lower(u.email) = ANY ($2::text[])
`

type MemberLocalesByEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Emails         []string  `json:"emails"`
}

type MemberLocalesByEmailRow struct {
	Email  string `json:"email"`
	Locale string `json:"locale"`
}

// The language of each address that belongs to a member of the organization.
func (q *Queries) MemberLocalesByEmail(ctx context.Context, arg MemberLocalesByEmailParams) ([]MemberLocalesByEmailRow, error) {
	rows, err := q.db.Query(ctx, memberLocalesByEmail, arg.OrganizationID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberLocalesByEmailRow{}
	for rows.Next() {
		var i MemberLocalesByEmailRow
		if err := rows.Scan(&i.Email, &i.Locale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgChannelIDs = `-- name: OrgChannelIDs :many
SELECT id FROM notification_channels WHERE organization_id = $1 AND id = ANY ($2::uuid[])
`

type OrgChannelIDsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ids            []uuid.UUID `json:"ids"`
}

func (q *Queries) OrgChannelIDs(ctx context.Context, arg OrgChannelIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, orgChannelIDs, arg.OrganizationID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rulesUsingChannel = `-- name: RulesUsingChannel :many
SELECT r.name FROM alert_rules r
WHERE r.organization_id = $1
  AND EXISTS (SELECT 1 FROM jsonb_array_elements(r.escalation) step WHERE step->'channel_ids' ? $2::text)
ORDER BY r.name
`

type RulesUsingChannelParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ChannelID      string    `json:"channel_id"`
}

// Names of the rules whose escalation notifies the channel.
func (q *Queries) RulesUsingChannel(ctx context.Context, arg RulesUsingChannelParams) ([]string, error) {
	rows, err := q.db.Query(ctx, rulesUsingChannel, arg.OrganizationID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelTest = `-- name: SetChannelTest :exec
UPDATE notification_channels SET last_test_at = now(), last_test_ok = $1 WHERE id = $2
`

type SetChannelTestParams struct {
	Ok *bool     `json:"ok"`
	ID uuid.UUID `json:"id"`
}

func (q *Queries) SetChannelTest(ctx context.Context, arg SetChannelTestParams) error {
	_, err := q.db.Exec(ctx, setChannelTest, arg.Ok, arg.ID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE notification_channels SET name = $1, config = $2, secrets_enc = $3, locale = $4,
  version = version + 1
WHERE id = $5 AND version = $6
RETURNING id, organization_id, name, kind, config, secrets_enc, locale, last_test_at, last_test_ok, created_by, version, created_at, updated_at
`

type UpdateChannelParams struct {
	Name            string    `json:"name"`
	Config          []byte    `json:"config"`
	SecretsEnc      []byte    `json:"secrets_enc"`
	Locale          *string   `json:"locale"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.Config,
		arg.SecretsEnc,
		arg.Locale,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.SecretsEnc,
		&i.Locale,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
