// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDeploymentLogBytes = `-- name: AddDeploymentLogBytes :exec
UPDATE deployments SET log_bytes = log_bytes + $1 WHERE id = $2
`

type AddDeploymentLogBytesParams struct {
	Bytes int64     `json:"bytes"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AddDeploymentLogBytes(ctx context.Context, arg AddDeploymentLogBytesParams) error {
	_, err := q.db.Exec(ctx, addDeploymentLogBytes, arg.Bytes, arg.ID)
	return err
}

const countActiveTargetDeployments = `-- name: CountActiveTargetDeployments :one
SELECT count(*) FROM deployments WHERE target_id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) CountActiveTargetDeployments(ctx context.Context, targetID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTargetDeployments, targetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployTargetWithID = `-- name: CreateDeployTargetWithID :one
INSERT INTO deploy_targets (id, organization_id, name, kind, description, config, credentials_enc, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, name, kind, description, config, credentials_enc, last_test_at, last_test_ok, created_by, version, created_at, updated_at
`

type CreateDeployTargetWithIDParams struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	Name           string           `json:"name"`
	Kind           DeployTargetKind `json:"kind"`
	Description    string           `json:"description"`
	Config         []byte           `json:"config"`
	CredentialsEnc []byte           `json:"credentials_enc"`
	CreatedBy      *uuid.UUID       `json:"created_by"`
}

// The id is chosen by the caller: it is the associated data of the credentials' encryption.
func (q *Queries) CreateDeployTargetWithID(ctx context.Context, arg CreateDeployTargetWithIDParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, createDeployTargetWithID,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.Config,
		arg.CredentialsEnc,
		arg.CreatedBy,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Config,
		&i.CredentialsEnc,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (organization_id, project_id, environment_id, number, target_id, target_name, target_kind,
  version, previous_version, strategy, run_id, job_id, rollback_of_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11, $12, $13, $14)
RETURNING id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at
`

type CreateDeploymentParams struct {
	OrganizationID  uuid.UUID        `json:"organization_id"`
	ProjectID       uuid.UUID        `json:"project_id"`
	EnvironmentID   uuid.UUID        `json:"environment_id"`
	Number          int32            `json:"number"`
	TargetID        *uuid.UUID       `json:"target_id"`
	TargetName      string           `json:"target_name"`
	TargetKind      DeployTargetKind `json:"target_kind"`
	Version         string           `json:"version"`
	PreviousVersion string           `json:"previous_version"`
	Strategy        DeployStrategy   `json:"strategy"`
	RunID           *uuid.UUID       `json:"run_id"`
	JobID           *uuid.UUID       `json:"job_id"`
	RollbackOfID    *uuid.UUID       `json:"rollback_of_id"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.OrganizationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Number,
		arg.TargetID,
		arg.TargetName,
		arg.TargetKind,
		arg.Version,
		arg.PreviousVersion,
		arg.Strategy,
		arg.RunID,
		arg.JobID,
		arg.RollbackOfID,
		arg.CreatedBy,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeployTarget = `-- name: DeleteDeployTarget :execrows
DELETE FROM deploy_targets WHERE id = $1
`

func (q *Queries) DeleteDeployTarget(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeployTarget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deploymentByJob = `-- name: DeploymentByJob :one
SELECT id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at FROM deployments WHERE job_id = $1
`

func (q *Queries) DeploymentByJob(ctx context.Context, jobID *uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, deploymentByJob, jobID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishDeployment = `-- name: FinishDeployment :one
UPDATE deployments SET status = $1, failure_reason = $2, reverted = $3,
  health = $4, finished_at = now(),
  previous_version = CASE WHEN previous_version = '' THEN $5::text ELSE previous_version END
WHERE id = $6 AND status IN ('pending', 'running')
RETURNING id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at
`

type FinishDeploymentParams struct {
	Status           DeploymentStatus `json:"status"`
	FailureReason    *string          `json:"failure_reason"`
	Reverted         bool             `json:"reverted"`
	Health           []byte           `json:"health"`
	ObservedPrevious string           `json:"observed_previous"`
	ID               uuid.UUID        `json:"id"`
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, finishDeployment,
		arg.Status,
		arg.FailureReason,
		arg.Reverted,
		arg.Health,
		arg.ObservedPrevious,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentDeployment = `-- name: GetCurrentDeployment :one
SELECT d.id, d.organization_id, d.project_id, d.environment_id, d.number, d.target_id, d.target_name, d.target_kind, d.version, d.previous_version, d.strategy, d.status, d.failure_reason, d.reverted, d.health, d.run_id, d.job_id, d.rollback_of_id, d.created_by, d.log_bytes, d.started_at, d.finished_at, d.created_at, d.updated_at FROM environments e JOIN deployments d ON d.id = e.current_deployment_id WHERE e.id = $1
`

func (q *Queries) GetCurrentDeployment(ctx context.Context, environmentID uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getCurrentDeployment, environmentID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT id, organization_id, name, kind, description, config, credentials_enc, last_test_at, last_test_ok, created_by, version, created_at, updated_at FROM deploy_targets WHERE id = $1
`

func (q *Queries) GetDeployTarget(ctx context.Context, id uuid.UUID) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, getDeployTarget, id)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Config,
		&i.CredentialsEnc,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployTargetByName = `-- name: GetDeployTargetByName :one
SELECT id, organization_id, name, kind, description, config, credentials_enc, last_test_at, last_test_ok, created_by, version, created_at, updated_at FROM deploy_targets WHERE organization_id = $1 AND name = $2
`

type GetDeployTargetByNameParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetDeployTargetByName(ctx context.Context, arg GetDeployTargetByNameParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, getDeployTargetByName, arg.OrganizationID, arg.Name)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Config,
		&i.CredentialsEnc,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentDetail = `-- name: GetDeploymentDetail :one
SELECT d.id, d.organization_id, d.project_id, d.environment_id, d.number, d.target_id, d.target_name, d.target_kind, d.version, d.previous_version, d.strategy, d.status, d.failure_reason, d.reverted, d.health, d.run_id, d.job_id, d.rollback_of_id, d.created_by, d.log_bytes, d.started_at, d.finished_at, d.created_at, d.updated_at, e.name AS environment_name, coalesce(u.display_name, '')::text AS created_by_name,
       coalesce(r.number, 0)::integer AS run_number, coalesce(j.name, '')::text AS job_name,
       (e.current_deployment_id IS NOT DISTINCT FROM d.id)::boolean AS is_current
FROM deployments d
JOIN environments e ON e.id = d.environment_id
LEFT JOIN users u ON u.id = d.created_by
LEFT JOIN pipeline_runs r ON r.id = d.run_id
LEFT JOIN pipeline_jobs j ON j.id = d.job_id
WHERE d.id = $1
`

type GetDeploymentDetailRow struct {
	Deployment      Deployment `json:"deployment"`
	EnvironmentName string     `json:"environment_name"`
	CreatedByName   string     `json:"created_by_name"`
	RunNumber       int32      `json:"run_number"`
	JobName         string     `json:"job_name"`
	IsCurrent       bool       `json:"is_current"`
}

func (q *Queries) GetDeploymentDetail(ctx context.Context, id uuid.UUID) (GetDeploymentDetailRow, error) {
	row := q.db.QueryRow(ctx, getDeploymentDetail, id)
	var i GetDeploymentDetailRow
	err := row.Scan(
		&i.Deployment.ID,
		&i.Deployment.OrganizationID,
		&i.Deployment.ProjectID,
		&i.Deployment.EnvironmentID,
		&i.Deployment.Number,
		&i.Deployment.TargetID,
		&i.Deployment.TargetName,
		&i.Deployment.TargetKind,
		&i.Deployment.Version,
		&i.Deployment.PreviousVersion,
		&i.Deployment.Strategy,
		&i.Deployment.Status,
		&i.Deployment.FailureReason,
		&i.Deployment.Reverted,
		&i.Deployment.Health,
		&i.Deployment.RunID,
		&i.Deployment.JobID,
		&i.Deployment.RollbackOfID,
		&i.Deployment.CreatedBy,
		&i.Deployment.LogBytes,
		&i.Deployment.StartedAt,
		&i.Deployment.FinishedAt,
		&i.Deployment.CreatedAt,
		&i.Deployment.UpdatedAt,
		&i.EnvironmentName,
		&i.CreatedByName,
		&i.RunNumber,
		&i.JobName,
		&i.IsCurrent,
	)
	return i, err
}

const insertDeploymentLog = `-- name: InsertDeploymentLog :execrows
INSERT INTO deployment_log_chunks (deployment_id, seq, content) VALUES ($1, $2, $3)
ON CONFLICT (deployment_id, seq) DO NOTHING
`

type InsertDeploymentLogParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	Seq          int32     `json:"seq"`
	Content      string    `json:"content"`
}

func (q *Queries) InsertDeploymentLog(ctx context.Context, arg InsertDeploymentLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDeploymentLog, arg.DeploymentID, arg.Seq, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeployTargets = `-- name: ListDeployTargets :many
SELECT id, organization_id, name, kind, description, config, credentials_enc, last_test_at, last_test_ok, created_by, version, created_at, updated_at FROM deploy_targets WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListDeployTargets(ctx context.Context, organizationID uuid.UUID) ([]DeployTarget, error) {
	rows, err := q.db.Query(ctx, listDeployTargets, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeployTarget{}
	for rows.Next() {
		var i DeployTarget
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.Config,
			&i.CredentialsEnc,
			&i.LastTestAt,
			&i.LastTestOk,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT seq, content FROM deployment_log_chunks
WHERE deployment_id = $1 AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListDeploymentLogsParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	AfterSeq     int32     `json:"after_seq"`
	PageSize     int32     `json:"page_size"`
}

type ListDeploymentLogsRow struct {
	Seq     int32  `json:"seq"`
	Content string `json:"content"`
}

func (q *Queries) ListDeploymentLogs(ctx context.Context, arg ListDeploymentLogsParams) ([]ListDeploymentLogsRow, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, arg.DeploymentID, arg.AfterSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentLogsRow{}
	for rows.Next() {
		var i ListDeploymentLogsRow
		if err := rows.Scan(&i.Seq, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT d.id, d.organization_id, d.project_id, d.environment_id, d.number, d.target_id, d.target_name, d.target_kind, d.version, d.previous_version, d.strategy, d.status, d.failure_reason, d.reverted, d.health, d.run_id, d.job_id, d.rollback_of_id, d.created_by, d.log_bytes, d.started_at, d.finished_at, d.created_at, d.updated_at, e.name AS environment_name, coalesce(u.display_name, '')::text AS created_by_name,
       coalesce(r.number, 0)::integer AS run_number, coalesce(j.name, '')::text AS job_name,
       (e.current_deployment_id IS NOT DISTINCT FROM d.id)::boolean AS is_current
FROM deployments d
JOIN environments e ON e.id = d.environment_id
LEFT JOIN users u ON u.id = d.created_by
LEFT JOIN pipeline_runs r ON r.id = d.run_id
LEFT JOIN pipeline_jobs j ON j.id = d.job_id
WHERE d.project_id = $1
  AND ($2::uuid IS NULL OR d.environment_id = $2)
  AND ($3::text IS NULL OR d.status::text = $3)
  AND ($4::timestamptz IS NULL OR d.created_at >= $4)
  AND ($5::timestamptz IS NULL OR d.created_at < $5)
  AND (NOT $6::boolean OR e.current_deployment_id = d.id)
  AND ($7::timestamptz IS NULL OR (d.created_at, d.id) < ($7, $8::uuid))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $9
`

type ListDeploymentsParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
	Status        *string    `json:"status"`
	FromTime      *time.Time `json:"from_time"`
	ToTime        *time.Time `json:"to_time"`
	OnlyCurrent   bool       `json:"only_current"`
	CursorTime    *time.Time `json:"cursor_time"`
	CursorID      *uuid.UUID `json:"cursor_id"`
	PageSize      int32      `json:"page_size"`
}

type ListDeploymentsRow struct {
	Deployment      Deployment `json:"deployment"`
	EnvironmentName string     `json:"environment_name"`
	CreatedByName   string     `json:"created_by_name"`
	RunNumber       int32      `json:"run_number"`
	JobName         string     `json:"job_name"`
	IsCurrent       bool       `json:"is_current"`
}

// Newest first; keyset pagination on (created_at, id).
func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
		arg.OnlyCurrent,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsRow{}
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.Deployment.ID,
			&i.Deployment.OrganizationID,
			&i.Deployment.ProjectID,
			&i.Deployment.EnvironmentID,
			&i.Deployment.Number,
			&i.Deployment.TargetID,
			&i.Deployment.TargetName,
			&i.Deployment.TargetKind,
			&i.Deployment.Version,
			&i.Deployment.PreviousVersion,
			&i.Deployment.Strategy,
			&i.Deployment.Status,
			&i.Deployment.FailureReason,
			&i.Deployment.Reverted,
			&i.Deployment.Health,
			&i.Deployment.RunID,
			&i.Deployment.JobID,
			&i.Deployment.RollbackOfID,
			&i.Deployment.CreatedBy,
			&i.Deployment.LogBytes,
			&i.Deployment.StartedAt,
			&i.Deployment.FinishedAt,
			&i.Deployment.CreatedAt,
			&i.Deployment.UpdatedAt,
			&i.EnvironmentName,
			&i.CreatedByName,
			&i.RunNumber,
			&i.JobName,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDeploymentNumber = `-- name: NextDeploymentNumber :one
UPDATE projects SET last_deployment_number = last_deployment_number + 1 WHERE id = $1 RETURNING last_deployment_number
`

func (q *Queries) NextDeploymentNumber(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextDeploymentNumber, id)
	var last_deployment_number int32
	err := row.Scan(&last_deployment_number)
	return last_deployment_number, err
}

const nextJobLogSeq = `-- name: NextJobLogSeq :one
SELECT (coalesce(max(seq), -1) + 1)::integer FROM job_log_chunks WHERE job_id = $1
`

func (q *Queries) NextJobLogSeq(ctx context.Context, jobID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextJobLogSeq, jobID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const previousSuccessfulDeployment = `-- name: PreviousSuccessfulDeployment :one
SELECT id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at FROM deployments
WHERE environment_id = $1 AND status = 'succeeded' AND created_at < $2 AND id <> $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type PreviousSuccessfulDeploymentParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Before        time.Time `json:"before"`
	ExcludeID     uuid.UUID `json:"exclude_id"`
}

// The latest successful deployment of the environment before the given time.
func (q *Queries) PreviousSuccessfulDeployment(ctx context.Context, arg PreviousSuccessfulDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, previousSuccessfulDeployment, arg.EnvironmentID, arg.Before, arg.ExcludeID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordTargetTest = `-- name: RecordTargetTest :exec
UPDATE deploy_targets SET last_test_at = now(), last_test_ok = $1 WHERE id = $2
`

type RecordTargetTestParams struct {
	Ok *bool     `json:"ok"`
	ID uuid.UUID `json:"id"`
}

func (q *Queries) RecordTargetTest(ctx context.Context, arg RecordTargetTestParams) error {
	_, err := q.db.Exec(ctx, recordTargetTest, arg.Ok, arg.ID)
	return err
}

const setCurrentDeployment = `-- name: SetCurrentDeployment :exec
UPDATE environments SET current_deployment_id = $1 WHERE id = $2
`

type SetCurrentDeploymentParams struct {
	DeploymentID *uuid.UUID `json:"deployment_id"`
	ID           uuid.UUID  `json:"id"`
}

func (q *Queries) SetCurrentDeployment(ctx context.Context, arg SetCurrentDeploymentParams) error {
	_, err := q.db.Exec(ctx, setCurrentDeployment, arg.DeploymentID, arg.ID)
	return err
}

const startDeployment = `-- name: StartDeployment :one
UPDATE deployments SET status = 'running', started_at = now() WHERE id = $1 AND status = 'pending' RETURNING id, organization_id, project_id, environment_id, number, target_id, target_name, target_kind, version, previous_version, strategy, status, failure_reason, reverted, health, run_id, job_id, rollback_of_id, created_by, log_bytes, started_at, finished_at, created_at, updated_at
`

func (q *Queries) StartDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, startDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Number,
		&i.TargetID,
		&i.TargetName,
		&i.TargetKind,
		&i.Version,
		&i.PreviousVersion,
		&i.Strategy,
		&i.Status,
		&i.FailureReason,
		&i.Reverted,
		&i.Health,
		&i.RunID,
		&i.JobID,
		&i.RollbackOfID,
		&i.CreatedBy,
		&i.LogBytes,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeployTarget = `-- name: UpdateDeployTarget :one
UPDATE deploy_targets SET description = $1, config = $2, credentials_enc = $3,
  version = version + 1
WHERE id = $4 AND version = $5
RETURNING id, organization_id, name, kind, description, config, credentials_enc, last_test_at, last_test_ok, created_by, version, created_at, updated_at
`

type UpdateDeployTargetParams struct {
	Description    string    `json:"description"`
	Config         []byte    `json:"config"`
	CredentialsEnc []byte    `json:"credentials_enc"`
	ID             uuid.UUID `json:"id"`
	Version        int32     `json:"version"`
}

func (q *Queries) UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (DeployTarget, error) {
	row := q.db.QueryRow(ctx, updateDeployTarget,
		arg.Description,
		arg.Config,
		arg.CredentialsEnc,
		arg.ID,
		arg.Version,
	)
	var i DeployTarget
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Config,
		&i.CredentialsEnc,
		&i.LastTestAt,
		&i.LastTestOk,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
