// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT count(*) FROM environments WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountEnvironments(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironments, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, kind, variables)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, kind, variables, version, created_at, updated_at, deleted_at, current_deployment_id
`

type CreateEnvironmentParams struct {
	ProjectID uuid.UUID       `json:"project_id"`
	Name      string          `json:"name"`
	Kind      EnvironmentKind `json:"kind"`
	Variables []byte          `json:"variables"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Variables,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Variables,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CurrentDeploymentID,
	)
	return i, err
}

const deleteProtectionRule = `-- name: DeleteProtectionRule :exec
DELETE FROM protection_rules WHERE environment_id = $1
`

func (q *Queries) DeleteProtectionRule(ctx context.Context, environmentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProtectionRule, environmentID)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT e.id, e.project_id, e.name, e.kind, e.variables, e.version, e.created_at, e.updated_at, e.deleted_at, e.current_deployment_id,
       (pr.environment_id IS NOT NULL)::boolean AS protected,
       coalesce(pr.required_approvals, 0)::integer AS required_approvals,
       coalesce(pr.allowed_branches, '{}')::text[] AS allowed_branches,
       coalesce(pr.allowed_roles::text[], '{}')::text[] AS allowed_roles
FROM environments e
LEFT JOIN protection_rules pr ON pr.environment_id = e.id
WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetEnvironmentRow struct {
	Environment       Environment `json:"environment"`
	Protected         bool        `json:"protected"`
	RequiredApprovals int32       `json:"required_approvals"`
	AllowedBranches   []string    `json:"allowed_branches"`
	AllowedRoles      []string    `json:"allowed_roles"`
}

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.Environment.ID,
		&i.Environment.ProjectID,
		&i.Environment.Name,
		&i.Environment.Kind,
		&i.Environment.Variables,
		&i.Environment.Version,
		&i.Environment.CreatedAt,
		&i.Environment.UpdatedAt,
		&i.Environment.DeletedAt,
		&i.Environment.CurrentDeploymentID,
		&i.Protected,
		&i.RequiredApprovals,
		&i.AllowedBranches,
		&i.AllowedRoles,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT e.id, e.project_id, e.name, e.kind, e.variables, e.version, e.created_at, e.updated_at, e.deleted_at, e.current_deployment_id,
       (pr.environment_id IS NOT NULL)::boolean AS protected,
       coalesce(pr.required_approvals, 0)::integer AS required_approvals,
       coalesce(pr.allowed_branches, '{}')::text[] AS allowed_branches,
       coalesce(pr.allowed_roles::text[], '{}')::text[] AS allowed_roles
FROM environments e
LEFT JOIN protection_rules pr ON pr.environment_id = e.id
WHERE e.project_id = $1 AND e.deleted_at IS NULL
ORDER BY e.kind, e.name
`

type ListEnvironmentsRow struct {
	Environment       Environment `json:"environment"`
	Protected         bool        `json:"protected"`
	RequiredApprovals int32       `json:"required_approvals"`
	AllowedBranches   []string    `json:"allowed_branches"`
	AllowedRoles      []string    `json:"allowed_roles"`
}

// Ordered development, staging, production, then by name.
func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.Environment.ID,
			&i.Environment.ProjectID,
			&i.Environment.Name,
			&i.Environment.Kind,
			&i.Environment.Variables,
			&i.Environment.Version,
			&i.Environment.CreatedAt,
			&i.Environment.UpdatedAt,
			&i.Environment.DeletedAt,
			&i.Environment.CurrentDeploymentID,
			&i.Protected,
			&i.RequiredApprovals,
			&i.AllowedBranches,
			&i.AllowedRoles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEnvironment = `-- name: SoftDeleteEnvironment :exec
UPDATE environments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEnvironment, id)
	return err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET kind = $1, variables = $2, version = version + 1
WHERE id = $3 AND version = $4 AND deleted_at IS NULL
RETURNING id, project_id, name, kind, variables, version, created_at, updated_at, deleted_at, current_deployment_id
`

type UpdateEnvironmentParams struct {
	Kind      EnvironmentKind `json:"kind"`
	Variables []byte          `json:"variables"`
	ID        uuid.UUID       `json:"id"`
	Version   int32           `json:"version"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.Kind,
		arg.Variables,
		arg.ID,
		arg.Version,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Variables,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CurrentDeploymentID,
	)
	return i, err
}

const upsertProtectionRule = `-- name: UpsertProtectionRule :exec
INSERT INTO protection_rules (environment_id, required_approvals, allowed_branches, allowed_roles)
VALUES ($1, $2, $3::text[], CAST($4::text[] AS member_role[]))
ON CONFLICT (environment_id) DO UPDATE SET
  required_approvals = EXCLUDED.required_approvals,
  allowed_branches = EXCLUDED.allowed_branches,
  allowed_roles = EXCLUDED.allowed_roles
`

type UpsertProtectionRuleParams struct {
	EnvironmentID     uuid.UUID `json:"environment_id"`
	RequiredApprovals int32     `json:"required_approvals"`
	AllowedBranches   []string  `json:"allowed_branches"`
	AllowedRoles      []string  `json:"allowed_roles"`
}

func (q *Queries) UpsertProtectionRule(ctx context.Context, arg UpsertProtectionRuleParams) error {
	_, err := q.db.Exec(ctx, upsertProtectionRule,
		arg.EnvironmentID,
		arg.RequiredApprovals,
		arg.AllowedBranches,
		arg.AllowedRoles,
	)
	return err
}
