// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, key) DO UPDATE SET
  request_hash = EXCLUDED.request_hash, response_status = NULL, response_body = NULL,
  created_at = now(), expires_at = EXCLUDED.expires_at
WHERE idempotency_keys.expires_at <= now()
RETURNING id
`

type ClaimIdempotencyKeyParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Key         string    `json:"key"`
	RequestHash []byte    `json:"request_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// Inserts an in-flight record (or takes over an expired one); returns no row when a live
// record already exists for this user and key.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey,
		arg.UserID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys SET response_status = $1, response_body = $2
WHERE id = $3
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey, arg.ResponseStatus, arg.ResponseBody, arg.ID)
	return err
}

const deleteExpiredHousekeeping = `-- name: DeleteExpiredHousekeeping :exec
WITH k AS (DELETE FROM idempotency_keys WHERE expires_at < now())
DELETE FROM webhook_deliveries WHERE received_at < now() - interval '30 days'
`

// Periodic cleanup: expired idempotency keys and webhook deliveries older than 30 days.
func (q *Queries) DeleteExpiredHousekeeping(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredHousekeeping)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, key, request_hash, response_status, response_body, created_at, expires_at FROM idempotency_keys WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID `json:"user_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE id = $1
`

// The request failed with a server error: forget the key so the client can retry.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, id)
	return err
}
