// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countIdentities = `-- name: CountIdentities :one
SELECT count(*) FROM user_identities WHERE user_id = $1
`

func (q *Queries) CountIdentities(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (user_id, provider, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, subject, email, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
	Subject  string    `json:"subject"`
	Email    *string   `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :one
DELETE FROM user_identities WHERE id = $1 AND user_id = $2 RETURNING id, user_id, provider, subject, email, created_at, updated_at
`

type DeleteIdentityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, deleteIdentity, arg.ID, arg.UserID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.email, u.display_name, u.password_hash, u.email_verified_at, u.locale, u.timezone, u.khmer_numerals, u.totp_secret_enc, u.totp_pending_enc, u.totp_enabled_at, u.totp_last_step, u.failed_login_count, u.lockout_level, u.locked_until, u.password_changed_at, u.is_platform_admin, u.disabled_at, u.last_login_at, u.version, u.created_at, u.updated_at, u.deleted_at FROM user_identities i
JOIN users u ON u.id = i.user_id
WHERE i.provider = $1 AND i.subject = $2 AND u.deleted_at IS NULL
`

type GetUserByIdentityParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.Timezone,
		&i.KhmerNumerals,
		&i.TotpSecretEnc,
		&i.TotpPendingEnc,
		&i.TotpEnabledAt,
		&i.TotpLastStep,
		&i.FailedLoginCount,
		&i.LockoutLevel,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, user_id, provider, subject, email, created_at, updated_at FROM user_identities WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListIdentities(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Subject,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
