// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: infrastructure.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO infra_assets (organization_id, kind, name, address, description, tags, metadata, tls_port, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, kind, name, address, description, tags, metadata, tls_port, agent_token_hash, agent_token_prefix, agent_version, agent_hostname, agent_os, agent_arch, last_heartbeat_at, last_metrics, created_by, version, created_at, updated_at
`

type CreateAssetParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Kind           AssetKind  `json:"kind"`
	Name           string     `json:"name"`
	Address        string     `json:"address"`
	Description    string     `json:"description"`
	Tags           []string   `json:"tags"`
	Metadata       []byte     `json:"metadata"`
	TlsPort        int32      `json:"tls_port"`
	CreatedBy      *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (InfraAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.OrganizationID,
		arg.Kind,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.Tags,
		arg.Metadata,
		arg.TlsPort,
		arg.CreatedBy,
	)
	var i InfraAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.TlsPort,
		&i.AgentTokenHash,
		&i.AgentTokenPrefix,
		&i.AgentVersion,
		&i.AgentHostname,
		&i.AgentOs,
		&i.AgentArch,
		&i.LastHeartbeatAt,
		&i.LastMetrics,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :execrows
DELETE FROM infra_assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM ssl_certificates WHERE asset_id = $1
`

func (q *Queries) DeleteCertificate(ctx context.Context, assetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCertificate, assetID)
	return err
}

const deleteOldHourlyMetrics = `-- name: DeleteOldHourlyMetrics :execrows
DELETE FROM asset_metrics_hourly WHERE hour < $1
`

func (q *Queries) DeleteOldHourlyMetrics(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldHourlyMetrics, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dueCertificateChecks = `-- name: DueCertificateChecks :many
SELECT a.id, a.address, a.tls_port FROM infra_assets a
LEFT JOIN ssl_certificates c ON c.asset_id = a.id
WHERE a.kind = 'domain' AND a.address <> '' AND (c.asset_id IS NULL OR c.next_check_at <= now())
ORDER BY c.next_check_at NULLS FIRST
LIMIT 200
`

type DueCertificateChecksRow struct {
	ID      uuid.UUID `json:"id"`
	Address string    `json:"address"`
	TlsPort int32     `json:"tls_port"`
}

// Domain assets whose certificate is due for a check (or was never checked).
func (q *Queries) DueCertificateChecks(ctx context.Context) ([]DueCertificateChecksRow, error) {
	rows, err := q.db.Query(ctx, dueCertificateChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueCertificateChecksRow{}
	for rows.Next() {
		var i DueCertificateChecksRow
		if err := rows.Scan(&i.ID, &i.Address, &i.TlsPort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAsset = `-- name: GetAsset :one
SELECT id, organization_id, kind, name, address, description, tags, metadata, tls_port, agent_token_hash, agent_token_prefix, agent_version, agent_hostname, agent_os, agent_arch, last_heartbeat_at, last_metrics, created_by, version, created_at, updated_at FROM infra_assets WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (InfraAsset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i InfraAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.TlsPort,
		&i.AgentTokenHash,
		&i.AgentTokenPrefix,
		&i.AgentVersion,
		&i.AgentHostname,
		&i.AgentOs,
		&i.AgentArch,
		&i.LastHeartbeatAt,
		&i.LastMetrics,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByAgentToken = `-- name: GetAssetByAgentToken :one
SELECT id, organization_id, kind, name, address, description, tags, metadata, tls_port, agent_token_hash, agent_token_prefix, agent_version, agent_hostname, agent_os, agent_arch, last_heartbeat_at, last_metrics, created_by, version, created_at, updated_at FROM infra_assets WHERE agent_token_hash = $1
`

func (q *Queries) GetAssetByAgentToken(ctx context.Context, tokenHash []byte) (InfraAsset, error) {
	row := q.db.QueryRow(ctx, getAssetByAgentToken, tokenHash)
	var i InfraAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.TlsPort,
		&i.AgentTokenHash,
		&i.AgentTokenPrefix,
		&i.AgentVersion,
		&i.AgentHostname,
		&i.AgentOs,
		&i.AgentArch,
		&i.LastHeartbeatAt,
		&i.LastMetrics,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCertificate = `-- name: GetCertificate :one
SELECT asset_id, host, port, subject, issuer, dns_names, serial, fingerprint, not_before, not_after, error, last_checked_at, next_check_at FROM ssl_certificates WHERE asset_id = $1
`

func (q *Queries) GetCertificate(ctx context.Context, assetID uuid.UUID) (SslCertificate, error) {
	row := q.db.QueryRow(ctx, getCertificate, assetID)
	var i SslCertificate
	err := row.Scan(
		&i.AssetID,
		&i.Host,
		&i.Port,
		&i.Subject,
		&i.Issuer,
		&i.DnsNames,
		&i.Serial,
		&i.Fingerprint,
		&i.NotBefore,
		&i.NotAfter,
		&i.Error,
		&i.LastCheckedAt,
		&i.NextCheckAt,
	)
	return i, err
}

const hourlyMetricSeries = `-- name: HourlyMetricSeries :many
SELECT date_bin(make_interval(secs => $1::integer), hour, TIMESTAMPTZ '2000-01-01')::timestamptz AS bucket,
       coalesce(sum(cpu_avg * samples) FILTER (WHERE cpu_avg IS NOT NULL) / nullif(sum(samples) FILTER (WHERE cpu_avg IS NOT NULL), 0), -1)::real AS cpu_avg,
       coalesce(max(cpu_max), -1)::real AS cpu_max,
       coalesce(sum(mem_avg * samples) FILTER (WHERE mem_avg IS NOT NULL) / nullif(sum(samples) FILTER (WHERE mem_avg IS NOT NULL), 0), -1)::real AS mem_avg,
       coalesce(max(mem_max), -1)::real AS mem_max,
       coalesce(sum(disk_avg * samples) FILTER (WHERE disk_avg IS NOT NULL) / nullif(sum(samples) FILTER (WHERE disk_avg IS NOT NULL), 0), -1)::real AS disk_avg,
       coalesce(max(disk_max), -1)::real AS disk_max
FROM asset_metrics_hourly
WHERE asset_id = $2 AND hour >= $3 AND hour < $4
GROUP BY bucket
ORDER BY bucket
`

type HourlyMetricSeriesParams struct {
	StepSeconds int32     `json:"step_seconds"`
	AssetID     uuid.UUID `json:"asset_id"`
	FromTime    time.Time `json:"from_time"`
	ToTime      time.Time `json:"to_time"`
}

type HourlyMetricSeriesRow struct {
	Bucket  time.Time `json:"bucket"`
	CpuAvg  float32   `json:"cpu_avg"`
	CpuMax  float32   `json:"cpu_max"`
	MemAvg  float32   `json:"mem_avg"`
	MemMax  float32   `json:"mem_max"`
	DiskAvg float32   `json:"disk_avg"`
	DiskMax float32   `json:"disk_max"`
}

// The same from hourly rollups (for ranges beyond the raw retention); -1 = no data.
func (q *Queries) HourlyMetricSeries(ctx context.Context, arg HourlyMetricSeriesParams) ([]HourlyMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, hourlyMetricSeries,
		arg.StepSeconds,
		arg.AssetID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HourlyMetricSeriesRow{}
	for rows.Next() {
		var i HourlyMetricSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.CpuAvg,
			&i.CpuMax,
			&i.MemAvg,
			&i.MemMax,
			&i.DiskAvg,
			&i.DiskMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMetric = `-- name: InsertMetric :exec
INSERT INTO asset_metrics (asset_id, ts, cpu_pct, mem_pct, disk_pct, load1)
VALUES ($1, date_trunc('second', now()), $2, $3, $4, $5)
ON CONFLICT (asset_id, ts) DO NOTHING
`

type InsertMetricParams struct {
	AssetID uuid.UUID `json:"asset_id"`
	CpuPct  *float32  `json:"cpu_pct"`
	MemPct  *float32  `json:"mem_pct"`
	DiskPct *float32  `json:"disk_pct"`
	Load1   *float32  `json:"load1"`
}

// One sample per asset and second; a re-sent heartbeat within the same second is ignored.
func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) error {
	_, err := q.db.Exec(ctx, insertMetric,
		arg.AssetID,
		arg.CpuPct,
		arg.MemPct,
		arg.DiskPct,
		arg.Load1,
	)
	return err
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.organization_id, a.kind, a.name, a.address, a.description, a.tags, a.metadata, a.tls_port, a.agent_token_hash, a.agent_token_prefix, a.agent_version, a.agent_hostname, a.agent_os, a.agent_arch, a.last_heartbeat_at, a.last_metrics, a.created_by, a.version, a.created_at, a.updated_at, c.not_after AS cert_not_after, coalesce(c.error, '')::text AS cert_error, c.last_checked_at AS cert_checked_at
FROM infra_assets a
LEFT JOIN ssl_certificates c ON c.asset_id = a.id
WHERE a.organization_id = $1
  AND ($2::text IS NULL OR a.kind::text = $2)
  AND ($3::text IS NULL OR $3::text = ANY(a.tags))
  AND ($4::text IS NULL OR a.name ILIKE '%' || $4 || '%' OR a.address ILIKE '%' || $4 || '%')
ORDER BY a.kind, a.name
LIMIT 1000
`

type ListAssetsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Kind           *string   `json:"kind"`
	Tag            *string   `json:"tag"`
	Search         *string   `json:"search"`
}

type ListAssetsRow struct {
	ID               uuid.UUID  `json:"id"`
	OrganizationID   uuid.UUID  `json:"organization_id"`
	Kind             AssetKind  `json:"kind"`
	Name             string     `json:"name"`
	Address          string     `json:"address"`
	Description      string     `json:"description"`
	Tags             []string   `json:"tags"`
	Metadata         []byte     `json:"metadata"`
	TlsPort          int32      `json:"tls_port"`
	AgentTokenHash   []byte     `json:"agent_token_hash"`
	AgentTokenPrefix string     `json:"agent_token_prefix"`
	AgentVersion     string     `json:"agent_version"`
	AgentHostname    string     `json:"agent_hostname"`
	AgentOs          string     `json:"agent_os"`
	AgentArch        string     `json:"agent_arch"`
	LastHeartbeatAt  *time.Time `json:"last_heartbeat_at"`
	LastMetrics      []byte     `json:"last_metrics"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	Version          int32      `json:"version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	CertNotAfter     *time.Time `json:"cert_not_after"`
	CertError        string     `json:"cert_error"`
	CertCheckedAt    *time.Time `json:"cert_checked_at"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.OrganizationID,
		arg.Kind,
		arg.Tag,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetsRow{}
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Kind,
			&i.Name,
			&i.Address,
			&i.Description,
			&i.Tags,
			&i.Metadata,
			&i.TlsPort,
			&i.AgentTokenHash,
			&i.AgentTokenPrefix,
			&i.AgentVersion,
			&i.AgentHostname,
			&i.AgentOs,
			&i.AgentArch,
			&i.LastHeartbeatAt,
			&i.LastMetrics,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CertNotAfter,
			&i.CertError,
			&i.CertCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT c.asset_id, c.host, c.port, c.subject, c.issuer, c.dns_names, c.serial, c.fingerprint, c.not_before, c.not_after, c.error, c.last_checked_at, c.next_check_at, a.name AS asset_name, a.tags AS asset_tags
FROM ssl_certificates c
JOIN infra_assets a ON a.id = c.asset_id
WHERE a.organization_id = $1
  AND ($2::timestamptz IS NULL OR c.not_after < $2 OR c.error <> '')
ORDER BY c.not_after NULLS FIRST, a.name
`

type ListCertificatesParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ExpiringBefore *time.Time `json:"expiring_before"`
}

type ListCertificatesRow struct {
	SslCertificate SslCertificate `json:"ssl_certificate"`
	AssetName      string         `json:"asset_name"`
	AssetTags      []string       `json:"asset_tags"`
}

// Certificates of the organization's domains, soonest expiry first; expiring_before (optional)
// keeps those expiring earlier or failing.
func (q *Queries) ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error) {
	rows, err := q.db.Query(ctx, listCertificates, arg.OrganizationID, arg.ExpiringBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificatesRow{}
	for rows.Next() {
		var i ListCertificatesRow
		if err := rows.Scan(
			&i.SslCertificate.AssetID,
			&i.SslCertificate.Host,
			&i.SslCertificate.Port,
			&i.SslCertificate.Subject,
			&i.SslCertificate.Issuer,
			&i.SslCertificate.DnsNames,
			&i.SslCertificate.Serial,
			&i.SslCertificate.Fingerprint,
			&i.SslCertificate.NotBefore,
			&i.SslCertificate.NotAfter,
			&i.SslCertificate.Error,
			&i.SslCertificate.LastCheckedAt,
			&i.SslCertificate.NextCheckAt,
			&i.AssetName,
			&i.AssetTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintainMetricPartitions = `-- name: MaintainMetricPartitions :exec
SELECT opshub_maintain_metric_partitions($1::integer)
`

func (q *Queries) MaintainMetricPartitions(ctx context.Context, keepMonths int32) error {
	_, err := q.db.Exec(ctx, maintainMetricPartitions, keepMonths)
	return err
}

const rawMetricSeries = `-- name: RawMetricSeries :many
SELECT date_bin(make_interval(secs => $1::integer), ts, TIMESTAMPTZ '2000-01-01')::timestamptz AS bucket,
       coalesce(avg(cpu_pct), -1)::real AS cpu_avg, coalesce(max(cpu_pct), -1)::real AS cpu_max,
       coalesce(avg(mem_pct), -1)::real AS mem_avg, coalesce(max(mem_pct), -1)::real AS mem_max,
       coalesce(avg(disk_pct), -1)::real AS disk_avg, coalesce(max(disk_pct), -1)::real AS disk_max
FROM asset_metrics
WHERE asset_id = $2 AND ts >= $3 AND ts < $4
GROUP BY bucket
ORDER BY bucket
`

type RawMetricSeriesParams struct {
	StepSeconds int32     `json:"step_seconds"`
	AssetID     uuid.UUID `json:"asset_id"`
	FromTime    time.Time `json:"from_time"`
	ToTime      time.Time `json:"to_time"`
}

type RawMetricSeriesRow struct {
	Bucket  time.Time `json:"bucket"`
	CpuAvg  float32   `json:"cpu_avg"`
	CpuMax  float32   `json:"cpu_max"`
	MemAvg  float32   `json:"mem_avg"`
	MemMax  float32   `json:"mem_max"`
	DiskAvg float32   `json:"disk_avg"`
	DiskMax float32   `json:"disk_max"`
}

// Averages and maxima per step (seconds) from the raw samples; -1 = no data in the bucket.
func (q *Queries) RawMetricSeries(ctx context.Context, arg RawMetricSeriesParams) ([]RawMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, rawMetricSeries,
		arg.StepSeconds,
		arg.AssetID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawMetricSeriesRow{}
	for rows.Next() {
		var i RawMetricSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.CpuAvg,
			&i.CpuMax,
			&i.MemAvg,
			&i.MemMax,
			&i.DiskAvg,
			&i.DiskMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordHeartbeat = `-- name: RecordHeartbeat :exec
UPDATE infra_assets SET last_heartbeat_at = now(), agent_version = $1, agent_hostname = $2,
  agent_os = $3, agent_arch = $4, last_metrics = $5
WHERE id = $6
`

type RecordHeartbeatParams struct {
	AgentVersion  string    `json:"agent_version"`
	AgentHostname string    `json:"agent_hostname"`
	AgentOs       string    `json:"agent_os"`
	AgentArch     string    `json:"agent_arch"`
	LastMetrics   []byte    `json:"last_metrics"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordHeartbeat,
		arg.AgentVersion,
		arg.AgentHostname,
		arg.AgentOs,
		arg.AgentArch,
		arg.LastMetrics,
		arg.ID,
	)
	return err
}

const rollupMetrics = `-- name: RollupMetrics :execrows
INSERT INTO asset_metrics_hourly (asset_id, hour, cpu_avg, cpu_max, mem_avg, mem_max, disk_avg, disk_max, samples)
SELECT asset_id, date_trunc('hour', ts), avg(cpu_pct), max(cpu_pct), avg(mem_pct), max(mem_pct), avg(disk_pct), max(disk_pct), count(*)
FROM asset_metrics
WHERE ts >= $1 AND ts < $2
GROUP BY asset_id, date_trunc('hour', ts)
ON CONFLICT (asset_id, hour) DO UPDATE SET
  cpu_avg = EXCLUDED.cpu_avg, cpu_max = EXCLUDED.cpu_max, mem_avg = EXCLUDED.mem_avg, mem_max = EXCLUDED.mem_max,
  disk_avg = EXCLUDED.disk_avg, disk_max = EXCLUDED.disk_max, samples = EXCLUDED.samples
`

type RollupMetricsParams struct {
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

// Summarizes raw samples of whole hours in [from, to) into hourly rows (idempotent).
func (q *Queries) RollupMetrics(ctx context.Context, arg RollupMetricsParams) (int64, error) {
	result, err := q.db.Exec(ctx, rollupMetrics, arg.FromTime, arg.ToTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAgentToken = `-- name: SetAgentToken :one
UPDATE infra_assets SET agent_token_hash = $1, agent_token_prefix = $2, version = version + 1
WHERE id = $3
RETURNING id, organization_id, kind, name, address, description, tags, metadata, tls_port, agent_token_hash, agent_token_prefix, agent_version, agent_hostname, agent_os, agent_arch, last_heartbeat_at, last_metrics, created_by, version, created_at, updated_at
`

type SetAgentTokenParams struct {
	TokenHash   []byte    `json:"token_hash"`
	TokenPrefix string    `json:"token_prefix"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) SetAgentToken(ctx context.Context, arg SetAgentTokenParams) (InfraAsset, error) {
	row := q.db.QueryRow(ctx, setAgentToken, arg.TokenHash, arg.TokenPrefix, arg.ID)
	var i InfraAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.TlsPort,
		&i.AgentTokenHash,
		&i.AgentTokenPrefix,
		&i.AgentVersion,
		&i.AgentHostname,
		&i.AgentOs,
		&i.AgentArch,
		&i.LastHeartbeatAt,
		&i.LastMetrics,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE infra_assets SET name = $1, address = $2, description = $3, tags = $4,
  metadata = $5, tls_port = $6, version = version + 1
WHERE id = $7 AND version = $8
RETURNING id, organization_id, kind, name, address, description, tags, metadata, tls_port, agent_token_hash, agent_token_prefix, agent_version, agent_hostname, agent_os, agent_arch, last_heartbeat_at, last_metrics, created_by, version, created_at, updated_at
`

type UpdateAssetParams struct {
	Name        string    `json:"name"`
	Address     string    `json:"address"`
	Description string    `json:"description"`
	Tags        []string  `json:"tags"`
	Metadata    []byte    `json:"metadata"`
	TlsPort     int32     `json:"tls_port"`
	ID          uuid.UUID `json:"id"`
	Version     int32     `json:"version"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InfraAsset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Name,
		arg.Address,
		arg.Description,
		arg.Tags,
		arg.Metadata,
		arg.TlsPort,
		arg.ID,
		arg.Version,
	)
	var i InfraAsset
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Kind,
		&i.Name,
		&i.Address,
		&i.Description,
		&i.Tags,
		&i.Metadata,
		&i.TlsPort,
		&i.AgentTokenHash,
		&i.AgentTokenPrefix,
		&i.AgentVersion,
		&i.AgentHostname,
		&i.AgentOs,
		&i.AgentArch,
		&i.LastHeartbeatAt,
		&i.LastMetrics,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCertificate = `-- name: UpsertCertificate :one
INSERT INTO ssl_certificates (asset_id, host, port, subject, issuer, dns_names, serial, fingerprint, not_before, not_after,
  error, last_checked_at, next_check_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, now(), $12)
ON CONFLICT (asset_id) DO UPDATE SET host = EXCLUDED.host, port = EXCLUDED.port, subject = EXCLUDED.subject,
  issuer = EXCLUDED.issuer, dns_names = EXCLUDED.dns_names, serial = EXCLUDED.serial, fingerprint = EXCLUDED.fingerprint,
  -- A failed connection keeps what was known about the certificate.
  not_before = coalesce(EXCLUDED.not_before, ssl_certificates.not_before),
  not_after = coalesce(EXCLUDED.not_after, ssl_certificates.not_after),
  error = EXCLUDED.error, last_checked_at = now(), next_check_at = EXCLUDED.next_check_at
RETURNING asset_id, host, port, subject, issuer, dns_names, serial, fingerprint, not_before, not_after, error, last_checked_at, next_check_at
`

type UpsertCertificateParams struct {
	AssetID     uuid.UUID  `json:"asset_id"`
	Host        string     `json:"host"`
	Port        int32      `json:"port"`
	Subject     string     `json:"subject"`
	Issuer      string     `json:"issuer"`
	DnsNames    []string   `json:"dns_names"`
	Serial      string     `json:"serial"`
	Fingerprint string     `json:"fingerprint"`
	NotBefore   *time.Time `json:"not_before"`
	NotAfter    *time.Time `json:"not_after"`
	Error       string     `json:"error"`
	NextCheckAt time.Time  `json:"next_check_at"`
}

func (q *Queries) UpsertCertificate(ctx context.Context, arg UpsertCertificateParams) (SslCertificate, error) {
	row := q.db.QueryRow(ctx, upsertCertificate,
		arg.AssetID,
		arg.Host,
		arg.Port,
		arg.Subject,
		arg.Issuer,
		arg.DnsNames,
		arg.Serial,
		arg.Fingerprint,
		arg.NotBefore,
		arg.NotAfter,
		arg.Error,
		arg.NextCheckAt,
	)
	var i SslCertificate
	err := row.Scan(
		&i.AssetID,
		&i.Host,
		&i.Port,
		&i.Subject,
		&i.Issuer,
		&i.DnsNames,
		&i.Serial,
		&i.Fingerprint,
		&i.NotBefore,
		&i.NotAfter,
		&i.Error,
		&i.LastCheckedAt,
		&i.NextCheckAt,
	)
	return i, err
}
