// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (organization_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Email          string     `json:"email"`
	Role           MemberRole `json:"role"`
	TokenHash      []byte     `json:"token_hash"`
	InvitedBy      *uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenForUpdate = `-- name: GetInvitationByTokenForUpdate :one
SELECT i.id, i.organization_id, i.email, i.role, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, i.created_at, o.name AS organization_name, o.slug AS organization_slug, u.display_name AS invited_by_name
FROM invitations i
JOIN organizations o ON o.id = i.organization_id AND o.deleted_at IS NULL
LEFT JOIN users u ON u.id = i.invited_by
WHERE i.token_hash = $1
FOR UPDATE OF i
`

type GetInvitationByTokenForUpdateRow struct {
	ID               uuid.UUID  `json:"id"`
	OrganizationID   uuid.UUID  `json:"organization_id"`
	Email            string     `json:"email"`
	Role             MemberRole `json:"role"`
	TokenHash        []byte     `json:"token_hash"`
	InvitedBy        *uuid.UUID `json:"invited_by"`
	ExpiresAt        time.Time  `json:"expires_at"`
	AcceptedAt       *time.Time `json:"accepted_at"`
	AcceptedBy       *uuid.UUID `json:"accepted_by"`
	RevokedAt        *time.Time `json:"revoked_at"`
	CreatedAt        time.Time  `json:"created_at"`
	OrganizationName string     `json:"organization_name"`
	OrganizationSlug string     `json:"organization_slug"`
	InvitedByName    *string    `json:"invited_by_name"`
}

func (q *Queries) GetInvitationByTokenForUpdate(ctx context.Context, tokenHash []byte) (GetInvitationByTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenForUpdate, tokenHash)
	var i GetInvitationByTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.InvitedByName,
	)
	return i, err
}

const getOpenInvitationEmailByToken = `-- name: GetOpenInvitationEmailByToken :one
SELECT i.email
FROM invitations i
JOIN organizations o ON o.id = i.organization_id AND o.deleted_at IS NULL
WHERE i.token_hash = $1
  AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now()
`

// Used by sign-up when self-service registration is disabled: an open invitation for the
// same address lets the invitee create an account.
func (q *Queries) GetOpenInvitationEmailByToken(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getOpenInvitationEmailByToken, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const listOpenInvitations = `-- name: ListOpenInvitations :many
SELECT i.id, i.organization_id, i.email, i.role, i.token_hash, i.invited_by, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, i.created_at, u.display_name AS invited_by_name
FROM invitations i
LEFT JOIN users u ON u.id = i.invited_by
WHERE i.organization_id = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (i.created_at, i.id) < ($2::timestamptz, $3::uuid))
ORDER BY i.created_at DESC, i.id DESC
LIMIT $4
`

type ListOpenInvitationsParams struct {
	OrganizationID  uuid.UUID  `json:"organization_id"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	PageSize        int32      `json:"page_size"`
}

type ListOpenInvitationsRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Email          string     `json:"email"`
	Role           MemberRole `json:"role"`
	TokenHash      []byte     `json:"token_hash"`
	InvitedBy      *uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
	AcceptedAt     *time.Time `json:"accepted_at"`
	AcceptedBy     *uuid.UUID `json:"accepted_by"`
	RevokedAt      *time.Time `json:"revoked_at"`
	CreatedAt      time.Time  `json:"created_at"`
	InvitedByName  *string    `json:"invited_by_name"`
}

func (q *Queries) ListOpenInvitations(ctx context.Context, arg ListOpenInvitationsParams) ([]ListOpenInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listOpenInvitations,
		arg.OrganizationID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenInvitationsRow{}
	for rows.Next() {
		var i ListOpenInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE invitations SET accepted_at = now(), accepted_by = $1 WHERE id = $2
`

type MarkInvitationAcceptedParams struct {
	AcceptedBy *uuid.UUID `json:"accepted_by"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, arg.AcceptedBy, arg.ID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE invitations SET revoked_at = now() WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}

const revokeOpenInvitationForEmail = `-- name: RevokeOpenInvitationForEmail :exec
UPDATE invitations SET revoked_at = now()
WHERE organization_id = $1 AND email = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeOpenInvitationForEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

func (q *Queries) RevokeOpenInvitationForEmail(ctx context.Context, arg RevokeOpenInvitationForEmailParams) error {
	_, err := q.db.Exec(ctx, revokeOpenInvitationForEmail, arg.OrganizationID, arg.Email)
	return err
}
