// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIngestToken = `-- name: CreateIngestToken :one
INSERT INTO log_ingest_tokens (organization_id, name, service, token_hash, token_prefix, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, service, token_hash, token_prefix, created_by, last_used_at, created_at
`

type CreateIngestTokenParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Service        string     `json:"service"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	CreatedBy      *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateIngestToken(ctx context.Context, arg CreateIngestTokenParams) (LogIngestToken, error) {
	row := q.db.QueryRow(ctx, createIngestToken,
		arg.OrganizationID,
		arg.Name,
		arg.Service,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.CreatedBy,
	)
	var i LogIngestToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Service,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngestToken = `-- name: DeleteIngestToken :execrows
DELETE FROM log_ingest_tokens WHERE id = $1
`

func (q *Queries) DeleteIngestToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngestToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngestToken = `-- name: GetIngestToken :one
SELECT id, organization_id, name, service, token_hash, token_prefix, created_by, last_used_at, created_at FROM log_ingest_tokens WHERE id = $1
`

func (q *Queries) GetIngestToken(ctx context.Context, id uuid.UUID) (LogIngestToken, error) {
	row := q.db.QueryRow(ctx, getIngestToken, id)
	var i LogIngestToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Service,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIngestTokenByHash = `-- name: GetIngestTokenByHash :one
SELECT id, organization_id, name, service, token_hash, token_prefix, created_by, last_used_at, created_at FROM log_ingest_tokens WHERE token_hash = $1
`

func (q *Queries) GetIngestTokenByHash(ctx context.Context, tokenHash []byte) (LogIngestToken, error) {
	row := q.db.QueryRow(ctx, getIngestTokenByHash, tokenHash)
	var i LogIngestToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Service,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertServiceLogs = `-- name: InsertServiceLogs :execrows
INSERT INTO log_entries (organization_id, ts, source, source_id, service, level, message, attributes)
SELECT $1::uuid, unnest($2::timestamptz[]), 'service', $3::uuid, $4::text,
       unnest($5::text[])::log_level, unnest($6::text[]), unnest($7::jsonb[])
`

type InsertServiceLogsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ts             []time.Time `json:"ts"`
	SourceID       uuid.UUID   `json:"source_id"`
	Service        string      `json:"service"`
	Levels         []string    `json:"levels"`
	Messages       []string    `json:"messages"`
	Attributes     [][]byte    `json:"attributes"`
}

// One ingest batch for a token's service. The arrays have one element per line (set-returning
// functions in a select list advance together).
func (q *Queries) InsertServiceLogs(ctx context.Context, arg InsertServiceLogsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertServiceLogs,
		arg.OrganizationID,
		arg.Ts,
		arg.SourceID,
		arg.Service,
		arg.Levels,
		arg.Messages,
		arg.Attributes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listIngestTokens = `-- name: ListIngestTokens :many
SELECT t.id, t.organization_id, t.name, t.service, t.token_hash, t.token_prefix, t.created_by, t.last_used_at, t.created_at, u.display_name AS created_by_name
FROM log_ingest_tokens t LEFT JOIN users u ON u.id = t.created_by
WHERE t.organization_id = $1 ORDER BY t.name
`

type ListIngestTokensRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Service        string     `json:"service"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	CreatedAt      time.Time  `json:"created_at"`
	CreatedByName  *string    `json:"created_by_name"`
}

func (q *Queries) ListIngestTokens(ctx context.Context, organizationID uuid.UUID) ([]ListIngestTokensRow, error) {
	rows, err := q.db.Query(ctx, listIngestTokens, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngestTokensRow{}
	for rows.Next() {
		var i ListIngestTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Service,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintainLogPartitions = `-- name: MaintainLogPartitions :exec
SELECT opshub_maintain_log_partitions($1::integer)
`

func (q *Queries) MaintainLogPartitions(ctx context.Context, keepDays int32) error {
	_, err := q.db.Exec(ctx, maintainLogPartitions, keepDays)
	return err
}

const recentLogServices = `-- name: RecentLogServices :many
SELECT DISTINCT service FROM log_entries
WHERE organization_id = $1 AND ts >= now() - interval '1 day'
  AND (project_id IS NULL OR $2::boolean OR project_id = ANY ($3::uuid[]))
ORDER BY service
LIMIT 200
`

type RecentLogServicesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	SeeAll         bool        `json:"see_all"`
	ProjectIds     []uuid.UUID `json:"project_ids"`
}

// Service names seen in the last day, for the filter.
func (q *Queries) RecentLogServices(ctx context.Context, arg RecentLogServicesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, recentLogServices, arg.OrganizationID, arg.SeeAll, arg.ProjectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var service string
		if err := rows.Scan(&service); err != nil {
			return nil, err
		}
		items = append(items, service)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogs = `-- name: SearchLogs :many
SELECT id, ts, source, source_id, project_id, service, level, message, attributes
FROM log_entries
WHERE organization_id = $1
  AND ts >= $2 AND ts < $3
  AND (project_id IS NULL OR $4::boolean OR project_id = ANY ($5::uuid[]))
  AND ($6::log_source IS NULL OR source = $6)
  AND ($7::text IS NULL OR service = $7)
  AND ($8::log_level IS NULL OR level >= $8)
  AND ($9::text IS NULL OR search @@ websearch_to_tsquery('simple', $9))
  AND ($10::text IS NULL OR message ILIKE '%' || $10 || '%' ESCAPE '\')
  AND ($11::timestamptz IS NULL OR (ts, id) < ($11, $12::uuid))
  AND ($13::timestamptz IS NULL OR (ts, id) > ($13, $14::uuid))
ORDER BY ts DESC, id DESC
LIMIT $15
`

type SearchLogsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	FromTs         time.Time   `json:"from_ts"`
	ToTs           time.Time   `json:"to_ts"`
	SeeAll         bool        `json:"see_all"`
	ProjectIds     []uuid.UUID `json:"project_ids"`
	Source         *LogSource  `json:"source"`
	Service        *string     `json:"service"`
	MinLevel       *LogLevel   `json:"min_level"`
	Fts            *string     `json:"fts"`
	Contains       *string     `json:"contains"`
	BeforeTs       *time.Time  `json:"before_ts"`
	BeforeID       *uuid.UUID  `json:"before_id"`
	AfterTs        *time.Time  `json:"after_ts"`
	AfterID        *uuid.UUID  `json:"after_id"`
	MaxRows        int32       `json:"max_rows"`
}

type SearchLogsRow struct {
	ID         uuid.UUID  `json:"id"`
	Ts         time.Time  `json:"ts"`
	Source     LogSource  `json:"source"`
	SourceID   *uuid.UUID `json:"source_id"`
	ProjectID  *uuid.UUID `json:"project_id"`
	Service    string     `json:"service"`
	Level      LogLevel   `json:"level"`
	Message    string     `json:"message"`
	Attributes []byte     `json:"attributes"`
}

// Newest first within [from_ts, to_ts). Job and deployment lines only for the given projects
// (see_all: every project). fts: a full-text query; contains: a plain substring (for text
// without spaces between words, such as Khmer). before_* pages backwards, after_* fetches
// only newer lines (follow mode).
func (q *Queries) SearchLogs(ctx context.Context, arg SearchLogsParams) ([]SearchLogsRow, error) {
	rows, err := q.db.Query(ctx, searchLogs,
		arg.OrganizationID,
		arg.FromTs,
		arg.ToTs,
		arg.SeeAll,
		arg.ProjectIds,
		arg.Source,
		arg.Service,
		arg.MinLevel,
		arg.Fts,
		arg.Contains,
		arg.BeforeTs,
		arg.BeforeID,
		arg.AfterTs,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchLogsRow{}
	for rows.Next() {
		var i SearchLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.Source,
			&i.SourceID,
			&i.ProjectID,
			&i.Service,
			&i.Level,
			&i.Message,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchIngestToken = `-- name: TouchIngestToken :exec
UPDATE log_ingest_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchIngestToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchIngestToken, id)
	return err
}

const visibleProjectIDs = `-- name: VisibleProjectIDs :many
SELECT p.id FROM projects p
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::boolean
       OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id = p.id AND pm.user_id = $3::uuid)
       OR EXISTS (SELECT 1 FROM project_members pm
                  JOIN team_members tm ON tm.team_id = pm.team_id AND tm.user_id = $3::uuid
                  JOIN teams t ON t.id = pm.team_id AND t.deleted_at IS NULL
                  WHERE pm.project_id = p.id))
`

type VisibleProjectIDsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	SeeAll         bool      `json:"see_all"`
	UserID         uuid.UUID `json:"user_id"`
}

// The projects a member can see (all of them when see_all).
func (q *Queries) VisibleProjectIDs(ctx context.Context, arg VisibleProjectIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, visibleProjectIDs, arg.OrganizationID, arg.SeeAll, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
