// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type EmailTokenPurpose string

const (
	EmailTokenPurposeVerifyEmail   EmailTokenPurpose = "verify_email"
	EmailTokenPurposeResetPassword EmailTokenPurpose = "reset_password"
)

func (e *EmailTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailTokenPurpose(s)
	case string:
		*e = EmailTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailTokenPurpose: %T", src)
	}
	return nil
}

type NullEmailTokenPurpose struct {
	EmailTokenPurpose EmailTokenPurpose `json:"email_token_purpose"`
	Valid             bool              `json:"valid"` // Valid is true if EmailTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.EmailTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailTokenPurpose), nil
}

type EnvironmentKind string

const (
	EnvironmentKindDevelopment EnvironmentKind = "development"
	EnvironmentKindStaging     EnvironmentKind = "staging"
	EnvironmentKindProduction  EnvironmentKind = "production"
)

func (e *EnvironmentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnvironmentKind(s)
	case string:
		*e = EnvironmentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EnvironmentKind: %T", src)
	}
	return nil
}

type NullEnvironmentKind struct {
	EnvironmentKind EnvironmentKind `json:"environment_kind"`
	Valid           bool            `json:"valid"` // Valid is true if EnvironmentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironmentKind) Scan(value interface{}) error {
	if value == nil {
		ns.EnvironmentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnvironmentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironmentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnvironmentKind), nil
}

type GitProvider string

const (
	GitProviderGithub GitProvider = "github"
	GitProviderGitlab GitProvider = "gitlab"
)

func (e *GitProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GitProvider(s)
	case string:
		*e = GitProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for GitProvider: %T", src)
	}
	return nil
}

type NullGitProvider struct {
	GitProvider GitProvider `json:"git_provider"`
	Valid       bool        `json:"valid"` // Valid is true if GitProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGitProvider) Scan(value interface{}) error {
	if value == nil {
		ns.GitProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GitProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGitProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GitProvider), nil
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleDeveloper MemberRole = "developer"
	MemberRoleViewer    MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type WebhookMode string

const (
	WebhookModeAutomatic WebhookMode = "automatic"
	WebhookModeManual    WebhookMode = "manual"
)

func (e *WebhookMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookMode(s)
	case string:
		*e = WebhookMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookMode: %T", src)
	}
	return nil
}

type NullWebhookMode struct {
	WebhookMode WebhookMode `json:"webhook_mode"`
	Valid       bool        `json:"valid"` // Valid is true if WebhookMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookMode) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookMode), nil
}

type ApiToken struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	TokenPrefix string     `json:"token_prefix"`
	TokenHash   []byte     `json:"token_hash"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type AuditLog struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID *uuid.UUID  `json:"organization_id"`
	ActorUserID    *uuid.UUID  `json:"actor_user_id"`
	ActorType      string      `json:"actor_type"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     *string     `json:"resource_id"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
	Before         []byte      `json:"before"`
	After          []byte      `json:"after"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type EmailToken struct {
	ID        uuid.UUID         `json:"id"`
	UserID    uuid.UUID         `json:"user_id"`
	Purpose   EmailTokenPurpose `json:"purpose"`
	TokenHash []byte            `json:"token_hash"`
	ExpiresAt time.Time         `json:"expires_at"`
	UsedAt    *time.Time        `json:"used_at"`
	CreatedAt time.Time         `json:"created_at"`
}

type Environment struct {
	ID        uuid.UUID       `json:"id"`
	ProjectID uuid.UUID       `json:"project_id"`
	Name      string          `json:"name"`
	Kind      EnvironmentKind `json:"kind"`
	Variables []byte          `json:"variables"`
	Version   int32           `json:"version"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
	DeletedAt *time.Time      `json:"deleted_at"`
}

type IdempotencyKey struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type Invitation struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Email          string     `json:"email"`
	Role           MemberRole `json:"role"`
	TokenHash      []byte     `json:"token_hash"`
	InvitedBy      *uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
	AcceptedAt     *time.Time `json:"accepted_at"`
	AcceptedBy     *uuid.UUID `json:"accepted_by"`
	RevokedAt      *time.Time `json:"revoked_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type MfaChallenge struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	TokenHash  []byte     `json:"token_hash"`
	AuthMethod string     `json:"auth_method"`
	Attempts   int32      `json:"attempts"`
	ExpiresAt  time.Time  `json:"expires_at"`
	UsedAt     *time.Time `json:"used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Name      string     `json:"name"`
	Settings  []byte     `json:"settings"`
	Version   int32      `json:"version"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Role           MemberRole `json:"role"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Project struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	DefaultBranch  string     `json:"default_branch"`
	Version        int32      `json:"version"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type ProjectMember struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	UserID    *uuid.UUID `json:"user_id"`
	TeamID    *uuid.UUID `json:"team_id"`
	Role      MemberRole `json:"role"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type ProtectionRule struct {
	EnvironmentID     uuid.UUID    `json:"environment_id"`
	RequiredApprovals int32        `json:"required_approvals"`
	AllowedBranches   []string     `json:"allowed_branches"`
	AllowedRoles      []MemberRole `json:"allowed_roles"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	SessionID uuid.UUID  `json:"session_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Repository struct {
	ID               uuid.UUID   `json:"id"`
	ProjectID        uuid.UUID   `json:"project_id"`
	Provider         GitProvider `json:"provider"`
	BaseUrl          *string     `json:"base_url"`
	FullName         string      `json:"full_name"`
	ExternalID       string      `json:"external_id"`
	WebUrl           string      `json:"web_url"`
	CloneUrl         string      `json:"clone_url"`
	DefaultBranch    string      `json:"default_branch"`
	AccessTokenEnc   []byte      `json:"access_token_enc"`
	WebhookSecretEnc []byte      `json:"webhook_secret_enc"`
	WebhookMode      WebhookMode `json:"webhook_mode"`
	WebhookID        *string     `json:"webhook_id"`
	ConnectedBy      *uuid.UUID  `json:"connected_by"`
	LastDeliveryAt   *time.Time  `json:"last_delivery_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	AuthMethod   string      `json:"auth_method"`
	Ip           *netip.Addr `json:"ip"`
	UserAgent    *string     `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	RevokedAt    *time.Time  `json:"revoked_at"`
	RevokeReason *string     `json:"revoke_reason"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Team struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
	Description    string     `json:"description"`
	Version        int32      `json:"version"`
}

type TeamMember struct {
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	Email             string     `json:"email"`
	DisplayName       string     `json:"display_name"`
	PasswordHash      *string    `json:"password_hash"`
	EmailVerifiedAt   *time.Time `json:"email_verified_at"`
	Locale            string     `json:"locale"`
	Timezone          string     `json:"timezone"`
	KhmerNumerals     bool       `json:"khmer_numerals"`
	TotpSecretEnc     []byte     `json:"totp_secret_enc"`
	TotpPendingEnc    []byte     `json:"totp_pending_enc"`
	TotpEnabledAt     *time.Time `json:"totp_enabled_at"`
	TotpLastStep      *int64     `json:"totp_last_step"`
	FailedLoginCount  int32      `json:"failed_login_count"`
	LockoutLevel      int32      `json:"lockout_level"`
	LockedUntil       *time.Time `json:"locked_until"`
	PasswordChangedAt *time.Time `json:"password_changed_at"`
	IsPlatformAdmin   bool       `json:"is_platform_admin"`
	DisabledAt        *time.Time `json:"disabled_at"`
	LastLoginAt       *time.Time `json:"last_login_at"`
	Version           int32      `json:"version"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

type UserIdentity struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CodeHash  []byte     `json:"code_hash"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID `json:"id"`
	RepositoryID   uuid.UUID `json:"repository_id"`
	DeliveryID     string    `json:"delivery_id"`
	Event          string    `json:"event"`
	Ref            string    `json:"ref"`
	CommitSha      string    `json:"commit_sha"`
	SignatureValid bool      `json:"signature_valid"`
	Payload        []byte    `json:"payload"`
	ReceivedAt     time.Time `json:"received_at"`
}
