// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AlertRuleKind string

const (
	AlertRuleKindMonitorDown    AlertRuleKind = "monitor_down"
	AlertRuleKindMonitorLatency AlertRuleKind = "monitor_latency"
	AlertRuleKindAssetMetric    AlertRuleKind = "asset_metric"
	AlertRuleKindAssetOffline   AlertRuleKind = "asset_offline"
	AlertRuleKindCertificate    AlertRuleKind = "certificate"
)

func (e *AlertRuleKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertRuleKind(s)
	case string:
		*e = AlertRuleKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertRuleKind: %T", src)
	}
	return nil
}

type NullAlertRuleKind struct {
	AlertRuleKind AlertRuleKind `json:"alert_rule_kind"`
	Valid         bool          `json:"valid"` // Valid is true if AlertRuleKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertRuleKind) Scan(value interface{}) error {
	if value == nil {
		ns.AlertRuleKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertRuleKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertRuleKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertRuleKind), nil
}

type AlertSeverity string

const (
	AlertSeverityInfo     AlertSeverity = "info"
	AlertSeverityWarning  AlertSeverity = "warning"
	AlertSeverityCritical AlertSeverity = "critical"
)

func (e *AlertSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSeverity(s)
	case string:
		*e = AlertSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSeverity: %T", src)
	}
	return nil
}

type NullAlertSeverity struct {
	AlertSeverity AlertSeverity `json:"alert_severity"`
	Valid         bool          `json:"valid"` // Valid is true if AlertSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSeverity), nil
}

type AlertStatus string

const (
	AlertStatusPending  AlertStatus = "pending"
	AlertStatusFiring   AlertStatus = "firing"
	AlertStatusResolved AlertStatus = "resolved"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus `json:"alert_status"`
	Valid       bool        `json:"valid"` // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type ApprovalDecision string

const (
	ApprovalDecisionApproved ApprovalDecision = "approved"
	ApprovalDecisionRejected ApprovalDecision = "rejected"
)

func (e *ApprovalDecision) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalDecision(s)
	case string:
		*e = ApprovalDecision(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalDecision: %T", src)
	}
	return nil
}

type NullApprovalDecision struct {
	ApprovalDecision ApprovalDecision `json:"approval_decision"`
	Valid            bool             `json:"valid"` // Valid is true if ApprovalDecision is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalDecision) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalDecision, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalDecision.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalDecision) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalDecision), nil
}

type AssetKind string

const (
	AssetKindServer   AssetKind = "server"
	AssetKindCluster  AssetKind = "cluster"
	AssetKindDatabase AssetKind = "database"
	AssetKindDomain   AssetKind = "domain"
)

func (e *AssetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetKind(s)
	case string:
		*e = AssetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetKind: %T", src)
	}
	return nil
}

type NullAssetKind struct {
	AssetKind AssetKind `json:"asset_kind"`
	Valid     bool      `json:"valid"` // Valid is true if AssetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetKind) Scan(value interface{}) error {
	if value == nil {
		ns.AssetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetKind), nil
}

type ChannelKind string

const (
	ChannelKindTelegram ChannelKind = "telegram"
	ChannelKindSlack    ChannelKind = "slack"
	ChannelKindEmail    ChannelKind = "email"
	ChannelKindWebhook  ChannelKind = "webhook"
)

func (e *ChannelKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelKind(s)
	case string:
		*e = ChannelKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelKind: %T", src)
	}
	return nil
}

type NullChannelKind struct {
	ChannelKind ChannelKind `json:"channel_kind"`
	Valid       bool        `json:"valid"` // Valid is true if ChannelKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelKind) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelKind), nil
}

type DeployStrategy string

const (
	DeployStrategyRolling   DeployStrategy = "rolling"
	DeployStrategyBlueGreen DeployStrategy = "blue_green"
)

func (e *DeployStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeployStrategy(s)
	case string:
		*e = DeployStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for DeployStrategy: %T", src)
	}
	return nil
}

type NullDeployStrategy struct {
	DeployStrategy DeployStrategy `json:"deploy_strategy"`
	Valid          bool           `json:"valid"` // Valid is true if DeployStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeployStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.DeployStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeployStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeployStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeployStrategy), nil
}

type DeployTargetKind string

const (
	DeployTargetKindSsh        DeployTargetKind = "ssh"
	DeployTargetKindDocker     DeployTargetKind = "docker"
	DeployTargetKindKubernetes DeployTargetKind = "kubernetes"
)

func (e *DeployTargetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeployTargetKind(s)
	case string:
		*e = DeployTargetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DeployTargetKind: %T", src)
	}
	return nil
}

type NullDeployTargetKind struct {
	DeployTargetKind DeployTargetKind `json:"deploy_target_kind"`
	Valid            bool             `json:"valid"` // Valid is true if DeployTargetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeployTargetKind) Scan(value interface{}) error {
	if value == nil {
		ns.DeployTargetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeployTargetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeployTargetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeployTargetKind), nil
}

type DeploymentStatus string

const (
	DeploymentStatusPending   DeploymentStatus = "pending"
	DeploymentStatusRunning   DeploymentStatus = "running"
	DeploymentStatusSucceeded DeploymentStatus = "succeeded"
	DeploymentStatusFailed    DeploymentStatus = "failed"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type EmailTokenPurpose string

const (
	EmailTokenPurposeVerifyEmail   EmailTokenPurpose = "verify_email"
	EmailTokenPurposeResetPassword EmailTokenPurpose = "reset_password"
)

func (e *EmailTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailTokenPurpose(s)
	case string:
		*e = EmailTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailTokenPurpose: %T", src)
	}
	return nil
}

type NullEmailTokenPurpose struct {
	EmailTokenPurpose EmailTokenPurpose `json:"email_token_purpose"`
	Valid             bool              `json:"valid"` // Valid is true if EmailTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.EmailTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailTokenPurpose), nil
}

type EnvironmentKind string

const (
	EnvironmentKindDevelopment EnvironmentKind = "development"
	EnvironmentKindStaging     EnvironmentKind = "staging"
	EnvironmentKindProduction  EnvironmentKind = "production"
)

func (e *EnvironmentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnvironmentKind(s)
	case string:
		*e = EnvironmentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EnvironmentKind: %T", src)
	}
	return nil
}

type NullEnvironmentKind struct {
	EnvironmentKind EnvironmentKind `json:"environment_kind"`
	Valid           bool            `json:"valid"` // Valid is true if EnvironmentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironmentKind) Scan(value interface{}) error {
	if value == nil {
		ns.EnvironmentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnvironmentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironmentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnvironmentKind), nil
}

type GitProvider string

const (
	GitProviderGithub GitProvider = "github"
	GitProviderGitlab GitProvider = "gitlab"
)

func (e *GitProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GitProvider(s)
	case string:
		*e = GitProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for GitProvider: %T", src)
	}
	return nil
}

type NullGitProvider struct {
	GitProvider GitProvider `json:"git_provider"`
	Valid       bool        `json:"valid"` // Valid is true if GitProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGitProvider) Scan(value interface{}) error {
	if value == nil {
		ns.GitProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GitProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGitProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GitProvider), nil
}

type JobStatus string

const (
	JobStatusCreated         JobStatus = "created"
	JobStatusWaitingApproval JobStatus = "waiting_approval"
	JobStatusQueued          JobStatus = "queued"
	JobStatusRunning         JobStatus = "running"
	JobStatusSucceeded       JobStatus = "succeeded"
	JobStatusFailed          JobStatus = "failed"
	JobStatusCanceled        JobStatus = "canceled"
	JobStatusSkipped         JobStatus = "skipped"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type LogLevel string

const (
	LogLevelDebug LogLevel = "debug"
	LogLevelInfo  LogLevel = "info"
	LogLevelWarn  LogLevel = "warn"
	LogLevelError LogLevel = "error"
)

func (e *LogLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogLevel(s)
	case string:
		*e = LogLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for LogLevel: %T", src)
	}
	return nil
}

type NullLogLevel struct {
	LogLevel LogLevel `json:"log_level"`
	Valid    bool     `json:"valid"` // Valid is true if LogLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogLevel) Scan(value interface{}) error {
	if value == nil {
		ns.LogLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogLevel), nil
}

type LogSource string

const (
	LogSourceService    LogSource = "service"
	LogSourceJob        LogSource = "job"
	LogSourceDeployment LogSource = "deployment"
)

func (e *LogSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogSource(s)
	case string:
		*e = LogSource(s)
	default:
		return fmt.Errorf("unsupported scan type for LogSource: %T", src)
	}
	return nil
}

type NullLogSource struct {
	LogSource LogSource `json:"log_source"`
	Valid     bool      `json:"valid"` // Valid is true if LogSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogSource) Scan(value interface{}) error {
	if value == nil {
		ns.LogSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogSource), nil
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleDeveloper MemberRole = "developer"
	MemberRoleViewer    MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MonitorKind string

const (
	MonitorKindHttp MonitorKind = "http"
	MonitorKindTcp  MonitorKind = "tcp"
	MonitorKindSsl  MonitorKind = "ssl"
)

func (e *MonitorKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorKind(s)
	case string:
		*e = MonitorKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorKind: %T", src)
	}
	return nil
}

type NullMonitorKind struct {
	MonitorKind MonitorKind `json:"monitor_kind"`
	Valid       bool        `json:"valid"` // Valid is true if MonitorKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorKind) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorKind), nil
}

type RunStatus string

const (
	RunStatusQueued    RunStatus = "queued"
	RunStatusRunning   RunStatus = "running"
	RunStatusWaiting   RunStatus = "waiting"
	RunStatusSucceeded RunStatus = "succeeded"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCanceled  RunStatus = "canceled"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type RunTrigger string

const (
	RunTriggerPush        RunTrigger = "push"
	RunTriggerPullRequest RunTrigger = "pull_request"
	RunTriggerTag         RunTrigger = "tag"
	RunTriggerManual      RunTrigger = "manual"
	RunTriggerSchedule    RunTrigger = "schedule"
)

func (e *RunTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunTrigger(s)
	case string:
		*e = RunTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for RunTrigger: %T", src)
	}
	return nil
}

type NullRunTrigger struct {
	RunTrigger RunTrigger `json:"run_trigger"`
	Valid      bool       `json:"valid"` // Valid is true if RunTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.RunTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunTrigger), nil
}

type StepStatus string

const (
	StepStatusPending   StepStatus = "pending"
	StepStatusRunning   StepStatus = "running"
	StepStatusSucceeded StepStatus = "succeeded"
	StepStatusFailed    StepStatus = "failed"
	StepStatusSkipped   StepStatus = "skipped"
	StepStatusCanceled  StepStatus = "canceled"
)

func (e *StepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StepStatus(s)
	case string:
		*e = StepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StepStatus: %T", src)
	}
	return nil
}

type NullStepStatus struct {
	StepStatus StepStatus `json:"step_status"`
	Valid      bool       `json:"valid"` // Valid is true if StepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StepStatus), nil
}

type WebhookMode string

const (
	WebhookModeAutomatic WebhookMode = "automatic"
	WebhookModeManual    WebhookMode = "manual"
)

func (e *WebhookMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookMode(s)
	case string:
		*e = WebhookMode(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookMode: %T", src)
	}
	return nil
}

type NullWebhookMode struct {
	WebhookMode WebhookMode `json:"webhook_mode"`
	Valid       bool        `json:"valid"` // Valid is true if WebhookMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookMode) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookMode), nil
}

type Alert struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	RuleID         *uuid.UUID    `json:"rule_id"`
	RuleName       string        `json:"rule_name"`
	RuleKind       AlertRuleKind `json:"rule_kind"`
	Severity       AlertSeverity `json:"severity"`
	SubjectType    string        `json:"subject_type"`
	SubjectID      uuid.UUID     `json:"subject_id"`
	SubjectName    string        `json:"subject_name"`
	SubjectLabels  []string      `json:"subject_labels"`
	Status         AlertStatus   `json:"status"`
	Details        []byte        `json:"details"`
	PendingSince   time.Time     `json:"pending_since"`
	StartedAt      *time.Time    `json:"started_at"`
	ResolvedAt     *time.Time    `json:"resolved_at"`
	AcknowledgedBy *uuid.UUID    `json:"acknowledged_by"`
	AcknowledgedAt *time.Time    `json:"acknowledged_at"`
	NextStep       int32         `json:"next_step"`
	NextStepAt     *time.Time    `json:"next_step_at"`
}

type AlertEvent struct {
	ID          int64      `json:"id"`
	AlertID     uuid.UUID  `json:"alert_id"`
	At          time.Time  `json:"at"`
	Kind        string     `json:"kind"`
	ChannelID   *uuid.UUID `json:"channel_id"`
	ChannelName string     `json:"channel_name"`
	UserID      *uuid.UUID `json:"user_id"`
	Detail      string     `json:"detail"`
}

type AlertRule struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	Name           string        `json:"name"`
	Kind           AlertRuleKind `json:"kind"`
	TargetID       *uuid.UUID    `json:"target_id"`
	Label          *string       `json:"label"`
	Threshold      *float64      `json:"threshold"`
	Metric         *string       `json:"metric"`
	ForSeconds     int32         `json:"for_seconds"`
	Severity       AlertSeverity `json:"severity"`
	Escalation     []byte        `json:"escalation"`
	Enabled        bool          `json:"enabled"`
	CreatedBy      *uuid.UUID    `json:"created_by"`
	Version        int32         `json:"version"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

type ApiToken struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	TokenPrefix string     `json:"token_prefix"`
	TokenHash   []byte     `json:"token_hash"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Artifact struct {
	ID             uuid.UUID `json:"id"`
	JobID          uuid.UUID `json:"job_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	SizeBytes      int64     `json:"size_bytes"`
	Sha256         []byte    `json:"sha256"`
	StorageKey     string    `json:"storage_key"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type AssetMetric struct {
	AssetID uuid.UUID `json:"asset_id"`
	Ts      time.Time `json:"ts"`
	CpuPct  *float32  `json:"cpu_pct"`
	MemPct  *float32  `json:"mem_pct"`
	DiskPct *float32  `json:"disk_pct"`
	Load1   *float32  `json:"load1"`
}

type AssetMetricsHourly struct {
	AssetID uuid.UUID `json:"asset_id"`
	Hour    time.Time `json:"hour"`
	CpuAvg  *float32  `json:"cpu_avg"`
	CpuMax  *float32  `json:"cpu_max"`
	MemAvg  *float32  `json:"mem_avg"`
	MemMax  *float32  `json:"mem_max"`
	DiskAvg *float32  `json:"disk_avg"`
	DiskMax *float32  `json:"disk_max"`
	Samples int32     `json:"samples"`
}

type AuditLog struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID *uuid.UUID  `json:"organization_id"`
	ActorUserID    *uuid.UUID  `json:"actor_user_id"`
	ActorType      string      `json:"actor_type"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     *string     `json:"resource_id"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
	Before         []byte      `json:"before"`
	After          []byte      `json:"after"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type CacheEntry struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	Key        string    `json:"key"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	Sha256     []byte    `json:"sha256"`
	LastUsedAt time.Time `json:"last_used_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type DeployTarget struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	Name           string           `json:"name"`
	Kind           DeployTargetKind `json:"kind"`
	Description    string           `json:"description"`
	Config         []byte           `json:"config"`
	CredentialsEnc []byte           `json:"credentials_enc"`
	LastTestAt     *time.Time       `json:"last_test_at"`
	LastTestOk     *bool            `json:"last_test_ok"`
	CreatedBy      *uuid.UUID       `json:"created_by"`
	Version        int32            `json:"version"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type Deployment struct {
	ID              uuid.UUID        `json:"id"`
	OrganizationID  uuid.UUID        `json:"organization_id"`
	ProjectID       uuid.UUID        `json:"project_id"`
	EnvironmentID   uuid.UUID        `json:"environment_id"`
	Number          int32            `json:"number"`
	TargetID        *uuid.UUID       `json:"target_id"`
	TargetName      string           `json:"target_name"`
	TargetKind      DeployTargetKind `json:"target_kind"`
	Version         string           `json:"version"`
	PreviousVersion string           `json:"previous_version"`
	Strategy        DeployStrategy   `json:"strategy"`
	Status          DeploymentStatus `json:"status"`
	FailureReason   *string          `json:"failure_reason"`
	Reverted        bool             `json:"reverted"`
	Health          []byte           `json:"health"`
	RunID           *uuid.UUID       `json:"run_id"`
	JobID           *uuid.UUID       `json:"job_id"`
	RollbackOfID    *uuid.UUID       `json:"rollback_of_id"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	LogBytes        int64            `json:"log_bytes"`
	StartedAt       *time.Time       `json:"started_at"`
	FinishedAt      *time.Time       `json:"finished_at"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type DeploymentLogChunk struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	Seq          int32     `json:"seq"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"created_at"`
}

type EmailToken struct {
	ID        uuid.UUID         `json:"id"`
	UserID    uuid.UUID         `json:"user_id"`
	Purpose   EmailTokenPurpose `json:"purpose"`
	TokenHash []byte            `json:"token_hash"`
	ExpiresAt time.Time         `json:"expires_at"`
	UsedAt    *time.Time        `json:"used_at"`
	CreatedAt time.Time         `json:"created_at"`
}

type Environment struct {
	ID                  uuid.UUID       `json:"id"`
	ProjectID           uuid.UUID       `json:"project_id"`
	Name                string          `json:"name"`
	Kind                EnvironmentKind `json:"kind"`
	Variables           []byte          `json:"variables"`
	Version             int32           `json:"version"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
	DeletedAt           *time.Time      `json:"deleted_at"`
	CurrentDeploymentID *uuid.UUID      `json:"current_deployment_id"`
}

type IdempotencyKey struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Key            string    `json:"key"`
	RequestHash    []byte    `json:"request_hash"`
	ResponseStatus *int32    `json:"response_status"`
	ResponseBody   []byte    `json:"response_body"`
	CreatedAt      time.Time `json:"created_at"`
	ExpiresAt      time.Time `json:"expires_at"`
}

type InfraAsset struct {
	ID               uuid.UUID  `json:"id"`
	OrganizationID   uuid.UUID  `json:"organization_id"`
	Kind             AssetKind  `json:"kind"`
	Name             string     `json:"name"`
	Address          string     `json:"address"`
	Description      string     `json:"description"`
	Tags             []string   `json:"tags"`
	Metadata         []byte     `json:"metadata"`
	TlsPort          int32      `json:"tls_port"`
	AgentTokenHash   []byte     `json:"agent_token_hash"`
	AgentTokenPrefix string     `json:"agent_token_prefix"`
	AgentVersion     string     `json:"agent_version"`
	AgentHostname    string     `json:"agent_hostname"`
	AgentOs          string     `json:"agent_os"`
	AgentArch        string     `json:"agent_arch"`
	LastHeartbeatAt  *time.Time `json:"last_heartbeat_at"`
	LastMetrics      []byte     `json:"last_metrics"`
	CreatedBy        *uuid.UUID `json:"created_by"`
	Version          int32      `json:"version"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Invitation struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Email          string     `json:"email"`
	Role           MemberRole `json:"role"`
	TokenHash      []byte     `json:"token_hash"`
	InvitedBy      *uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
	AcceptedAt     *time.Time `json:"accepted_at"`
	AcceptedBy     *uuid.UUID `json:"accepted_by"`
	RevokedAt      *time.Time `json:"revoked_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type JobApproval struct {
	ID        uuid.UUID        `json:"id"`
	JobID     uuid.UUID        `json:"job_id"`
	UserID    uuid.UUID        `json:"user_id"`
	Decision  ApprovalDecision `json:"decision"`
	Comment   string           `json:"comment"`
	CreatedAt time.Time        `json:"created_at"`
}

type JobLogChunk struct {
	JobID     uuid.UUID `json:"job_id"`
	Seq       int32     `json:"seq"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type JobStep struct {
	JobID      uuid.UUID  `json:"job_id"`
	Index      int32      `json:"index"`
	Name       string     `json:"name"`
	Command    string     `json:"command"`
	Status     StepStatus `json:"status"`
	ExitCode   *int32     `json:"exit_code"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
}

type JobToken struct {
	JobID     uuid.UUID `json:"job_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	MasksEnc  []byte    `json:"masks_enc"`
}

type LogEntry struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Ts             time.Time   `json:"ts"`
	Source         LogSource   `json:"source"`
	SourceID       *uuid.UUID  `json:"source_id"`
	ProjectID      *uuid.UUID  `json:"project_id"`
	Service        string      `json:"service"`
	Level          LogLevel    `json:"level"`
	Message        string      `json:"message"`
	Attributes     []byte      `json:"attributes"`
	Search         interface{} `json:"search"`
}

type LogIngestToken struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Service        string     `json:"service"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	LastUsedAt     *time.Time `json:"last_used_at"`
	CreatedAt      time.Time  `json:"created_at"`
}

type MfaChallenge struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	TokenHash  []byte     `json:"token_hash"`
	AuthMethod string     `json:"auth_method"`
	Attempts   int32      `json:"attempts"`
	ExpiresAt  time.Time  `json:"expires_at"`
	UsedAt     *time.Time `json:"used_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type Monitor struct {
	ID              uuid.UUID   `json:"id"`
	OrganizationID  uuid.UUID   `json:"organization_id"`
	Name            string      `json:"name"`
	Kind            MonitorKind `json:"kind"`
	Target          string      `json:"target"`
	IntervalSeconds int32       `json:"interval_seconds"`
	TimeoutMs       int32       `json:"timeout_ms"`
	Config          []byte      `json:"config"`
	Labels          []string    `json:"labels"`
	Enabled         bool        `json:"enabled"`
	LastUp          *bool       `json:"last_up"`
	LastCheckedAt   *time.Time  `json:"last_checked_at"`
	LastLatencyMs   *int32      `json:"last_latency_ms"`
	LastError       string      `json:"last_error"`
	DownSince       *time.Time  `json:"down_since"`
	NextCheckAt     time.Time   `json:"next_check_at"`
	CreatedBy       *uuid.UUID  `json:"created_by"`
	Version         int32       `json:"version"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type MonitorResult struct {
	MonitorID  uuid.UUID `json:"monitor_id"`
	Ts         time.Time `json:"ts"`
	Up         bool      `json:"up"`
	LatencyMs  *int32    `json:"latency_ms"`
	StatusCode *int32    `json:"status_code"`
	Error      string    `json:"error"`
}

type MonitorResultsHourly struct {
	MonitorID  uuid.UUID `json:"monitor_id"`
	Hour       time.Time `json:"hour"`
	Checks     int32     `json:"checks"`
	UpChecks   int32     `json:"up_checks"`
	LatencyAvg *float32  `json:"latency_avg"`
	LatencyMax *int32    `json:"latency_max"`
}

type NotificationChannel struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Kind           ChannelKind `json:"kind"`
	Config         []byte      `json:"config"`
	SecretsEnc     []byte      `json:"secrets_enc"`
	Locale         *string     `json:"locale"`
	LastTestAt     *time.Time  `json:"last_test_at"`
	LastTestOk     *bool       `json:"last_test_ok"`
	CreatedBy      *uuid.UUID  `json:"created_by"`
	Version        int32       `json:"version"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Name      string     `json:"name"`
	Settings  []byte     `json:"settings"`
	Version   int32      `json:"version"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Role           MemberRole `json:"role"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type PipelineJob struct {
	ID             uuid.UUID  `json:"id"`
	RunID          uuid.UUID  `json:"run_id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Stage          string     `json:"stage"`
	StageIndex     int32      `json:"stage_index"`
	Needs          []string   `json:"needs"`
	Condition      string     `json:"condition"`
	Environment    *string    `json:"environment"`
	EnvironmentID  *uuid.UUID `json:"environment_id"`
	RunsOn         []string   `json:"runs_on"`
	Spec           []byte     `json:"spec"`
	Status         JobStatus  `json:"status"`
	Attempt        int32      `json:"attempt"`
	RunnerID       *uuid.UUID `json:"runner_id"`
	TimeoutSeconds int32      `json:"timeout_seconds"`
	ExitCode       *int32     `json:"exit_code"`
	FailureReason  *string    `json:"failure_reason"`
	LogBytes       int64      `json:"log_bytes"`
	QueuedAt       *time.Time `json:"queued_at"`
	StartedAt      *time.Time `json:"started_at"`
	FinishedAt     *time.Time `json:"finished_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type PipelineRun struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	Number         int32      `json:"number"`
	Status         RunStatus  `json:"status"`
	Trigger        RunTrigger `json:"trigger"`
	Ref            string     `json:"ref"`
	CommitSha      string     `json:"commit_sha"`
	Title          string     `json:"title"`
	ActorName      string     `json:"actor_name"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	RerunOf        *uuid.UUID `json:"rerun_of"`
	Definition     []byte     `json:"definition"`
	Problems       []byte     `json:"problems"`
	Variables      []byte     `json:"variables"`
	StartedAt      *time.Time `json:"started_at"`
	FinishedAt     *time.Time `json:"finished_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	CommittedAt    *time.Time `json:"committed_at"`
}

type PipelineSchedule struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	Cron      string     `json:"cron"`
	NextRunAt time.Time  `json:"next_run_at"`
	LastRunAt *time.Time `json:"last_run_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Project struct {
	ID                   uuid.UUID  `json:"id"`
	OrganizationID       uuid.UUID  `json:"organization_id"`
	Slug                 string     `json:"slug"`
	Name                 string     `json:"name"`
	Description          string     `json:"description"`
	DefaultBranch        string     `json:"default_branch"`
	Version              int32      `json:"version"`
	CreatedBy            *uuid.UUID `json:"created_by"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	DeletedAt            *time.Time `json:"deleted_at"`
	LastRunNumber        int32      `json:"last_run_number"`
	LastDeploymentNumber int32      `json:"last_deployment_number"`
}

type ProjectMember struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	UserID    *uuid.UUID `json:"user_id"`
	TeamID    *uuid.UUID `json:"team_id"`
	Role      MemberRole `json:"role"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type ProtectionRule struct {
	EnvironmentID     uuid.UUID    `json:"environment_id"`
	RequiredApprovals int32        `json:"required_approvals"`
	AllowedBranches   []string     `json:"allowed_branches"`
	AllowedRoles      []MemberRole `json:"allowed_roles"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	SessionID uuid.UUID  `json:"session_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Repository struct {
	ID               uuid.UUID   `json:"id"`
	ProjectID        uuid.UUID   `json:"project_id"`
	Provider         GitProvider `json:"provider"`
	BaseUrl          *string     `json:"base_url"`
	FullName         string      `json:"full_name"`
	ExternalID       string      `json:"external_id"`
	WebUrl           string      `json:"web_url"`
	CloneUrl         string      `json:"clone_url"`
	DefaultBranch    string      `json:"default_branch"`
	AccessTokenEnc   []byte      `json:"access_token_enc"`
	WebhookSecretEnc []byte      `json:"webhook_secret_enc"`
	WebhookMode      WebhookMode `json:"webhook_mode"`
	WebhookID        *string     `json:"webhook_id"`
	ConnectedBy      *uuid.UUID  `json:"connected_by"`
	LastDeliveryAt   *time.Time  `json:"last_delivery_at"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type Runner struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Labels         []string   `json:"labels"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	Version        string     `json:"version"`
	Os             string     `json:"os"`
	Arch           string     `json:"arch"`
	MaxConcurrency int32      `json:"max_concurrency"`
	LastSeenAt     *time.Time `json:"last_seen_at"`
	DisabledAt     *time.Time `json:"disabled_at"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	RowVersion     int32      `json:"row_version"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type RunnerRegistrationToken struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	TokenHash      []byte     `json:"token_hash"`
	Labels         []string   `json:"labels"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
	UsedAt         *time.Time `json:"used_at"`
	RunnerID       *uuid.UUID `json:"runner_id"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Secret struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	EnvironmentID  *uuid.UUID `json:"environment_id"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	CurrentVersion int32      `json:"current_version"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	Version        int32      `json:"version"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type SecretVersion struct {
	SecretID    uuid.UUID  `json:"secret_id"`
	Version     int32      `json:"version"`
	Ciphertext  []byte     `json:"ciphertext"`
	Nonce       []byte     `json:"nonce"`
	DekEnc      []byte     `json:"dek_enc"`
	KekID       *string    `json:"kek_id"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	CreatedAt   time.Time  `json:"created_at"`
	DestroyedAt *time.Time `json:"destroyed_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	AuthMethod   string      `json:"auth_method"`
	Ip           *netip.Addr `json:"ip"`
	UserAgent    *string     `json:"user_agent"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastUsedAt   time.Time   `json:"last_used_at"`
	RevokedAt    *time.Time  `json:"revoked_at"`
	RevokeReason *string     `json:"revoke_reason"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Silence struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	RuleID         *uuid.UUID     `json:"rule_id"`
	SubjectID      *uuid.UUID     `json:"subject_id"`
	Label          *string        `json:"label"`
	Severity       *AlertSeverity `json:"severity"`
	Comment        string         `json:"comment"`
	StartsAt       time.Time      `json:"starts_at"`
	EndsAt         time.Time      `json:"ends_at"`
	CreatedBy      *uuid.UUID     `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
}

type SslCertificate struct {
	AssetID       uuid.UUID  `json:"asset_id"`
	Host          string     `json:"host"`
	Port          int32      `json:"port"`
	Subject       string     `json:"subject"`
	Issuer        string     `json:"issuer"`
	DnsNames      []string   `json:"dns_names"`
	Serial        string     `json:"serial"`
	Fingerprint   string     `json:"fingerprint"`
	NotBefore     *time.Time `json:"not_before"`
	NotAfter      *time.Time `json:"not_after"`
	Error         string     `json:"error"`
	LastCheckedAt time.Time  `json:"last_checked_at"`
	NextCheckAt   time.Time  `json:"next_check_at"`
}

type Team struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
	Description    string     `json:"description"`
	Version        int32      `json:"version"`
}

type TeamMember struct {
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	Email             string     `json:"email"`
	DisplayName       string     `json:"display_name"`
	PasswordHash      *string    `json:"password_hash"`
	EmailVerifiedAt   *time.Time `json:"email_verified_at"`
	Locale            string     `json:"locale"`
	Timezone          string     `json:"timezone"`
	KhmerNumerals     bool       `json:"khmer_numerals"`
	TotpSecretEnc     []byte     `json:"totp_secret_enc"`
	TotpPendingEnc    []byte     `json:"totp_pending_enc"`
	TotpEnabledAt     *time.Time `json:"totp_enabled_at"`
	TotpLastStep      *int64     `json:"totp_last_step"`
	FailedLoginCount  int32      `json:"failed_login_count"`
	LockoutLevel      int32      `json:"lockout_level"`
	LockedUntil       *time.Time `json:"locked_until"`
	PasswordChangedAt *time.Time `json:"password_changed_at"`
	IsPlatformAdmin   bool       `json:"is_platform_admin"`
	DisabledAt        *time.Time `json:"disabled_at"`
	LastLoginAt       *time.Time `json:"last_login_at"`
	Version           int32      `json:"version"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
}

type UserIdentity struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CodeHash  []byte     `json:"code_hash"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID `json:"id"`
	RepositoryID   uuid.UUID `json:"repository_id"`
	DeliveryID     string    `json:"delivery_id"`
	Event          string    `json:"event"`
	Ref            string    `json:"ref"`
	CommitSha      string    `json:"commit_sha"`
	SignatureValid bool      `json:"signature_valid"`
	Payload        []byte    `json:"payload"`
	ReceivedAt     time.Time `json:"received_at"`
}
