// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type EmailTokenPurpose string

const (
	EmailTokenPurposeVerifyEmail   EmailTokenPurpose = "verify_email"
	EmailTokenPurposeResetPassword EmailTokenPurpose = "reset_password"
)

func (e *EmailTokenPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EmailTokenPurpose(s)
	case string:
		*e = EmailTokenPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for EmailTokenPurpose: %T", src)
	}
	return nil
}

type NullEmailTokenPurpose struct {
	EmailTokenPurpose EmailTokenPurpose `json:"email_token_purpose"`
	Valid             bool              `json:"valid"` // Valid is true if EmailTokenPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEmailTokenPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.EmailTokenPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EmailTokenPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEmailTokenPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EmailTokenPurpose), nil
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleAdmin     MemberRole = "admin"
	MemberRoleDeveloper MemberRole = "developer"
	MemberRoleViewer    MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type ApiToken struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	Name        string     `json:"name"`
	TokenPrefix string     `json:"token_prefix"`
	TokenHash   []byte     `json:"token_hash"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type AuditLog struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID *uuid.UUID  `json:"organization_id"`
	ActorUserID    *uuid.UUID  `json:"actor_user_id"`
	ActorType      string      `json:"actor_type"`
	Action         string      `json:"action"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     *string     `json:"resource_id"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      *string     `json:"user_agent"`
	Before         []byte      `json:"before"`
	After          []byte      `json:"after"`
	Metadata       []byte      `json:"metadata"`
	CreatedAt      time.Time   `json:"created_at"`
}

type EmailToken struct {
	ID        uuid.UUID         `json:"id"`
	UserID    uuid.UUID         `json:"user_id"`
	Purpose   EmailTokenPurpose `json:"purpose"`
	TokenHash []byte            `json:"token_hash"`
	ExpiresAt time.Time         `json:"expires_at"`
	UsedAt    *time.Time        `json:"used_at"`
	CreatedAt time.Time         `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Name      string     `json:"name"`
	Settings  []byte     `json:"settings"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Role           MemberRole `json:"role"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	TokenHash   []byte      `json:"token_hash"`
	MfaVerified bool        `json:"mfa_verified"`
	Ip          *netip.Addr `json:"ip"`
	UserAgent   *string     `json:"user_agent"`
	ExpiresAt   time.Time   `json:"expires_at"`
	LastSeenAt  time.Time   `json:"last_seen_at"`
	RevokedAt   *time.Time  `json:"revoked_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Team struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type TeamMember struct {
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	PasswordHash    *string    `json:"password_hash"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	Locale          string     `json:"locale"`
	Timezone        string     `json:"timezone"`
	KhmerNumerals   bool       `json:"khmer_numerals"`
	TotpSecretEnc   []byte     `json:"totp_secret_enc"`
	TotpEnabledAt   *time.Time `json:"totp_enabled_at"`
	IsPlatformAdmin bool       `json:"is_platform_admin"`
	DisabledAt      *time.Time `json:"disabled_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	DeletedAt       *time.Time `json:"deleted_at"`
}

type UserIdentity struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	CodeHash  []byte     `json:"code_hash"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}
