// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimDueMonitors = `-- name: ClaimDueMonitors :many
UPDATE monitors SET next_check_at = now() + make_interval(secs => interval_seconds)
WHERE id IN (
  SELECT id FROM monitors WHERE enabled AND next_check_at <= now()
  ORDER BY next_check_at LIMIT $1 FOR UPDATE SKIP LOCKED
)
RETURNING id, organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, last_up, last_checked_at, last_latency_ms, last_error, down_since, next_check_at, created_by, version, created_at, updated_at
`

// Takes due monitors and schedules their next check, so concurrent workers never run the
// same check twice.
func (q *Queries) ClaimDueMonitors(ctx context.Context, maxMonitors int32) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, claimDueMonitors, maxMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutMs,
			&i.Config,
			&i.Labels,
			&i.Enabled,
			&i.LastUp,
			&i.LastCheckedAt,
			&i.LastLatencyMs,
			&i.LastError,
			&i.DownSince,
			&i.NextCheckAt,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, last_up, last_checked_at, last_latency_ms, last_error, down_since, next_check_at, created_by, version, created_at, updated_at
`

type CreateMonitorParams struct {
	OrganizationID  uuid.UUID   `json:"organization_id"`
	Name            string      `json:"name"`
	Kind            MonitorKind `json:"kind"`
	Target          string      `json:"target"`
	IntervalSeconds int32       `json:"interval_seconds"`
	TimeoutMs       int32       `json:"timeout_ms"`
	Config          []byte      `json:"config"`
	Labels          []string    `json:"labels"`
	Enabled         bool        `json:"enabled"`
	CreatedBy       *uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.OrganizationID,
		arg.Name,
		arg.Kind,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.Config,
		arg.Labels,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.Config,
		&i.Labels,
		&i.Enabled,
		&i.LastUp,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.LastError,
		&i.DownSince,
		&i.NextCheckAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :execrows
DELETE FROM monitors WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldMonitorHourly = `-- name: DeleteOldMonitorHourly :execrows
DELETE FROM monitor_results_hourly WHERE hour < $1
`

func (q *Queries) DeleteOldMonitorHourly(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMonitorHourly, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMonitor = `-- name: GetMonitor :one
SELECT id, organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, last_up, last_checked_at, last_latency_ms, last_error, down_since, next_check_at, created_by, version, created_at, updated_at FROM monitors WHERE id = $1
`

func (q *Queries) GetMonitor(ctx context.Context, id uuid.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitor, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.Config,
		&i.Labels,
		&i.Enabled,
		&i.LastUp,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.LastError,
		&i.DownSince,
		&i.NextCheckAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hourlyMonitorSeries = `-- name: HourlyMonitorSeries :many
SELECT date_bin(make_interval(secs => $1::integer), hour, $2::timestamptz)::timestamptz AS bucket,
       sum(checks)::integer AS checks,
       sum(up_checks)::integer AS up_checks,
       coalesce(sum(latency_avg * up_checks) / nullif(sum(up_checks) FILTER (WHERE latency_avg IS NOT NULL), 0), -1)::real AS latency_avg,
       coalesce(max(latency_max), -1)::integer AS latency_max
FROM monitor_results_hourly
WHERE monitor_id = $3 AND hour >= $2 AND hour < $4
GROUP BY bucket ORDER BY bucket
`

type HourlyMonitorSeriesParams struct {
	StepSeconds int32     `json:"step_seconds"`
	FromTs      time.Time `json:"from_ts"`
	MonitorID   uuid.UUID `json:"monitor_id"`
	ToTs        time.Time `json:"to_ts"`
}

type HourlyMonitorSeriesRow struct {
	Bucket     time.Time `json:"bucket"`
	Checks     int32     `json:"checks"`
	UpChecks   int32     `json:"up_checks"`
	LatencyAvg float32   `json:"latency_avg"`
	LatencyMax int32     `json:"latency_max"`
}

func (q *Queries) HourlyMonitorSeries(ctx context.Context, arg HourlyMonitorSeriesParams) ([]HourlyMonitorSeriesRow, error) {
	rows, err := q.db.Query(ctx, hourlyMonitorSeries,
		arg.StepSeconds,
		arg.FromTs,
		arg.MonitorID,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HourlyMonitorSeriesRow{}
	for rows.Next() {
		var i HourlyMonitorSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Checks,
			&i.UpChecks,
			&i.LatencyAvg,
			&i.LatencyMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMonitorResult = `-- name: InsertMonitorResult :exec
INSERT INTO monitor_results (monitor_id, ts, up, latency_ms, status_code, error)
VALUES ($1, date_trunc('milliseconds', now()), $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertMonitorResultParams struct {
	MonitorID  uuid.UUID `json:"monitor_id"`
	Up         bool      `json:"up"`
	LatencyMs  *int32    `json:"latency_ms"`
	StatusCode *int32    `json:"status_code"`
	Error      string    `json:"error"`
}

func (q *Queries) InsertMonitorResult(ctx context.Context, arg InsertMonitorResultParams) error {
	_, err := q.db.Exec(ctx, insertMonitorResult,
		arg.MonitorID,
		arg.Up,
		arg.LatencyMs,
		arg.StatusCode,
		arg.Error,
	)
	return err
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, last_up, last_checked_at, last_latency_ms, last_error, down_since, next_check_at, created_by, version, created_at, updated_at FROM monitors
WHERE organization_id = $1
  AND ($2::text IS NULL OR $2 = ANY (labels))
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%' OR target ILIKE '%' || $3 || '%')
ORDER BY name
`

type ListMonitorsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Label          *string   `json:"label"`
	Search         *string   `json:"search"`
}

func (q *Queries) ListMonitors(ctx context.Context, arg ListMonitorsParams) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors, arg.OrganizationID, arg.Label, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.IntervalSeconds,
			&i.TimeoutMs,
			&i.Config,
			&i.Labels,
			&i.Enabled,
			&i.LastUp,
			&i.LastCheckedAt,
			&i.LastLatencyMs,
			&i.LastError,
			&i.DownSince,
			&i.NextCheckAt,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintainMonitorPartitions = `-- name: MaintainMonitorPartitions :exec
SELECT opshub_maintain_monitor_partitions($1::integer)
`

func (q *Queries) MaintainMonitorPartitions(ctx context.Context, keepMonths int32) error {
	_, err := q.db.Exec(ctx, maintainMonitorPartitions, keepMonths)
	return err
}

const monitorUptime24h = `-- name: MonitorUptime24h :many
SELECT monitor_id, count(*)::integer AS checks, count(*) FILTER (WHERE up)::integer AS up_checks
FROM monitor_results
WHERE monitor_id IN (SELECT id FROM monitors WHERE organization_id = $1) AND ts >= now() - interval '24 hours'
GROUP BY monitor_id
`

type MonitorUptime24hRow struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Checks    int32     `json:"checks"`
	UpChecks  int32     `json:"up_checks"`
}

func (q *Queries) MonitorUptime24h(ctx context.Context, organizationID uuid.UUID) ([]MonitorUptime24hRow, error) {
	rows, err := q.db.Query(ctx, monitorUptime24h, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitorUptime24hRow{}
	for rows.Next() {
		var i MonitorUptime24hRow
		if err := rows.Scan(&i.MonitorID, &i.Checks, &i.UpChecks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rawMonitorSeries = `-- name: RawMonitorSeries :many
SELECT date_bin(make_interval(secs => $1::integer), ts, $2::timestamptz)::timestamptz AS bucket,
       count(*)::integer AS checks,
       count(*) FILTER (WHERE up)::integer AS up_checks,
       coalesce(avg(latency_ms) FILTER (WHERE up), -1)::real AS latency_avg,
       coalesce(max(latency_ms) FILTER (WHERE up), -1)::integer AS latency_max
FROM monitor_results
WHERE monitor_id = $3 AND ts >= $2 AND ts < $4
GROUP BY bucket ORDER BY bucket
`

type RawMonitorSeriesParams struct {
	StepSeconds int32     `json:"step_seconds"`
	FromTs      time.Time `json:"from_ts"`
	MonitorID   uuid.UUID `json:"monitor_id"`
	ToTs        time.Time `json:"to_ts"`
}

type RawMonitorSeriesRow struct {
	Bucket     time.Time `json:"bucket"`
	Checks     int32     `json:"checks"`
	UpChecks   int32     `json:"up_checks"`
	LatencyAvg float32   `json:"latency_avg"`
	LatencyMax int32     `json:"latency_max"`
}

// Buckets of step_seconds; latency is averaged over successful checks. -1 = no value.
func (q *Queries) RawMonitorSeries(ctx context.Context, arg RawMonitorSeriesParams) ([]RawMonitorSeriesRow, error) {
	rows, err := q.db.Query(ctx, rawMonitorSeries,
		arg.StepSeconds,
		arg.FromTs,
		arg.MonitorID,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawMonitorSeriesRow{}
	for rows.Next() {
		var i RawMonitorSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Checks,
			&i.UpChecks,
			&i.LatencyAvg,
			&i.LatencyMax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentMonitorResults = `-- name: RecentMonitorResults :many
SELECT ts, up, latency_ms, status_code, error FROM monitor_results
WHERE monitor_id = $1 ORDER BY ts DESC LIMIT $2
`

type RecentMonitorResultsParams struct {
	MonitorID  uuid.UUID `json:"monitor_id"`
	MaxResults int32     `json:"max_results"`
}

type RecentMonitorResultsRow struct {
	Ts         time.Time `json:"ts"`
	Up         bool      `json:"up"`
	LatencyMs  *int32    `json:"latency_ms"`
	StatusCode *int32    `json:"status_code"`
	Error      string    `json:"error"`
}

func (q *Queries) RecentMonitorResults(ctx context.Context, arg RecentMonitorResultsParams) ([]RecentMonitorResultsRow, error) {
	rows, err := q.db.Query(ctx, recentMonitorResults, arg.MonitorID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentMonitorResultsRow{}
	for rows.Next() {
		var i RecentMonitorResultsRow
		if err := rows.Scan(
			&i.Ts,
			&i.Up,
			&i.LatencyMs,
			&i.StatusCode,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupMonitorResults = `-- name: RollupMonitorResults :exec
INSERT INTO monitor_results_hourly (monitor_id, hour, checks, up_checks, latency_avg, latency_max)
SELECT monitor_id, date_trunc('hour', ts), count(*), count(*) FILTER (WHERE up),
       avg(latency_ms) FILTER (WHERE up), max(latency_ms) FILTER (WHERE up)
FROM monitor_results
WHERE ts >= $1 AND ts < $2
GROUP BY monitor_id, date_trunc('hour', ts)
ON CONFLICT (monitor_id, hour) DO UPDATE SET checks = EXCLUDED.checks, up_checks = EXCLUDED.up_checks,
  latency_avg = EXCLUDED.latency_avg, latency_max = EXCLUDED.latency_max
`

type RollupMonitorResultsParams struct {
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

// Rolls up the whole hours in [from_ts, to_ts); re-running replaces them.
func (q *Queries) RollupMonitorResults(ctx context.Context, arg RollupMonitorResultsParams) error {
	_, err := q.db.Exec(ctx, rollupMonitorResults, arg.FromTs, arg.ToTs)
	return err
}

const setMonitorState = `-- name: SetMonitorState :exec
UPDATE monitors SET last_up = $1, last_checked_at = now(), last_latency_ms = $2, last_error = $3,
  down_since = CASE WHEN $1::boolean THEN NULL ELSE coalesce(down_since, now()) END
WHERE id = $4
`

type SetMonitorStateParams struct {
	Up        *bool     `json:"up"`
	LatencyMs *int32    `json:"latency_ms"`
	Error     string    `json:"error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetMonitorState(ctx context.Context, arg SetMonitorStateParams) error {
	_, err := q.db.Exec(ctx, setMonitorState,
		arg.Up,
		arg.LatencyMs,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors SET name = $1, target = $2, interval_seconds = $3, timeout_ms = $4,
  config = $5, labels = $6, enabled = $7, next_check_at = now(), version = version + 1,
  last_up = CASE WHEN target = $2 AND config = $5 THEN last_up END,
  down_since = CASE WHEN target = $2 AND config = $5 THEN down_since END,
  last_error = CASE WHEN target = $2 AND config = $5 THEN last_error ELSE '' END
WHERE id = $8 AND version = $9
RETURNING id, organization_id, name, kind, target, interval_seconds, timeout_ms, config, labels, enabled, last_up, last_checked_at, last_latency_ms, last_error, down_since, next_check_at, created_by, version, created_at, updated_at
`

type UpdateMonitorParams struct {
	Name            string    `json:"name"`
	Target          string    `json:"target"`
	IntervalSeconds int32     `json:"interval_seconds"`
	TimeoutMs       int32     `json:"timeout_ms"`
	Config          []byte    `json:"config"`
	Labels          []string  `json:"labels"`
	Enabled         bool      `json:"enabled"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

// Edits check again right away and forget the old state when what is checked changed.
func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.Name,
		arg.Target,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.Config,
		arg.Labels,
		arg.Enabled,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.Config,
		&i.Labels,
		&i.Enabled,
		&i.LastUp,
		&i.LastCheckedAt,
		&i.LastLatencyMs,
		&i.LastError,
		&i.DownSince,
		&i.NextCheckAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
