// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOrganizationMember = `-- name: AddOrganizationMember :exec
INSERT INTO organization_members (organization_id, user_id, role) VALUES ($1, $2, $3)
`

type AddOrganizationMemberParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	UserID         uuid.UUID  `json:"user_id"`
	Role           MemberRole `json:"role"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, addOrganizationMember, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (slug, name) VALUES ($1, $2) RETURNING id, slug, name, settings, version, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Settings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationForMember = `-- name: GetOrganizationForMember :one
SELECT o.id, o.slug, o.name, o.settings, o.version, o.created_at, o.updated_at, o.deleted_at, m.role
FROM organizations o
JOIN organization_members m ON m.organization_id = o.id AND m.user_id = $1
WHERE o.id = $2 AND o.deleted_at IS NULL
`

type GetOrganizationForMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetOrganizationForMemberRow struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Name      string     `json:"name"`
	Settings  []byte     `json:"settings"`
	Version   int32      `json:"version"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	Role      MemberRole `json:"role"`
}

// Tenant-scoped read: returns no row unless the user is a member.
func (q *Queries) GetOrganizationForMember(ctx context.Context, arg GetOrganizationForMemberParams) (GetOrganizationForMemberRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationForMember, arg.UserID, arg.ID)
	var i GetOrganizationForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Settings,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Role,
	)
	return i, err
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.slug, o.name, o.created_at, m.role
FROM organizations o
JOIN organization_members m ON m.organization_id = o.id
WHERE m.user_id = $1 AND o.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (o.name, o.id) > ($2::text, $3::uuid))
ORDER BY o.name, o.id
LIMIT $4
`

type ListUserOrganizationsParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	CursorName *string    `json:"cursor_name"`
	CursorID   *uuid.UUID `json:"cursor_id"`
	PageSize   int32      `json:"page_size"`
}

type ListUserOrganizationsRow struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	Role      MemberRole `json:"role"`
}

func (q *Queries) ListUserOrganizations(ctx context.Context, arg ListUserOrganizationsParams) ([]ListUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations,
		arg.UserID,
		arg.CursorName,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationsRow{}
	for rows.Next() {
		var i ListUserOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
