// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipelines.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addLogBytes = `-- name: AddLogBytes :one
UPDATE pipeline_jobs SET log_bytes = log_bytes + $1 WHERE id = $2 RETURNING log_bytes
`

type AddLogBytesParams struct {
	Bytes int64     `json:"bytes"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) AddLogBytes(ctx context.Context, arg AddLogBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, addLogBytes, arg.Bytes, arg.ID)
	var log_bytes int64
	err := row.Scan(&log_bytes)
	return log_bytes, err
}

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE pipeline_schedules SET next_run_at = $1, last_run_at = now() WHERE id = $2
`

type AdvanceScheduleParams struct {
	NextRunAt time.Time `json:"next_run_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.NextRunAt, arg.ID)
	return err
}

const claimJob = `-- name: ClaimJob :one
SELECT id, run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment, environment_id, runs_on, spec, status, attempt, runner_id, timeout_seconds, exit_code, failure_reason, log_bytes, queued_at, started_at, finished_at, created_at, updated_at FROM pipeline_jobs
WHERE organization_id = $1 AND status = 'queued' AND runs_on <@ $2::text[]
  AND spec->'deploy' IS NULL -- deploy jobs are performed by OpsHub (Module 6), not runners
ORDER BY queued_at, id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimJobParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Labels         []string  `json:"labels"`
}

// Oldest queued runner job of the organization whose required labels the runner has.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.OrganizationID, arg.Labels)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.Stage,
		&i.StageIndex,
		&i.Needs,
		&i.Condition,
		&i.Environment,
		&i.EnvironmentID,
		&i.RunsOn,
		&i.Spec,
		&i.Status,
		&i.Attempt,
		&i.RunnerID,
		&i.TimeoutSeconds,
		&i.ExitCode,
		&i.FailureReason,
		&i.LogBytes,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countApprovals = `-- name: CountApprovals :one
SELECT count(*) FROM job_approvals WHERE job_id = $1 AND decision = 'approved'
`

func (q *Queries) CountApprovals(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovals, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentJobs = `-- name: CurrentJobs :many
SELECT DISTINCT ON (name) id, run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment, environment_id, runs_on, spec, status, attempt, runner_id, timeout_seconds, exit_code, failure_reason, log_bytes, queued_at, started_at, finished_at, created_at, updated_at FROM pipeline_jobs WHERE run_id = $1 ORDER BY name, attempt DESC
`

// The latest attempt of every job in a run.
func (q *Queries) CurrentJobs(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error) {
	rows, err := q.db.Query(ctx, currentJobs, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineJob{}
	for rows.Next() {
		var i PipelineJob
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProjectID,
			&i.OrganizationID,
			&i.Name,
			&i.Stage,
			&i.StageIndex,
			&i.Needs,
			&i.Condition,
			&i.Environment,
			&i.EnvironmentID,
			&i.RunsOn,
			&i.Spec,
			&i.Status,
			&i.Attempt,
			&i.RunnerID,
			&i.TimeoutSeconds,
			&i.ExitCode,
			&i.FailureReason,
			&i.LogBytes,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSchedulesExcept = `-- name: DeleteSchedulesExcept :exec
DELETE FROM pipeline_schedules WHERE project_id = $1 AND NOT (cron = ANY($2::text[]))
`

type DeleteSchedulesExceptParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Keep      []string  `json:"keep"`
}

func (q *Queries) DeleteSchedulesExcept(ctx context.Context, arg DeleteSchedulesExceptParams) error {
	_, err := q.db.Exec(ctx, deleteSchedulesExcept, arg.ProjectID, arg.Keep)
	return err
}

const dueSchedules = `-- name: DueSchedules :many
SELECT id, project_id, cron, next_run_at, last_run_at, created_at, updated_at FROM pipeline_schedules WHERE next_run_at <= now() ORDER BY next_run_at LIMIT 50 FOR UPDATE SKIP LOCKED
`

func (q *Queries) DueSchedules(ctx context.Context) ([]PipelineSchedule, error) {
	rows, err := q.db.Query(ctx, dueSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineSchedule{}
	for rows.Next() {
		var i PipelineSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Cron,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredRunningJobs = `-- name: ExpiredRunningJobs :many
SELECT id, run_id FROM pipeline_jobs
WHERE status = 'running' AND started_at + make_interval(secs => timeout_seconds) < now()
LIMIT 100
`

type ExpiredRunningJobsRow struct {
	ID    uuid.UUID `json:"id"`
	RunID uuid.UUID `json:"run_id"`
}

func (q *Queries) ExpiredRunningJobs(ctx context.Context) ([]ExpiredRunningJobsRow, error) {
	rows, err := q.db.Query(ctx, expiredRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredRunningJobsRow{}
	for rows.Next() {
		var i ExpiredRunningJobsRow
		if err := rows.Scan(&i.ID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishOpenSteps = `-- name: FinishOpenSteps :exec
UPDATE job_steps SET status = $1, finished_at = now()
WHERE job_id = $2 AND status IN ('pending', 'running')
`

type FinishOpenStepsParams struct {
	Status StepStatus `json:"status"`
	JobID  uuid.UUID  `json:"job_id"`
}

// Steps still pending or running when a job ends.
func (q *Queries) FinishOpenSteps(ctx context.Context, arg FinishOpenStepsParams) error {
	_, err := q.db.Exec(ctx, finishOpenSteps, arg.Status, arg.JobID)
	return err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT e.id, e.project_id, e.name, e.kind, e.variables, e.version, e.created_at, e.updated_at, e.deleted_at, e.current_deployment_id,
       (pr.environment_id IS NOT NULL)::boolean AS protected,
       coalesce(pr.required_approvals, 0)::integer AS required_approvals,
       coalesce(pr.allowed_branches, '{}')::text[] AS allowed_branches,
       coalesce(pr.allowed_roles::text[], '{}')::text[] AS allowed_roles
FROM environments e
LEFT JOIN protection_rules pr ON pr.environment_id = e.id
WHERE e.project_id = $1 AND e.name = $2 AND e.deleted_at IS NULL
`

type GetEnvironmentByNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

type GetEnvironmentByNameRow struct {
	Environment       Environment `json:"environment"`
	Protected         bool        `json:"protected"`
	RequiredApprovals int32       `json:"required_approvals"`
	AllowedBranches   []string    `json:"allowed_branches"`
	AllowedRoles      []string    `json:"allowed_roles"`
}

func (q *Queries) GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (GetEnvironmentByNameRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, arg.ProjectID, arg.Name)
	var i GetEnvironmentByNameRow
	err := row.Scan(
		&i.Environment.ID,
		&i.Environment.ProjectID,
		&i.Environment.Name,
		&i.Environment.Kind,
		&i.Environment.Variables,
		&i.Environment.Version,
		&i.Environment.CreatedAt,
		&i.Environment.UpdatedAt,
		&i.Environment.DeletedAt,
		&i.Environment.CurrentDeploymentID,
		&i.Protected,
		&i.RequiredApprovals,
		&i.AllowedBranches,
		&i.AllowedRoles,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment, environment_id, runs_on, spec, status, attempt, runner_id, timeout_seconds, exit_code, failure_reason, log_bytes, queued_at, started_at, finished_at, created_at, updated_at FROM pipeline_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.Stage,
		&i.StageIndex,
		&i.Needs,
		&i.Condition,
		&i.Environment,
		&i.EnvironmentID,
		&i.RunsOn,
		&i.Spec,
		&i.Status,
		&i.Attempt,
		&i.RunnerID,
		&i.TimeoutSeconds,
		&i.ExitCode,
		&i.FailureReason,
		&i.LogBytes,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForPipeline = `-- name: GetProjectForPipeline :one
SELECT p.id, p.organization_id, p.slug, p.name, p.description, p.default_branch, p.version, p.created_by, p.created_at, p.updated_at, p.deleted_at, p.last_run_number, p.last_deployment_number, r.id AS repository_id
FROM projects p
LEFT JOIN repositories r ON r.project_id = p.id
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetProjectForPipelineRow struct {
	ID                   uuid.UUID  `json:"id"`
	OrganizationID       uuid.UUID  `json:"organization_id"`
	Slug                 string     `json:"slug"`
	Name                 string     `json:"name"`
	Description          string     `json:"description"`
	DefaultBranch        string     `json:"default_branch"`
	Version              int32      `json:"version"`
	CreatedBy            *uuid.UUID `json:"created_by"`
	CreatedAt            time.Time  `json:"created_at"`
	UpdatedAt            time.Time  `json:"updated_at"`
	DeletedAt            *time.Time `json:"deleted_at"`
	LastRunNumber        int32      `json:"last_run_number"`
	LastDeploymentNumber int32      `json:"last_deployment_number"`
	RepositoryID         *uuid.UUID `json:"repository_id"`
}

func (q *Queries) GetProjectForPipeline(ctx context.Context, id uuid.UUID) (GetProjectForPipelineRow, error) {
	row := q.db.QueryRow(ctx, getProjectForPipeline, id)
	var i GetProjectForPipelineRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DefaultBranch,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.LastRunNumber,
		&i.LastDeploymentNumber,
		&i.RepositoryID,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, organization_id, project_id, number, status, trigger, ref, commit_sha, title, actor_name, created_by, rerun_of, definition, problems, variables, started_at, finished_at, created_at, updated_at, committed_at FROM pipeline_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Trigger,
		&i.Ref,
		&i.CommitSha,
		&i.Title,
		&i.ActorName,
		&i.CreatedBy,
		&i.RerunOf,
		&i.Definition,
		&i.Problems,
		&i.Variables,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, project_id, cron, next_run_at, last_run_at, created_at, updated_at FROM pipeline_schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (PipelineSchedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i PipelineSchedule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Cron,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertApproval = `-- name: InsertApproval :one
INSERT INTO job_approvals (job_id, user_id, decision, comment) VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, user_id) DO NOTHING
RETURNING id
`

type InsertApprovalParams struct {
	JobID    uuid.UUID        `json:"job_id"`
	UserID   uuid.UUID        `json:"user_id"`
	Decision ApprovalDecision `json:"decision"`
	Comment  string           `json:"comment"`
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertApproval,
		arg.JobID,
		arg.UserID,
		arg.Decision,
		arg.Comment,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO pipeline_jobs (
  run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment,
  environment_id, runs_on, spec, status, attempt, timeout_seconds
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14, $15
)
RETURNING id, run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment, environment_id, runs_on, spec, status, attempt, runner_id, timeout_seconds, exit_code, failure_reason, log_bytes, queued_at, started_at, finished_at, created_at, updated_at
`

type InsertJobParams struct {
	RunID          uuid.UUID  `json:"run_id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Stage          string     `json:"stage"`
	StageIndex     int32      `json:"stage_index"`
	Needs          []string   `json:"needs"`
	Condition      string     `json:"condition"`
	Environment    *string    `json:"environment"`
	EnvironmentID  *uuid.UUID `json:"environment_id"`
	RunsOn         []string   `json:"runs_on"`
	Spec           []byte     `json:"spec"`
	Status         JobStatus  `json:"status"`
	Attempt        int32      `json:"attempt"`
	TimeoutSeconds int32      `json:"timeout_seconds"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.RunID,
		arg.ProjectID,
		arg.OrganizationID,
		arg.Name,
		arg.Stage,
		arg.StageIndex,
		arg.Needs,
		arg.Condition,
		arg.Environment,
		arg.EnvironmentID,
		arg.RunsOn,
		arg.Spec,
		arg.Status,
		arg.Attempt,
		arg.TimeoutSeconds,
	)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.Stage,
		&i.StageIndex,
		&i.Needs,
		&i.Condition,
		&i.Environment,
		&i.EnvironmentID,
		&i.RunsOn,
		&i.Spec,
		&i.Status,
		&i.Attempt,
		&i.RunnerID,
		&i.TimeoutSeconds,
		&i.ExitCode,
		&i.FailureReason,
		&i.LogBytes,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLogChunk = `-- name: InsertLogChunk :execrows
INSERT INTO job_log_chunks (job_id, seq, content) VALUES ($1, $2, $3)
ON CONFLICT (job_id, seq) DO NOTHING
`

type InsertLogChunkParams struct {
	JobID   uuid.UUID `json:"job_id"`
	Seq     int32     `json:"seq"`
	Content string    `json:"content"`
}

func (q *Queries) InsertLogChunk(ctx context.Context, arg InsertLogChunkParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLogChunk, arg.JobID, arg.Seq, arg.Content)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRun = `-- name: InsertRun :one
INSERT INTO pipeline_runs (
  organization_id, project_id, number, status, trigger, ref, commit_sha, title, actor_name,
  created_by, rerun_of, definition, problems, variables, finished_at, committed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, organization_id, project_id, number, status, trigger, ref, commit_sha, title, actor_name, created_by, rerun_of, definition, problems, variables, started_at, finished_at, created_at, updated_at, committed_at
`

type InsertRunParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	Number         int32      `json:"number"`
	Status         RunStatus  `json:"status"`
	Trigger        RunTrigger `json:"trigger"`
	Ref            string     `json:"ref"`
	CommitSha      string     `json:"commit_sha"`
	Title          string     `json:"title"`
	ActorName      string     `json:"actor_name"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	RerunOf        *uuid.UUID `json:"rerun_of"`
	Definition     []byte     `json:"definition"`
	Problems       []byte     `json:"problems"`
	Variables      []byte     `json:"variables"`
	FinishedAt     *time.Time `json:"finished_at"`
	CommittedAt    *time.Time `json:"committed_at"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.OrganizationID,
		arg.ProjectID,
		arg.Number,
		arg.Status,
		arg.Trigger,
		arg.Ref,
		arg.CommitSha,
		arg.Title,
		arg.ActorName,
		arg.CreatedBy,
		arg.RerunOf,
		arg.Definition,
		arg.Problems,
		arg.Variables,
		arg.FinishedAt,
		arg.CommittedAt,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Trigger,
		&i.Ref,
		&i.CommitSha,
		&i.Title,
		&i.ActorName,
		&i.CreatedBy,
		&i.RerunOf,
		&i.Definition,
		&i.Problems,
		&i.Variables,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const insertStep = `-- name: InsertStep :exec
INSERT INTO job_steps (job_id, index, name, command) VALUES ($1, $2, $3, $4)
`

type InsertStepParams struct {
	JobID   uuid.UUID `json:"job_id"`
	Index   int32     `json:"index"`
	Name    string    `json:"name"`
	Command string    `json:"command"`
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) error {
	_, err := q.db.Exec(ctx, insertStep,
		arg.JobID,
		arg.Index,
		arg.Name,
		arg.Command,
	)
	return err
}

const listApprovals = `-- name: ListApprovals :many
SELECT a.id, a.job_id, a.user_id, a.decision, a.comment, a.created_at, u.display_name, u.email
FROM job_approvals a JOIN users u ON u.id = a.user_id
WHERE a.job_id = $1 ORDER BY a.created_at
`

type ListApprovalsRow struct {
	ID          uuid.UUID        `json:"id"`
	JobID       uuid.UUID        `json:"job_id"`
	UserID      uuid.UUID        `json:"user_id"`
	Decision    ApprovalDecision `json:"decision"`
	Comment     string           `json:"comment"`
	CreatedAt   time.Time        `json:"created_at"`
	DisplayName string           `json:"display_name"`
	Email       string           `json:"email"`
}

func (q *Queries) ListApprovals(ctx context.Context, jobID uuid.UUID) ([]ListApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listApprovals, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalsRow{}
	for rows.Next() {
		var i ListApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.Decision,
			&i.Comment,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobAttempts = `-- name: ListJobAttempts :many
SELECT id, run_id, project_id, organization_id, name, stage, stage_index, needs, condition, environment, environment_id, runs_on, spec, status, attempt, runner_id, timeout_seconds, exit_code, failure_reason, log_bytes, queued_at, started_at, finished_at, created_at, updated_at FROM pipeline_jobs WHERE run_id = $1 AND name = $2 ORDER BY attempt DESC
`

type ListJobAttemptsParams struct {
	RunID uuid.UUID `json:"run_id"`
	Name  string    `json:"name"`
}

func (q *Queries) ListJobAttempts(ctx context.Context, arg ListJobAttemptsParams) ([]PipelineJob, error) {
	rows, err := q.db.Query(ctx, listJobAttempts, arg.RunID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineJob{}
	for rows.Next() {
		var i PipelineJob
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ProjectID,
			&i.OrganizationID,
			&i.Name,
			&i.Stage,
			&i.StageIndex,
			&i.Needs,
			&i.Condition,
			&i.Environment,
			&i.EnvironmentID,
			&i.RunsOn,
			&i.Spec,
			&i.Status,
			&i.Attempt,
			&i.RunnerID,
			&i.TimeoutSeconds,
			&i.ExitCode,
			&i.FailureReason,
			&i.LogBytes,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogChunks = `-- name: ListLogChunks :many
SELECT seq, content FROM job_log_chunks WHERE job_id = $1 AND seq > $2 ORDER BY seq LIMIT $3
`

type ListLogChunksParams struct {
	JobID    uuid.UUID `json:"job_id"`
	AfterSeq int32     `json:"after_seq"`
	PageSize int32     `json:"page_size"`
}

type ListLogChunksRow struct {
	Seq     int32  `json:"seq"`
	Content string `json:"content"`
}

func (q *Queries) ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]ListLogChunksRow, error) {
	rows, err := q.db.Query(ctx, listLogChunks, arg.JobID, arg.AfterSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogChunksRow{}
	for rows.Next() {
		var i ListLogChunksRow
		if err := rows.Scan(&i.Seq, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.organization_id, r.project_id, r.number, r.status, r.trigger, r.ref, r.commit_sha, r.title, r.actor_name, r.created_by, r.rerun_of, r.definition, r.problems, r.variables, r.started_at, r.finished_at, r.created_at, r.updated_at, r.committed_at, coalesce(u.display_name, '')::text AS created_by_name
FROM pipeline_runs r
LEFT JOIN users u ON u.id = r.created_by
WHERE r.project_id = $1
  AND ($2::run_status IS NULL OR r.status = $2::run_status)
  AND ($3::run_trigger IS NULL OR r.trigger = $3::run_trigger)
  AND ($4::text IS NULL OR r.ref = $4::text)
  AND ($5::timestamptz IS NULL
       OR (r.created_at, r.id) < ($5::timestamptz, $6::uuid))
ORDER BY r.created_at DESC, r.id DESC
LIMIT $7
`

type ListRunsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Status    *RunStatus  `json:"status"`
	Trigger   *RunTrigger `json:"trigger"`
	Ref       *string     `json:"ref"`
	CursorAt  *time.Time  `json:"cursor_at"`
	CursorID  *uuid.UUID  `json:"cursor_id"`
	PageSize  int32       `json:"page_size"`
}

type ListRunsRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	ProjectID      uuid.UUID  `json:"project_id"`
	Number         int32      `json:"number"`
	Status         RunStatus  `json:"status"`
	Trigger        RunTrigger `json:"trigger"`
	Ref            string     `json:"ref"`
	CommitSha      string     `json:"commit_sha"`
	Title          string     `json:"title"`
	ActorName      string     `json:"actor_name"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	RerunOf        *uuid.UUID `json:"rerun_of"`
	Definition     []byte     `json:"definition"`
	Problems       []byte     `json:"problems"`
	Variables      []byte     `json:"variables"`
	StartedAt      *time.Time `json:"started_at"`
	FinishedAt     *time.Time `json:"finished_at"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	CommittedAt    *time.Time `json:"committed_at"`
	CreatedByName  string     `json:"created_by_name"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error) {
	rows, err := q.db.Query(ctx, listRuns,
		arg.ProjectID,
		arg.Status,
		arg.Trigger,
		arg.Ref,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsRow{}
	for rows.Next() {
		var i ListRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.Number,
			&i.Status,
			&i.Trigger,
			&i.Ref,
			&i.CommitSha,
			&i.Title,
			&i.ActorName,
			&i.CreatedBy,
			&i.RerunOf,
			&i.Definition,
			&i.Problems,
			&i.Variables,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommittedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, project_id, cron, next_run_at, last_run_at, created_at, updated_at FROM pipeline_schedules WHERE project_id = $1 ORDER BY cron
`

func (q *Queries) ListSchedules(ctx context.Context, projectID uuid.UUID) ([]PipelineSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PipelineSchedule{}
	for rows.Next() {
		var i PipelineSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Cron,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT job_id, index, name, command, status, exit_code, started_at, finished_at FROM job_steps WHERE job_id = $1 ORDER BY index
`

func (q *Queries) ListSteps(ctx context.Context, jobID uuid.UUID) ([]JobStep, error) {
	rows, err := q.db.Query(ctx, listSteps, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobStep{}
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.JobID,
			&i.Index,
			&i.Name,
			&i.Command,
			&i.Status,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsForJobs = `-- name: ListStepsForJobs :many
SELECT job_id, index, name, command, status, exit_code, started_at, finished_at FROM job_steps WHERE job_id = ANY($1::uuid[]) ORDER BY job_id, index
`

func (q *Queries) ListStepsForJobs(ctx context.Context, jobIds []uuid.UUID) ([]JobStep, error) {
	rows, err := q.db.Query(ctx, listStepsForJobs, jobIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobStep{}
	for rows.Next() {
		var i JobStep
		if err := rows.Scan(
			&i.JobID,
			&i.Index,
			&i.Name,
			&i.Command,
			&i.Status,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRun = `-- name: LockRun :one
SELECT id, organization_id, project_id, number, status, trigger, ref, commit_sha, title, actor_name, created_by, rerun_of, definition, problems, variables, started_at, finished_at, created_at, updated_at, committed_at FROM pipeline_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockRun(ctx context.Context, id uuid.UUID) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, lockRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.Number,
		&i.Status,
		&i.Trigger,
		&i.Ref,
		&i.CommitSha,
		&i.Title,
		&i.ActorName,
		&i.CreatedBy,
		&i.RerunOf,
		&i.Definition,
		&i.Problems,
		&i.Variables,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommittedAt,
	)
	return i, err
}

const nextRunNumber = `-- name: NextRunNumber :one
UPDATE projects SET last_run_number = last_run_number + 1 WHERE id = $1 RETURNING last_run_number
`

// Serializes run creation per project (row lock on the project).
func (q *Queries) NextRunNumber(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextRunNumber, id)
	var last_run_number int32
	err := row.Scan(&last_run_number)
	return last_run_number, err
}

const recentRunExists = `-- name: RecentRunExists :one
SELECT EXISTS (
  SELECT 1 FROM pipeline_runs
  WHERE project_id = $1 AND trigger = $2 AND ref = $3 AND commit_sha = $4
    AND rerun_of IS NULL AND created_at > now() - interval '1 hour'
)
`

type RecentRunExistsParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	Trigger   RunTrigger `json:"trigger"`
	Ref       string     `json:"ref"`
	CommitSha string     `json:"commit_sha"`
}

// Guards against creating a second run for the same event when a worker is retried.
func (q *Queries) RecentRunExists(ctx context.Context, arg RecentRunExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentRunExists,
		arg.ProjectID,
		arg.Trigger,
		arg.Ref,
		arg.CommitSha,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setJobStatus = `-- name: SetJobStatus :exec
UPDATE pipeline_jobs SET
  status = $1,
  failure_reason = $2,
  exit_code = $3,
  queued_at = CASE WHEN $1 = 'queued'::job_status THEN now() ELSE queued_at END,
  started_at = CASE WHEN $1 = 'running'::job_status THEN now() ELSE started_at END,
  finished_at = CASE WHEN $1 IN ('succeeded', 'failed', 'canceled', 'skipped') THEN now() ELSE finished_at END
WHERE id = $4
`

type SetJobStatusParams struct {
	Status        JobStatus `json:"status"`
	FailureReason *string   `json:"failure_reason"`
	ExitCode      *int32    `json:"exit_code"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) error {
	_, err := q.db.Exec(ctx, setJobStatus,
		arg.Status,
		arg.FailureReason,
		arg.ExitCode,
		arg.ID,
	)
	return err
}

const staleQueuedJobs = `-- name: StaleQueuedJobs :many
SELECT id, run_id FROM pipeline_jobs
WHERE status = 'queued' AND queued_at < now() - interval '24 hours'
LIMIT 100
`

type StaleQueuedJobsRow struct {
	ID    uuid.UUID `json:"id"`
	RunID uuid.UUID `json:"run_id"`
}

func (q *Queries) StaleQueuedJobs(ctx context.Context) ([]StaleQueuedJobsRow, error) {
	rows, err := q.db.Query(ctx, staleQueuedJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StaleQueuedJobsRow{}
	for rows.Next() {
		var i StaleQueuedJobsRow
		if err := rows.Scan(&i.ID, &i.RunID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startJob = `-- name: StartJob :exec
UPDATE pipeline_jobs SET status = 'running', runner_id = $1, started_at = now() WHERE id = $2
`

type StartJobParams struct {
	RunnerID *uuid.UUID `json:"runner_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) StartJob(ctx context.Context, arg StartJobParams) error {
	_, err := q.db.Exec(ctx, startJob, arg.RunnerID, arg.ID)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE pipeline_runs SET status = $1, started_at = $2, finished_at = $3 WHERE id = $4
`

type UpdateRunStatusParams struct {
	Status     RunStatus  `json:"status"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const updateStep = `-- name: UpdateStep :execrows
UPDATE job_steps SET
  status = $1,
  exit_code = $2,
  started_at = CASE WHEN $1 = 'running'::step_status THEN coalesce(started_at, now()) ELSE started_at END,
  finished_at = CASE WHEN $1 IN ('succeeded', 'failed', 'skipped', 'canceled') THEN now() ELSE finished_at END
WHERE job_id = $3 AND index = $4
`

type UpdateStepParams struct {
	Status   StepStatus `json:"status"`
	ExitCode *int32     `json:"exit_code"`
	JobID    uuid.UUID  `json:"job_id"`
	Index    int32      `json:"index"`
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStep,
		arg.Status,
		arg.ExitCode,
		arg.JobID,
		arg.Index,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSchedule = `-- name: UpsertSchedule :exec
INSERT INTO pipeline_schedules (project_id, cron, next_run_at) VALUES ($1, $2, $3)
ON CONFLICT (project_id, cron) DO NOTHING
`

type UpsertScheduleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Cron      string    `json:"cron"`
	NextRunAt time.Time `json:"next_run_at"`
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertSchedule, arg.ProjectID, arg.Cron, arg.NextRunAt)
	return err
}
