// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (organization_id, slug, name, description, default_branch, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, slug, name, description, default_branch, version, created_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	Description    string     `json:"description"`
	DefaultBranch  string     `json:"default_branch"`
	CreatedBy      *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.DefaultBranch,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DefaultBranch,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProjectGrantsForTeam = `-- name: DeleteProjectGrantsForTeam :exec
DELETE FROM project_members WHERE team_id = $1::uuid
`

func (q *Queries) DeleteProjectGrantsForTeam(ctx context.Context, teamID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectGrantsForTeam, teamID)
	return err
}

const deleteProjectGrantsForUserInOrg = `-- name: DeleteProjectGrantsForUserInOrg :exec
DELETE FROM project_members pm
USING projects p
WHERE pm.project_id = p.id AND p.organization_id = $1 AND pm.user_id = $2::uuid
`

type DeleteProjectGrantsForUserInOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// Called when someone leaves or is removed from an organization.
func (q *Queries) DeleteProjectGrantsForUserInOrg(ctx context.Context, arg DeleteProjectGrantsForUserInOrgParams) error {
	_, err := q.db.Exec(ctx, deleteProjectGrantsForUserInOrg, arg.OrganizationID, arg.UserID)
	return err
}

const deleteProjectTeamGrant = `-- name: DeleteProjectTeamGrant :execrows
DELETE FROM project_members WHERE project_id = $1 AND team_id = $2::uuid
`

type DeleteProjectTeamGrantParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TeamID    uuid.UUID `json:"team_id"`
}

func (q *Queries) DeleteProjectTeamGrant(ctx context.Context, arg DeleteProjectTeamGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectTeamGrant, arg.ProjectID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectUserGrant = `-- name: DeleteProjectUserGrant :execrows
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2::uuid
`

type DeleteProjectUserGrantParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectUserGrant(ctx context.Context, arg DeleteProjectUserGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectUserGrant, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectAccess = `-- name: GetProjectAccess :one
SELECT p.id, p.organization_id, p.slug, p.name, p.description, p.default_branch, p.version, p.created_by, p.created_at, p.updated_at, p.deleted_at,
       coalesce(om.role::text, '')::text AS org_role,
       coalesce((SELECT pm.role::text FROM project_members pm
                  WHERE pm.project_id = p.id AND pm.user_id = $1::uuid), '')::text AS direct_role,
       coalesce((SELECT min(pm.role)::text FROM project_members pm
                  JOIN team_members tm ON tm.team_id = pm.team_id AND tm.user_id = $1::uuid
                  JOIN teams t ON t.id = pm.team_id AND t.deleted_at IS NULL
                  WHERE pm.project_id = p.id), '')::text AS team_role
FROM projects p
JOIN organizations o ON o.id = p.organization_id AND o.deleted_at IS NULL
LEFT JOIN organization_members om ON om.organization_id = p.organization_id AND om.user_id = $1::uuid
WHERE p.id = $2 AND p.deleted_at IS NULL
`

type GetProjectAccessParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetProjectAccessRow struct {
	Project    Project `json:"project"`
	OrgRole    string  `json:"org_role"`
	DirectRole string  `json:"direct_role"`
	TeamRole   string  `json:"team_role"`
}

// A project with the caller's organization role and project grants (docs/rbac.md); ” means
// none. The member_role enum is declared owner → viewer, so min() is the most privileged role.
func (q *Queries) GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error) {
	row := q.db.QueryRow(ctx, getProjectAccess, arg.UserID, arg.ID)
	var i GetProjectAccessRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.OrganizationID,
		&i.Project.Slug,
		&i.Project.Name,
		&i.Project.Description,
		&i.Project.DefaultBranch,
		&i.Project.Version,
		&i.Project.CreatedBy,
		&i.Project.CreatedAt,
		&i.Project.UpdatedAt,
		&i.Project.DeletedAt,
		&i.OrgRole,
		&i.DirectRole,
		&i.TeamRole,
	)
	return i, err
}

const getProjectTeamGrant = `-- name: GetProjectTeamGrant :one
SELECT role FROM project_members WHERE project_id = $1 AND team_id = $2::uuid
`

type GetProjectTeamGrantParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TeamID    uuid.UUID `json:"team_id"`
}

func (q *Queries) GetProjectTeamGrant(ctx context.Context, arg GetProjectTeamGrantParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, getProjectTeamGrant, arg.ProjectID, arg.TeamID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const getProjectUserGrant = `-- name: GetProjectUserGrant :one
SELECT role FROM project_members WHERE project_id = $1 AND user_id = $2::uuid
`

type GetProjectUserGrantParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectUserGrant(ctx context.Context, arg GetProjectUserGrantParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, getProjectUserGrant, arg.ProjectID, arg.UserID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const getTeamInOrg = `-- name: GetTeamInOrg :one
SELECT id, organization_id, slug, name, created_at, updated_at, deleted_at, description, version FROM teams WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetTeamInOrgParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetTeamInOrg(ctx context.Context, arg GetTeamInOrgParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamInOrg, arg.ID, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const listOrgManagers = `-- name: ListOrgManagers :many
SELECT u.id, u.email, u.display_name, om.role
FROM organization_members om
JOIN users u ON u.id = om.user_id AND u.deleted_at IS NULL
WHERE om.organization_id = $1 AND om.role IN ('owner', 'admin')
ORDER BY om.role, u.display_name, u.id
`

type ListOrgManagersRow struct {
	ID          uuid.UUID  `json:"id"`
	Email       string     `json:"email"`
	DisplayName string     `json:"display_name"`
	Role        MemberRole `json:"role"`
}

// Organization Owners and Admins, who inherit that role on every project.
func (q *Queries) ListOrgManagers(ctx context.Context, organizationID uuid.UUID) ([]ListOrgManagersRow, error) {
	rows, err := q.db.Query(ctx, listOrgManagers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgManagersRow{}
	for rows.Next() {
		var i ListOrgManagersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTeamGrants = `-- name: ListProjectTeamGrants :many
SELECT t.id, t.name, t.slug, pm.role, pm.created_at,
       (SELECT count(*) FROM team_members tm WHERE tm.team_id = t.id)::bigint AS member_count
FROM project_members pm
JOIN teams t ON t.id = pm.team_id AND t.deleted_at IS NULL
WHERE pm.project_id = $1
ORDER BY t.name, t.id
`

type ListProjectTeamGrantsRow struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Role        MemberRole `json:"role"`
	CreatedAt   time.Time  `json:"created_at"`
	MemberCount int64      `json:"member_count"`
}

func (q *Queries) ListProjectTeamGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectTeamGrantsRow, error) {
	rows, err := q.db.Query(ctx, listProjectTeamGrants, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTeamGrantsRow{}
	for rows.Next() {
		var i ListProjectTeamGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectUserGrants = `-- name: ListProjectUserGrants :many
SELECT u.id, u.email, u.display_name, pm.role, pm.created_at
FROM project_members pm
JOIN users u ON u.id = pm.user_id AND u.deleted_at IS NULL
WHERE pm.project_id = $1
ORDER BY u.display_name, u.id
`

type ListProjectUserGrantsRow struct {
	ID          uuid.UUID  `json:"id"`
	Email       string     `json:"email"`
	DisplayName string     `json:"display_name"`
	Role        MemberRole `json:"role"`
	CreatedAt   time.Time  `json:"created_at"`
}

func (q *Queries) ListProjectUserGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectUserGrantsRow, error) {
	rows, err := q.db.Query(ctx, listProjectUserGrants, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectUserGrantsRow{}
	for rows.Next() {
		var i ListProjectUserGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.organization_id, p.slug, p.name, p.description, p.default_branch, p.version, p.created_by, p.created_at, p.updated_at, p.deleted_at FROM projects p
WHERE p.organization_id = $1 AND p.deleted_at IS NULL
  AND ($2::boolean
       OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id = p.id AND pm.user_id = $3::uuid)
       OR EXISTS (SELECT 1 FROM project_members pm
                  JOIN team_members tm ON tm.team_id = pm.team_id AND tm.user_id = $3::uuid
                  JOIN teams t ON t.id = pm.team_id AND t.deleted_at IS NULL
                  WHERE pm.project_id = p.id))
  AND ($4::text IS NULL
       OR p.name ILIKE '%' || $4::text || '%' ESCAPE '\'
       OR p.slug ILIKE '%' || $4::text || '%' ESCAPE '\')
  AND ($5::text IS NULL
       OR (p.name, p.id) > ($5::text, $6::uuid))
ORDER BY p.name, p.id
LIMIT $7
`

type ListProjectsParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	SeeAll         bool       `json:"see_all"`
	UserID         uuid.UUID  `json:"user_id"`
	Search         *string    `json:"search"`
	CursorName     *string    `json:"cursor_name"`
	CursorID       *uuid.UUID `json:"cursor_id"`
	PageSize       int32      `json:"page_size"`
}

// Projects the caller can see: all of them when their organization role inherits a project
// role (owner/admin/viewer), otherwise those granted directly or through a team.
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.OrganizationID,
		arg.SeeAll,
		arg.UserID,
		arg.Search,
		arg.CursorName,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.DefaultBranch,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $1, description = $2, default_branch = $3,
  version = version + 1
WHERE id = $4 AND version = $5 AND deleted_at IS NULL
RETURNING id, organization_id, slug, name, description, default_branch, version, created_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	DefaultBranch string    `json:"default_branch"`
	ID            uuid.UUID `json:"id"`
	Version       int32     `json:"version"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.DefaultBranch,
		arg.ID,
		arg.Version,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.DefaultBranch,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertProjectTeamGrant = `-- name: UpsertProjectTeamGrant :exec
INSERT INTO project_members (project_id, team_id, role) VALUES ($1, $2::uuid, $3)
ON CONFLICT (project_id, team_id) WHERE team_id IS NOT NULL DO UPDATE SET role = EXCLUDED.role
`

type UpsertProjectTeamGrantParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	TeamID    uuid.UUID  `json:"team_id"`
	Role      MemberRole `json:"role"`
}

func (q *Queries) UpsertProjectTeamGrant(ctx context.Context, arg UpsertProjectTeamGrantParams) error {
	_, err := q.db.Exec(ctx, upsertProjectTeamGrant, arg.ProjectID, arg.TeamID, arg.Role)
	return err
}

const upsertProjectUserGrant = `-- name: UpsertProjectUserGrant :exec
INSERT INTO project_members (project_id, user_id, role) VALUES ($1, $2::uuid, $3)
ON CONFLICT (project_id, user_id) WHERE user_id IS NOT NULL DO UPDATE SET role = EXCLUDED.role
`

type UpsertProjectUserGrantParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	UserID    uuid.UUID  `json:"user_id"`
	Role      MemberRole `json:"role"`
}

func (q *Queries) UpsertProjectUserGrant(ctx context.Context, arg UpsertProjectUserGrantParams) error {
	_, err := q.db.Exec(ctx, upsertProjectUserGrant, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
