// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddDeploymentLogBytes(ctx context.Context, arg AddDeploymentLogBytesParams) error
	AddLogBytes(ctx context.Context, arg AddLogBytesParams) (int64, error)
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error
	// Accepts a TOTP time step only once (replay protection); returns no row if already used.
	AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (uuid.UUID, error)
	// Inserts an in-flight record (or takes over an expired one); returns no row when a live
	// record already exists for this user and key.
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error)
	// Oldest queued runner job of the organization whose required labels the runner has.
	ClaimJob(ctx context.Context, arg ClaimJobParams) (PipelineJob, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (uuid.UUID, error)
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (uuid.UUID, error)
	CountActiveTargetDeployments(ctx context.Context, targetID *uuid.UUID) (int64, error)
	CountApprovals(ctx context.Context, jobID uuid.UUID) (int64, error)
	CountEnvironments(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountIdentities(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountRunningJobs(ctx context.Context, runnerID *uuid.UUID) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (InfraAsset, error)
	// The id is chosen by the caller: it is the associated data of the credentials' encryption.
	CreateDeployTargetWithID(ctx context.Context, arg CreateDeployTargetWithIDParams) (DeployTarget, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (RunnerRegistrationToken, error)
	CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// The latest attempt of every job in a run.
	CurrentJobs(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error)
	DeleteAsset(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCertificate(ctx context.Context, assetID uuid.UUID) error
	DeleteDeployTarget(ctx context.Context, id uuid.UUID) (int64, error)
	// Periodic cleanup. Sessions are kept 30 days after expiry/revocation for the security page history.
	DeleteExpiredAuthRecords(ctx context.Context) error
	// Periodic cleanup: expired idempotency keys and webhook deliveries older than 30 days.
	DeleteExpiredHousekeeping(ctx context.Context) error
	DeleteExpiredJobTokens(ctx context.Context) (int64, error)
	DeleteExpiredRegistrationTokens(ctx context.Context) (int64, error)
	DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (UserIdentity, error)
	DeleteOldHourlyMetrics(ctx context.Context, before time.Time) (int64, error)
	DeleteProjectGrantsForTeam(ctx context.Context, teamID uuid.UUID) error
	// Called when someone leaves or is removed from an organization.
	DeleteProjectGrantsForUserInOrg(ctx context.Context, arg DeleteProjectGrantsForUserInOrgParams) error
	DeleteProjectTeamGrant(ctx context.Context, arg DeleteProjectTeamGrantParams) (int64, error)
	DeleteProjectUserGrant(ctx context.Context, arg DeleteProjectUserGrantParams) (int64, error)
	DeleteProtectionRule(ctx context.Context, environmentID uuid.UUID) error
	DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error
	DeleteRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error)
	DeleteRunner(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSchedulesExcept(ctx context.Context, arg DeleteSchedulesExceptParams) error
	// Artifacts of the latest successful attempt of each named job in a run.
	DependencyArtifacts(ctx context.Context, arg DependencyArtifactsParams) ([]DependencyArtifactsRow, error)
	DeploymentByJob(ctx context.Context, jobID *uuid.UUID) (Deployment, error)
	DisableTOTP(ctx context.Context, id uuid.UUID) error
	// Domain assets whose certificate is due for a check (or was never checked).
	DueCertificateChecks(ctx context.Context) ([]DueCertificateChecksRow, error)
	DueSchedules(ctx context.Context) ([]PipelineSchedule, error)
	EnableTOTP(ctx context.Context, arg EnableTOTPParams) error
	// Removes the least recently used entries beyond a project's quota.
	EvictCache(ctx context.Context, quotaBytes int64) ([]string, error)
	ExpiredArtifacts(ctx context.Context) ([]string, error)
	ExpiredRunningJobs(ctx context.Context) ([]ExpiredRunningJobsRow, error)
	FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error)
	// Steps still pending or running when a job ends.
	FinishOpenSteps(ctx context.Context, arg FinishOpenStepsParams) error
	GetActiveAPITokenByHash(ctx context.Context, tokenHash []byte) (GetActiveAPITokenByHashRow, error)
	GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetAsset(ctx context.Context, id uuid.UUID) (InfraAsset, error)
	GetAssetByAgentToken(ctx context.Context, tokenHash []byte) (InfraAsset, error)
	GetCacheEntry(ctx context.Context, arg GetCacheEntryParams) (CacheEntry, error)
	GetCertificate(ctx context.Context, assetID uuid.UUID) (SslCertificate, error)
	GetCurrentDeployment(ctx context.Context, environmentID uuid.UUID) (Deployment, error)
	GetDeployTarget(ctx context.Context, id uuid.UUID) (DeployTarget, error)
	GetDeployTargetByName(ctx context.Context, arg GetDeployTargetByNameParams) (DeployTarget, error)
	GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error)
	GetDeploymentDetail(ctx context.Context, id uuid.UUID) (GetDeploymentDetailRow, error)
	GetEnvironment(ctx context.Context, id uuid.UUID) (GetEnvironmentRow, error)
	GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (GetEnvironmentByNameRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error)
	GetInvitationByTokenForUpdate(ctx context.Context, tokenHash []byte) (GetInvitationByTokenForUpdateRow, error)
	GetJob(ctx context.Context, id uuid.UUID) (PipelineJob, error)
	GetJobByToken(ctx context.Context, tokenHash []byte) (PipelineJob, error)
	GetMFAChallengeForUpdate(ctx context.Context, tokenHash []byte) (MfaChallenge, error)
	GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error)
	// The caller's role in a live organization (tenant check for every org-scoped request).
	GetMembership(ctx context.Context, arg GetMembershipParams) (MemberRole, error)
	// Used by sign-up when self-service registration is disabled: an open invitation for the
	// same address lets the invitee create an account.
	GetOpenInvitationEmailByToken(ctx context.Context, tokenHash []byte) (string, error)
	// Tenant-scoped read: returns no row unless the user is a member.
	GetOrganizationForMember(ctx context.Context, arg GetOrganizationForMemberParams) (GetOrganizationForMemberRow, error)
	// A project with the caller's organization role and project grants (docs/rbac.md); '' means
	// none. The member_role enum is declared owner → viewer, so min() is the most privileged role.
	GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error)
	GetProjectForPipeline(ctx context.Context, id uuid.UUID) (GetProjectForPipelineRow, error)
	GetProjectTeamGrant(ctx context.Context, arg GetProjectTeamGrantParams) (MemberRole, error)
	GetProjectUserGrant(ctx context.Context, arg GetProjectUserGrantParams) (MemberRole, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error)
	GetRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error)
	// Webhook receiver lookup: the repository and whether its project still exists.
	GetRepositoryForWebhook(ctx context.Context, arg GetRepositoryForWebhookParams) (Repository, error)
	GetRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	GetRunner(ctx context.Context, id uuid.UUID) (Runner, error)
	GetRunnerByTokenHash(ctx context.Context, tokenHash []byte) (Runner, error)
	GetSchedule(ctx context.Context, id uuid.UUID) (PipelineSchedule, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamInOrg(ctx context.Context, arg GetTeamInOrgParams) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error)
	// The same from hourly rollups (for ranges beyond the raw retention); -1 = no data.
	HourlyMetricSeries(ctx context.Context, arg HourlyMetricSeriesParams) ([]HourlyMetricSeriesRow, error)
	IncrementMFAAttempts(ctx context.Context, id uuid.UUID) error
	InsertApproval(ctx context.Context, arg InsertApprovalParams) (uuid.UUID, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertDeploymentLog(ctx context.Context, arg InsertDeploymentLogParams) (int64, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (PipelineJob, error)
	InsertLogChunk(ctx context.Context, arg InsertLogChunkParams) (int64, error)
	// One sample per asset and second; a re-sent heartbeat within the same second is ignored.
	InsertMetric(ctx context.Context, arg InsertMetricParams) error
	InsertRecoveryCodes(ctx context.Context, arg []InsertRecoveryCodesParams) (int64, error)
	InsertRepository(ctx context.Context, arg InsertRepositoryParams) (Repository, error)
	InsertRun(ctx context.Context, arg InsertRunParams) (PipelineRun, error)
	InsertStep(ctx context.Context, arg InsertStepParams) error
	// Returns no row when a valid delivery with the same id was already recorded (a redelivery).
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (uuid.UUID, error)
	InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) error
	LinkRegistrationToken(ctx context.Context, arg LinkRegistrationTokenParams) error
	ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error)
	// Keyset pagination (newest first).
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]Session, error)
	ListApprovals(ctx context.Context, jobID uuid.UUID) ([]ListApprovalsRow, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error)
	// Keyset pagination on (created_at, id) newest first.
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error)
	// Certificates of the organization's domains, soonest expiry first; expiring_before (optional)
	// keeps those expiring earlier or failing.
	ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error)
	ListDeployTargets(ctx context.Context, organizationID uuid.UUID) ([]DeployTarget, error)
	ListDeploymentLogs(ctx context.Context, arg ListDeploymentLogsParams) ([]ListDeploymentLogsRow, error)
	// Newest first; keyset pagination on (created_at, id).
	ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error)
	// Ordered development, staging, production, then by name.
	ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentsRow, error)
	ListIdentities(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error)
	ListJobArtifacts(ctx context.Context, jobID uuid.UUID) ([]Artifact, error)
	ListJobAttempts(ctx context.Context, arg ListJobAttemptsParams) ([]PipelineJob, error)
	ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]ListLogChunksRow, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListOpenInvitations(ctx context.Context, arg ListOpenInvitationsParams) ([]ListOpenInvitationsRow, error)
	// Organization Owners and Admins, who inherit that role on every project.
	ListOrgManagers(ctx context.Context, organizationID uuid.UUID) ([]ListOrgManagersRow, error)
	ListProjectTeamGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectTeamGrantsRow, error)
	ListProjectUserGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectUserGrantsRow, error)
	// Projects the caller can see: all of them when their organization role inherits a project
	// role (owner/admin/viewer), otherwise those granted directly or through a team.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRunners(ctx context.Context, organizationID uuid.UUID) ([]ListRunnersRow, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error)
	ListSchedules(ctx context.Context, projectID uuid.UUID) ([]PipelineSchedule, error)
	ListSteps(ctx context.Context, jobID uuid.UUID) ([]JobStep, error)
	ListStepsForJobs(ctx context.Context, jobIds []uuid.UUID) ([]JobStep, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	ListUserOrganizations(ctx context.Context, arg ListUserOrganizationsParams) ([]ListUserOrganizationsRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	// Serializes membership changes (last-owner checks) within one organization.
	LockOrganization(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	// Serializes job claims per runner so max_concurrency holds under concurrent requests.
	LockRunner(ctx context.Context, id uuid.UUID) (Runner, error)
	// Running jobs whose runner stopped sending heartbeats.
	LostRunnerJobs(ctx context.Context, staleSeconds int32) ([]uuid.UUID, error)
	MaintainMetricPartitions(ctx context.Context, keepMonths int32) error
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	NextDeploymentNumber(ctx context.Context, id uuid.UUID) (int32, error)
	NextJobLogSeq(ctx context.Context, jobID uuid.UUID) (int32, error)
	// Serializes run creation per project (row lock on the project).
	NextRunNumber(ctx context.Context, id uuid.UUID) (int32, error)
	// Running jobs assigned to a runner that it no longer reports (the agent restarted, or
	// never received the assignment). The grace period covers a claim racing a heartbeat.
	OrphanedRunnerJobs(ctx context.Context, arg OrphanedRunnerJobsParams) ([]uuid.UUID, error)
	// The latest successful deployment of the environment before the given time.
	PreviousSuccessfulDeployment(ctx context.Context, arg PreviousSuccessfulDeploymentParams) (Deployment, error)
	// Averages and maxima per step (seconds) from the raw samples; -1 = no data in the bucket.
	RawMetricSeries(ctx context.Context, arg RawMetricSeriesParams) ([]RawMetricSeriesRow, error)
	// Guards against creating a second run for the same event when a worker is retried.
	RecentRunExists(ctx context.Context, arg RecentRunExistsParams) (bool, error)
	RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) error
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error
	RecordLoginSuccess(ctx context.Context, id uuid.UUID) error
	RecordTargetTest(ctx context.Context, arg RecordTargetTestParams) error
	// The request failed with a server error: forget the key so the client can retry.
	ReleaseIdempotencyKey(ctx context.Context, id uuid.UUID) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	RemoveUserFromOrgTeams(ctx context.Context, arg RemoveUserFromOrgTeamsParams) error
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (uuid.UUID, error)
	RevokeInvitation(ctx context.Context, id uuid.UUID) error
	RevokeOpenInvitationForEmail(ctx context.Context, arg RevokeOpenInvitationForEmailParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (uuid.UUID, error)
	// Revokes every session of a user, optionally keeping one (the caller's).
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error
	// Summarizes raw samples of whole hours in [from, to) into hourly rows (idempotent).
	RollupMetrics(ctx context.Context, arg RollupMetricsParams) (int64, error)
	RunningJobsForRunner(ctx context.Context, runnerID *uuid.UUID) ([]uuid.UUID, error)
	SetAgentToken(ctx context.Context, arg SetAgentTokenParams) (InfraAsset, error)
	SetCurrentDeployment(ctx context.Context, arg SetCurrentDeploymentParams) error
	SetJobStatus(ctx context.Context, arg SetJobStatusParams) error
	SetTOTPPending(ctx context.Context, arg SetTOTPPendingParams) error
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteEnvironment(ctx context.Context, id uuid.UUID) error
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteTeam(ctx context.Context, id uuid.UUID) error
	StaleQueuedJobs(ctx context.Context) ([]StaleQueuedJobsRow, error)
	StartDeployment(ctx context.Context, id uuid.UUID) (Deployment, error)
	StartJob(ctx context.Context, arg StartJobParams) error
	// Throttled to one write per minute per token.
	TouchAPIToken(ctx context.Context, id uuid.UUID) error
	TouchRepositoryDelivery(ctx context.Context, id uuid.UUID) error
	TouchRunner(ctx context.Context, arg TouchRunnerParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InfraAsset, error)
	UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (DeployTarget, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRepositoryDefaultBranch(ctx context.Context, arg UpdateRepositoryDefaultBranchParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateRunner(ctx context.Context, arg UpdateRunnerParams) (Runner, error)
	UpdateStep(ctx context.Context, arg UpdateStepParams) (int64, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	// Optimistic locking: no row is returned when the version does not match.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Returns the replaced blob's key (if any) so the caller can delete it.
	UpsertCacheEntry(ctx context.Context, arg UpsertCacheEntryParams) (string, error)
	UpsertCertificate(ctx context.Context, arg UpsertCertificateParams) (SslCertificate, error)
	UpsertJobToken(ctx context.Context, arg UpsertJobTokenParams) error
	UpsertProjectTeamGrant(ctx context.Context, arg UpsertProjectTeamGrantParams) error
	UpsertProjectUserGrant(ctx context.Context, arg UpsertProjectUserGrantParams) error
	UpsertProtectionRule(ctx context.Context, arg UpsertProtectionRuleParams) error
	UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error
	UseMFAChallenge(ctx context.Context, id uuid.UUID) error
	// Consumes an unused, unexpired token (one-time).
	UseRegistrationToken(ctx context.Context, tokenHash []byte) (RunnerRegistrationToken, error)
}

var _ Querier = (*Queries)(nil)
