// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// A user's own account events (sign-ins, 2FA, password, tokens, sessions): entries without
	// an organization that the user did or that are about the user. Newest first, keyset paging.
	AccountActivity(ctx context.Context, arg AccountActivityParams) ([]AccountActivityRow, error)
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	ActiveSilences(ctx context.Context, organizationID uuid.UUID) ([]Silence, error)
	AddDeploymentLogBytes(ctx context.Context, arg AddDeploymentLogBytesParams) error
	AddLogBytes(ctx context.Context, arg AddLogBytesParams) (int64, error)
	AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error
	AdvanceAlertStep(ctx context.Context, arg AdvanceAlertStepParams) error
	AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error
	// Accepts a TOTP time step only once (replay protection); returns no row if already used.
	AdvanceTOTPStep(ctx context.Context, arg AdvanceTOTPStepParams) (uuid.UUID, error)
	// Alerts that stopped firing in the range (organization-wide; alerts aren't tied to
	// projects): how many, and the median time from firing to resolved.
	AlertRestores(ctx context.Context, arg AlertRestoresParams) (AlertRestoresRow, error)
	// Names of infrastructure assets mentioned by audit entries.
	AuditAssetNames(ctx context.Context, ids []uuid.UUID) ([]AuditAssetNamesRow, error)
	// Names of teams mentioned by audit entries (deleted teams included).
	AuditTeamNames(ctx context.Context, ids []uuid.UUID) ([]AuditTeamNamesRow, error)
	// Names of users mentioned by audit entries.
	AuditUserNames(ctx context.Context, ids []uuid.UUID) ([]AuditUserNamesRow, error)
	// Rotation: the next value version, also a new ETag version.
	BumpSecretVersion(ctx context.Context, arg BumpSecretVersionParams) (Secret, error)
	// Takes due monitors and schedules their next check, so concurrent workers never run the
	// same check twice.
	ClaimDueMonitors(ctx context.Context, maxMonitors int32) ([]Monitor, error)
	// Inserts an in-flight record (or takes over an expired one); returns no row when a live
	// record already exists for this user and key.
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error)
	// Oldest queued runner job of the organization whose required labels the runner has.
	ClaimJob(ctx context.Context, arg ClaimJobParams) (PipelineJob, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (uuid.UUID, error)
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (uuid.UUID, error)
	CountActiveTargetDeployments(ctx context.Context, targetID *uuid.UUID) (int64, error)
	CountApprovals(ctx context.Context, jobID uuid.UUID) (int64, error)
	CountEnvironments(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountIdentities(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOwners(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountRunningJobs(ctx context.Context, runnerID *uuid.UUID) (int64, error)
	CountSecrets(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error)
	CreateAsset(ctx context.Context, arg CreateAssetParams) (InfraAsset, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (NotificationChannel, error)
	// The id is chosen by the caller: it is the associated data of the credentials' encryption.
	CreateDeployTargetWithID(ctx context.Context, arg CreateDeployTargetWithIDParams) (DeployTarget, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) error
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error)
	CreateIngestToken(ctx context.Context, arg CreateIngestTokenParams) (LogIngestToken, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) error
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (RunnerRegistrationToken, error)
	CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Without starts_at the silence starts at the database's now(), the clock that decides whether
	// it is active (the API server's clock may differ).
	CreateSilence(ctx context.Context, arg CreateSilenceParams) (Silence, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// The latest attempt of every job in a run.
	CurrentJobs(ctx context.Context, runID uuid.UUID) ([]PipelineJob, error)
	DeleteAlertRule(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteAsset(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCertificate(ctx context.Context, assetID uuid.UUID) error
	DeleteChannel(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteDeployTarget(ctx context.Context, id uuid.UUID) (int64, error)
	// Periodic cleanup. Sessions are kept 30 days after expiry/revocation for the security page history.
	DeleteExpiredAuthRecords(ctx context.Context) error
	// Periodic cleanup: expired idempotency keys and webhook deliveries older than 30 days.
	DeleteExpiredHousekeeping(ctx context.Context) error
	DeleteExpiredJobTokens(ctx context.Context) (int64, error)
	DeleteExpiredRegistrationTokens(ctx context.Context) (int64, error)
	DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (UserIdentity, error)
	DeleteIngestToken(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteMonitor(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteOldHourlyMetrics(ctx context.Context, before time.Time) (int64, error)
	DeleteOldMonitorHourly(ctx context.Context, before time.Time) (int64, error)
	DeletePendingAlert(ctx context.Context, id uuid.UUID) error
	DeleteProjectGrantsForTeam(ctx context.Context, teamID uuid.UUID) error
	// Called when someone leaves or is removed from an organization.
	DeleteProjectGrantsForUserInOrg(ctx context.Context, arg DeleteProjectGrantsForUserInOrgParams) error
	DeleteProjectTeamGrant(ctx context.Context, arg DeleteProjectTeamGrantParams) (int64, error)
	DeleteProjectUserGrant(ctx context.Context, arg DeleteProjectUserGrantParams) (int64, error)
	DeleteProtectionRule(ctx context.Context, environmentID uuid.UUID) error
	DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error
	DeleteRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error)
	DeleteRunner(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteSchedulesExcept(ctx context.Context, arg DeleteSchedulesExceptParams) error
	// Artifacts of the latest successful attempt of each named job in a run.
	DependencyArtifacts(ctx context.Context, arg DependencyArtifactsParams) ([]DependencyArtifactsRow, error)
	DeploymentByJob(ctx context.Context, jobID *uuid.UUID) (Deployment, error)
	// Changes per day or week (bucket) in the time zone tz, oldest first, split into those that
	// succeeded and stayed, and those that failed or were rolled back later.
	DeploymentTrend(ctx context.Context, arg DeploymentTrendParams) ([]DeploymentTrendRow, error)
	// Destroys the values of every version below before_version (all of them when it is 0).
	DestroySecretValues(ctx context.Context, arg DestroySecretValuesParams) (int64, error)
	DisableTOTP(ctx context.Context, id uuid.UUID) error
	// Per project: changes, failed changes and median lead time, busiest first (at most 50).
	DoraByProject(ctx context.Context, arg DoraByProjectParams) ([]DoraByProjectRow, error)
	// Time to restore, per failed change: a failed deployment counts from its start until it was
	// reverted automatically or the next successful deployment to that environment finished; a
	// change rolled back later counts from when it went live until the next successful deployment
	// (normally the rollback). Changes not restored yet are counted as open.
	DoraRestores(ctx context.Context, arg DoraRestoresParams) (DoraRestoresRow, error)
	// Changes are finished deployments started in the range to production environments (or to
	// environment_id), not counting rollbacks. A change failed when it failed or was rolled back
	// later. Lead time runs from the commit (or, without one, the run's creation) to the finished
	// deployment of a successful change made by a pipeline.
	DoraSummary(ctx context.Context, arg DoraSummaryParams) (DoraSummaryRow, error)
	// Domain assets whose certificate is due for a check (or was never checked).
	DueCertificateChecks(ctx context.Context) ([]DueCertificateChecksRow, error)
	// Firing, unacknowledged alerts whose next escalation step is due.
	DueEscalations(ctx context.Context, maxAlerts int32) ([]Alert, error)
	DueSchedules(ctx context.Context) ([]PipelineSchedule, error)
	EnableTOTP(ctx context.Context, arg EnableTOTPParams) error
	EnabledAlertRules(ctx context.Context) ([]AlertRule, error)
	EvalCertificates(ctx context.Context, organizationID uuid.UUID) ([]EvalCertificatesRow, error)
	EvalMonitors(ctx context.Context, organizationID uuid.UUID) ([]EvalMonitorsRow, error)
	EvalServers(ctx context.Context, organizationID uuid.UUID) ([]EvalServersRow, error)
	// Removes the least recently used entries beyond a project's quota.
	EvictCache(ctx context.Context, quotaBytes int64) ([]string, error)
	ExpireSilence(ctx context.Context, id uuid.UUID) (Silence, error)
	ExpiredArtifacts(ctx context.Context) ([]string, error)
	ExpiredRunningJobs(ctx context.Context) ([]ExpiredRunningJobsRow, error)
	FinishDeployment(ctx context.Context, arg FinishDeploymentParams) (Deployment, error)
	// Steps still pending or running when a job ends.
	FinishOpenSteps(ctx context.Context, arg FinishOpenStepsParams) error
	FireAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	GetActiveAPITokenByHash(ctx context.Context, tokenHash []byte) (GetActiveAPITokenByHashRow, error)
	GetAlert(ctx context.Context, id uuid.UUID) (GetAlertRow, error)
	GetAlertRule(ctx context.Context, id uuid.UUID) (AlertRule, error)
	GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetAsset(ctx context.Context, id uuid.UUID) (InfraAsset, error)
	GetAssetByAgentToken(ctx context.Context, tokenHash []byte) (InfraAsset, error)
	GetCacheEntry(ctx context.Context, arg GetCacheEntryParams) (CacheEntry, error)
	GetCertificate(ctx context.Context, assetID uuid.UUID) (SslCertificate, error)
	GetChannel(ctx context.Context, id uuid.UUID) (NotificationChannel, error)
	GetCurrentDeployment(ctx context.Context, environmentID uuid.UUID) (Deployment, error)
	GetDeployTarget(ctx context.Context, id uuid.UUID) (DeployTarget, error)
	GetDeployTargetByName(ctx context.Context, arg GetDeployTargetByNameParams) (DeployTarget, error)
	GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error)
	GetDeploymentDetail(ctx context.Context, id uuid.UUID) (GetDeploymentDetailRow, error)
	GetEnvironment(ctx context.Context, id uuid.UUID) (GetEnvironmentRow, error)
	GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (GetEnvironmentByNameRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetIngestToken(ctx context.Context, id uuid.UUID) (LogIngestToken, error)
	GetIngestTokenByHash(ctx context.Context, tokenHash []byte) (LogIngestToken, error)
	GetInvitation(ctx context.Context, id uuid.UUID) (Invitation, error)
	GetInvitationByTokenForUpdate(ctx context.Context, tokenHash []byte) (GetInvitationByTokenForUpdateRow, error)
	GetJob(ctx context.Context, id uuid.UUID) (PipelineJob, error)
	GetJobByToken(ctx context.Context, tokenHash []byte) (PipelineJob, error)
	GetJobMasks(ctx context.Context, jobID uuid.UUID) ([]byte, error)
	GetMFAChallengeForUpdate(ctx context.Context, tokenHash []byte) (MfaChallenge, error)
	GetMember(ctx context.Context, arg GetMemberParams) (GetMemberRow, error)
	// The caller's role in a live organization (tenant check for every org-scoped request).
	GetMembership(ctx context.Context, arg GetMembershipParams) (MemberRole, error)
	GetMonitor(ctx context.Context, id uuid.UUID) (Monitor, error)
	// Used by sign-up when self-service registration is disabled: an open invitation for the
	// same address lets the invitee create an account.
	GetOpenInvitationEmailByToken(ctx context.Context, tokenHash []byte) (string, error)
	GetOrgSlugName(ctx context.Context, id uuid.UUID) (GetOrgSlugNameRow, error)
	// Tenant-scoped read: returns no row unless the user is a member.
	GetOrganizationForMember(ctx context.Context, arg GetOrganizationForMemberParams) (GetOrganizationForMemberRow, error)
	// A project with the caller's organization role and project grants (docs/rbac.md); '' means
	// none. The member_role enum is declared owner → viewer, so min() is the most privileged role.
	GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error)
	GetProjectForPipeline(ctx context.Context, id uuid.UUID) (GetProjectForPipelineRow, error)
	GetProjectTeamGrant(ctx context.Context, arg GetProjectTeamGrantParams) (MemberRole, error)
	GetProjectUserGrant(ctx context.Context, arg GetProjectUserGrantParams) (MemberRole, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error)
	GetRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error)
	// Webhook receiver lookup: the repository and whether its project still exists.
	GetRepositoryForWebhook(ctx context.Context, arg GetRepositoryForWebhookParams) (Repository, error)
	GetRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	GetRunner(ctx context.Context, id uuid.UUID) (Runner, error)
	GetRunnerByTokenHash(ctx context.Context, tokenHash []byte) (Runner, error)
	GetSchedule(ctx context.Context, id uuid.UUID) (PipelineSchedule, error)
	// A live secret with its scope; environments deleted since hide their secrets.
	GetSecret(ctx context.Context, id uuid.UUID) (GetSecretRow, error)
	GetSilence(ctx context.Context, id uuid.UUID) (Silence, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamInOrg(ctx context.Context, arg GetTeamInOrgParams) (Team, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIDForUpdate(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error)
	// The same from hourly rollups (for ranges beyond the raw retention); -1 = no data.
	HourlyMetricSeries(ctx context.Context, arg HourlyMetricSeriesParams) ([]HourlyMetricSeriesRow, error)
	HourlyMonitorSeries(ctx context.Context, arg HourlyMonitorSeriesParams) ([]HourlyMonitorSeriesRow, error)
	IncrementMFAAttempts(ctx context.Context, id uuid.UUID) error
	InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) error
	InsertApproval(ctx context.Context, arg InsertApprovalParams) (uuid.UUID, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertDeploymentLog(ctx context.Context, arg InsertDeploymentLogParams) (int64, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (PipelineJob, error)
	InsertLogChunk(ctx context.Context, arg InsertLogChunkParams) (int64, error)
	// One sample per asset and second; a re-sent heartbeat within the same second is ignored.
	InsertMetric(ctx context.Context, arg InsertMetricParams) error
	InsertMonitorResult(ctx context.Context, arg InsertMonitorResultParams) error
	InsertPendingAlert(ctx context.Context, arg InsertPendingAlertParams) (Alert, error)
	InsertRecoveryCodes(ctx context.Context, arg []InsertRecoveryCodesParams) (int64, error)
	InsertRepository(ctx context.Context, arg InsertRepositoryParams) (Repository, error)
	InsertRun(ctx context.Context, arg InsertRunParams) (PipelineRun, error)
	InsertSecretVersion(ctx context.Context, arg InsertSecretVersionParams) error
	// One ingest batch for a token's service. The arrays have one element per line (set-returning
	// functions in a select list advance together).
	InsertServiceLogs(ctx context.Context, arg InsertServiceLogsParams) (int64, error)
	InsertStep(ctx context.Context, arg InsertStepParams) error
	// Returns no row when a valid delivery with the same id was already recorded (a redelivery).
	InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (uuid.UUID, error)
	InvalidateEmailTokens(ctx context.Context, arg InvalidateEmailTokensParams) error
	// The subset of names a job can be given (no decryption: used when the job becomes ready).
	JobSecretNames(ctx context.Context, arg JobSecretNamesParams) ([]string, error)
	LastAlertEventKind(ctx context.Context, alertID uuid.UUID) (string, error)
	LinkRegistrationToken(ctx context.Context, arg LinkRegistrationTokenParams) error
	ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ApiToken, error)
	// Keyset pagination (newest first).
	ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]Session, error)
	ListAlertEvents(ctx context.Context, alertID uuid.UUID) ([]ListAlertEventsRow, error)
	ListAlertRules(ctx context.Context, organizationID uuid.UUID) ([]ListAlertRulesRow, error)
	// Firing and resolved alerts, newest first (pending ones aren't alerts yet).
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error)
	ListApprovals(ctx context.Context, jobID uuid.UUID) ([]ListApprovalsRow, error)
	ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error)
	// Certificates of the organization's domains, soonest expiry first; expiring_before (optional)
	// keeps those expiring earlier or failing.
	ListCertificates(ctx context.Context, arg ListCertificatesParams) ([]ListCertificatesRow, error)
	ListChannels(ctx context.Context, organizationID uuid.UUID) ([]NotificationChannel, error)
	ListDeployTargets(ctx context.Context, organizationID uuid.UUID) ([]DeployTarget, error)
	ListDeploymentLogs(ctx context.Context, arg ListDeploymentLogsParams) ([]ListDeploymentLogsRow, error)
	// Newest first; keyset pagination on (created_at, id).
	ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error)
	// Ordered development, staging, production, then by name.
	ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]ListEnvironmentsRow, error)
	ListIdentities(ctx context.Context, userID uuid.UUID) ([]UserIdentity, error)
	ListIngestTokens(ctx context.Context, organizationID uuid.UUID) ([]ListIngestTokensRow, error)
	ListJobArtifacts(ctx context.Context, jobID uuid.UUID) ([]Artifact, error)
	ListJobAttempts(ctx context.Context, arg ListJobAttemptsParams) ([]PipelineJob, error)
	ListLogChunks(ctx context.Context, arg ListLogChunksParams) ([]ListLogChunksRow, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListMonitors(ctx context.Context, arg ListMonitorsParams) ([]Monitor, error)
	ListOpenInvitations(ctx context.Context, arg ListOpenInvitationsParams) ([]ListOpenInvitationsRow, error)
	// Organization Owners and Admins, who inherit that role on every project.
	ListOrgManagers(ctx context.Context, organizationID uuid.UUID) ([]ListOrgManagersRow, error)
	ListProjectTeamGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectTeamGrantsRow, error)
	ListProjectUserGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectUserGrantsRow, error)
	// Projects the caller can see: all of them when their organization role inherits a project
	// role (owner/admin/viewer), otherwise those granted directly or through a team.
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListRunners(ctx context.Context, organizationID uuid.UUID) ([]ListRunnersRow, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]ListRunsRow, error)
	ListSchedules(ctx context.Context, projectID uuid.UUID) ([]PipelineSchedule, error)
	ListSecretVersions(ctx context.Context, secretID uuid.UUID) ([]ListSecretVersionsRow, error)
	// Project-wide first, then by environment and name. project_wide = true lists only
	// project-wide secrets; environment_id lists only that environment's.
	ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error)
	// Active and upcoming silences, then (with include_expired) the last 100 expired ones.
	ListSilences(ctx context.Context, arg ListSilencesParams) ([]ListSilencesRow, error)
	ListSteps(ctx context.Context, jobID uuid.UUID) ([]JobStep, error)
	ListStepsForJobs(ctx context.Context, jobIds []uuid.UUID) ([]JobStep, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error)
	ListUserOrganizations(ctx context.Context, arg ListUserOrganizationsParams) ([]ListUserOrganizationsRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	// Serializes membership changes (last-owner checks) within one organization.
	LockOrganization(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockRun(ctx context.Context, id uuid.UUID) (PipelineRun, error)
	// Serializes job claims per runner so max_concurrency holds under concurrent requests.
	LockRunner(ctx context.Context, id uuid.UUID) (Runner, error)
	// Running jobs whose runner stopped sending heartbeats.
	LostRunnerJobs(ctx context.Context, staleSeconds int32) ([]uuid.UUID, error)
	MaintainLogPartitions(ctx context.Context, keepDays int32) error
	MaintainMetricPartitions(ctx context.Context, keepMonths int32) error
	MaintainMonitorPartitions(ctx context.Context, keepMonths int32) error
	MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) error
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	// The language of each address that belongs to a member of the organization.
	MemberLocalesByEmail(ctx context.Context, arg MemberLocalesByEmailParams) ([]MemberLocalesByEmailRow, error)
	MonitorUptime24h(ctx context.Context, organizationID uuid.UUID) ([]MonitorUptime24hRow, error)
	NextDeploymentNumber(ctx context.Context, id uuid.UUID) (int32, error)
	NextJobLogSeq(ctx context.Context, jobID uuid.UUID) (int32, error)
	// Serializes run creation per project (row lock on the project).
	NextRunNumber(ctx context.Context, id uuid.UUID) (int32, error)
	// Channels that received this alert's firing message (they also get the resolution).
	NotifiedChannelIDs(ctx context.Context, alertID uuid.UUID) ([]uuid.UUID, error)
	OpenAlertsForRule(ctx context.Context, ruleID *uuid.UUID) ([]Alert, error)
	OrgChannelIDs(ctx context.Context, arg OrgChannelIDsParams) ([]uuid.UUID, error)
	// Running jobs assigned to a runner that it no longer reports (the agent restarted, or
	// never received the assignment). The grace period covers a claim racing a heartbeat.
	OrphanedRunnerJobs(ctx context.Context, arg OrphanedRunnerJobsParams) ([]uuid.UUID, error)
	// Per project, busiest first (at most 50), with its latest run in the range.
	PipelineByProject(ctx context.Context, arg PipelineByProjectParams) ([]PipelineByProjectRow, error)
	// Dashboard (Module 12): pipeline statistics and DORA metrics, computed on request.
	// Every query takes the organization, the caller's project visibility (see_all or the
	// visible project_ids), an optional project, and the range [from_ts, to_ts).
	// Durations are in seconds; medians and p95 are -1 when there is nothing to measure.
	// Runs created in the range. Success rate and durations use finished runs.
	PipelineSummary(ctx context.Context, arg PipelineSummaryParams) (PipelineSummaryRow, error)
	// Runs per day or week (bucket) in the time zone tz, oldest first.
	PipelineTrend(ctx context.Context, arg PipelineTrendParams) ([]PipelineTrendRow, error)
	// The latest successful deployment of the environment before the given time.
	PreviousSuccessfulDeployment(ctx context.Context, arg PreviousSuccessfulDeploymentParams) (Deployment, error)
	// Averages and maxima per step (seconds) from the raw samples; -1 = no data in the bucket.
	RawMetricSeries(ctx context.Context, arg RawMetricSeriesParams) ([]RawMetricSeriesRow, error)
	// Buckets of step_seconds; latency is averaged over successful checks. -1 = no value.
	RawMonitorSeries(ctx context.Context, arg RawMonitorSeriesParams) ([]RawMonitorSeriesRow, error)
	// Service names seen in the last day, for the filter.
	RecentLogServices(ctx context.Context, arg RecentLogServicesParams) ([]string, error)
	RecentMonitorResults(ctx context.Context, arg RecentMonitorResultsParams) ([]RecentMonitorResultsRow, error)
	// Guards against creating a second run for the same event when a worker is retried.
	RecentRunExists(ctx context.Context, arg RecentRunExistsParams) (bool, error)
	RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) error
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error
	RecordLoginSuccess(ctx context.Context, id uuid.UUID) error
	RecordTargetTest(ctx context.Context, arg RecordTargetTestParams) error
	// The request failed with a server error: forget the key so the client can retry.
	ReleaseIdempotencyKey(ctx context.Context, id uuid.UUID) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	RemoveUserFromOrgTeams(ctx context.Context, arg RemoveUserFromOrgTeamsParams) error
	ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	// The live secrets a job may receive, by name: the job's environment's secret wins over a
	// project-wide one of the same name. environment_id NULL = a job without an environment.
	ResolveJobSecrets(ctx context.Context, arg ResolveJobSecretsParams) ([]ResolveJobSecretsRow, error)
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (uuid.UUID, error)
	RevokeInvitation(ctx context.Context, id uuid.UUID) error
	RevokeOpenInvitationForEmail(ctx context.Context, arg RevokeOpenInvitationForEmailParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (uuid.UUID, error)
	// Revokes every session of a user, optionally keeping one (the caller's).
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error
	// Summarizes raw samples of whole hours in [from, to) into hourly rows (idempotent).
	RollupMetrics(ctx context.Context, arg RollupMetricsParams) (int64, error)
	// Rolls up the whole hours in [from_ts, to_ts); re-running replaces them.
	RollupMonitorResults(ctx context.Context, arg RollupMonitorResultsParams) error
	// Names of the rules whose escalation notifies the channel.
	RulesUsingChannel(ctx context.Context, arg RulesUsingChannelParams) ([]string, error)
	RunningJobsForRunner(ctx context.Context, runnerID *uuid.UUID) ([]uuid.UUID, error)
	// An organization's entries, newest first, with the actor, the project and (for user and
	// member resources) the user named by resource_id. Filters: areas (the action's part before
	// the dot) or exact actions, actor, project, resource, and [from_ts, to_ts). Keyset paging on
	// (created_at, id).
	SearchAuditLog(ctx context.Context, arg SearchAuditLogParams) ([]SearchAuditLogRow, error)
	// Newest first within [from_ts, to_ts). Job and deployment lines only for the given projects
	// (see_all: every project). fts: a full-text query; contains: a plain substring (for text
	// without spaces between words, such as Khmer). before_* pages backwards, after_* fetches
	// only newer lines (follow mode).
	SearchLogs(ctx context.Context, arg SearchLogsParams) ([]SearchLogsRow, error)
	SetAgentToken(ctx context.Context, arg SetAgentTokenParams) (InfraAsset, error)
	SetChannelTest(ctx context.Context, arg SetChannelTestParams) error
	SetCurrentDeployment(ctx context.Context, arg SetCurrentDeploymentParams) error
	SetJobStatus(ctx context.Context, arg SetJobStatusParams) error
	SetMonitorState(ctx context.Context, arg SetMonitorStateParams) error
	SetTOTPPending(ctx context.Context, arg SetTOTPPendingParams) error
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) error
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteEnvironment(ctx context.Context, id uuid.UUID) error
	SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (int64, error)
	SoftDeleteTeam(ctx context.Context, id uuid.UUID) error
	StaleQueuedJobs(ctx context.Context) ([]StaleQueuedJobsRow, error)
	StartDeployment(ctx context.Context, id uuid.UUID) (Deployment, error)
	StartJob(ctx context.Context, arg StartJobParams) error
	// Throttled to one write per minute per token.
	TouchAPIToken(ctx context.Context, id uuid.UUID) error
	TouchIngestToken(ctx context.Context, id uuid.UUID) error
	TouchRepositoryDelivery(ctx context.Context, id uuid.UUID) error
	TouchRunner(ctx context.Context, arg TouchRunnerParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateAlertObservation(ctx context.Context, arg UpdateAlertObservationParams) error
	UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (InfraAsset, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (NotificationChannel, error)
	UpdateDeployTarget(ctx context.Context, arg UpdateDeployTargetParams) (DeployTarget, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	// Edits check again right away and forget the old state when what is checked changed.
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateRepositoryDefaultBranch(ctx context.Context, arg UpdateRepositoryDefaultBranchParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateRunner(ctx context.Context, arg UpdateRunnerParams) (Runner, error)
	UpdateSecretDescription(ctx context.Context, arg UpdateSecretDescriptionParams) (Secret, error)
	UpdateStep(ctx context.Context, arg UpdateStepParams) (int64, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	// Optimistic locking: no row is returned when the version does not match.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Returns the replaced blob's key (if any) so the caller can delete it.
	UpsertCacheEntry(ctx context.Context, arg UpsertCacheEntryParams) (string, error)
	UpsertCertificate(ctx context.Context, arg UpsertCertificateParams) (SslCertificate, error)
	UpsertJobToken(ctx context.Context, arg UpsertJobTokenParams) error
	UpsertProjectTeamGrant(ctx context.Context, arg UpsertProjectTeamGrantParams) error
	UpsertProjectUserGrant(ctx context.Context, arg UpsertProjectUserGrantParams) error
	UpsertProtectionRule(ctx context.Context, arg UpsertProtectionRuleParams) error
	UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error
	UseMFAChallenge(ctx context.Context, id uuid.UUID) error
	// Consumes an unused, unexpired token (one-time).
	UseRegistrationToken(ctx context.Context, tokenHash []byte) (RunnerRegistrationToken, error)
	// The projects a member can see (all of them when see_all).
	VisibleProjectIDs(ctx context.Context, arg VisibleProjectIDsParams) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
