// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRepositoryByProject = `-- name: DeleteRepositoryByProject :one
DELETE FROM repositories WHERE project_id = $1 RETURNING id, project_id, provider, base_url, full_name, external_id, web_url, clone_url, default_branch, access_token_enc, webhook_secret_enc, webhook_mode, webhook_id, connected_by, last_delivery_at, created_at, updated_at
`

func (q *Queries) DeleteRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, deleteRepositoryByProject, projectID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.BaseUrl,
		&i.FullName,
		&i.ExternalID,
		&i.WebUrl,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.AccessTokenEnc,
		&i.WebhookSecretEnc,
		&i.WebhookMode,
		&i.WebhookID,
		&i.ConnectedBy,
		&i.LastDeliveryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByProject = `-- name: GetRepositoryByProject :one
SELECT id, project_id, provider, base_url, full_name, external_id, web_url, clone_url, default_branch, access_token_enc, webhook_secret_enc, webhook_mode, webhook_id, connected_by, last_delivery_at, created_at, updated_at FROM repositories WHERE project_id = $1
`

func (q *Queries) GetRepositoryByProject(ctx context.Context, projectID uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByProject, projectID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.BaseUrl,
		&i.FullName,
		&i.ExternalID,
		&i.WebUrl,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.AccessTokenEnc,
		&i.WebhookSecretEnc,
		&i.WebhookMode,
		&i.WebhookID,
		&i.ConnectedBy,
		&i.LastDeliveryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryForWebhook = `-- name: GetRepositoryForWebhook :one
SELECT r.id, r.project_id, r.provider, r.base_url, r.full_name, r.external_id, r.web_url, r.clone_url, r.default_branch, r.access_token_enc, r.webhook_secret_enc, r.webhook_mode, r.webhook_id, r.connected_by, r.last_delivery_at, r.created_at, r.updated_at FROM repositories r
JOIN projects p ON p.id = r.project_id AND p.deleted_at IS NULL
WHERE r.id = $1 AND r.provider = $2
`

type GetRepositoryForWebhookParams struct {
	ID       uuid.UUID   `json:"id"`
	Provider GitProvider `json:"provider"`
}

// Webhook receiver lookup: the repository and whether its project still exists.
func (q *Queries) GetRepositoryForWebhook(ctx context.Context, arg GetRepositoryForWebhookParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryForWebhook, arg.ID, arg.Provider)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.BaseUrl,
		&i.FullName,
		&i.ExternalID,
		&i.WebUrl,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.AccessTokenEnc,
		&i.WebhookSecretEnc,
		&i.WebhookMode,
		&i.WebhookID,
		&i.ConnectedBy,
		&i.LastDeliveryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRepository = `-- name: InsertRepository :one
INSERT INTO repositories (
  id, project_id, provider, base_url, full_name, external_id, web_url, clone_url, default_branch,
  access_token_enc, webhook_secret_enc, webhook_mode, webhook_id, connected_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14
)
RETURNING id, project_id, provider, base_url, full_name, external_id, web_url, clone_url, default_branch, access_token_enc, webhook_secret_enc, webhook_mode, webhook_id, connected_by, last_delivery_at, created_at, updated_at
`

type InsertRepositoryParams struct {
	ID               uuid.UUID   `json:"id"`
	ProjectID        uuid.UUID   `json:"project_id"`
	Provider         GitProvider `json:"provider"`
	BaseUrl          *string     `json:"base_url"`
	FullName         string      `json:"full_name"`
	ExternalID       string      `json:"external_id"`
	WebUrl           string      `json:"web_url"`
	CloneUrl         string      `json:"clone_url"`
	DefaultBranch    string      `json:"default_branch"`
	AccessTokenEnc   []byte      `json:"access_token_enc"`
	WebhookSecretEnc []byte      `json:"webhook_secret_enc"`
	WebhookMode      WebhookMode `json:"webhook_mode"`
	WebhookID        *string     `json:"webhook_id"`
	ConnectedBy      *uuid.UUID  `json:"connected_by"`
}

func (q *Queries) InsertRepository(ctx context.Context, arg InsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, insertRepository,
		arg.ID,
		arg.ProjectID,
		arg.Provider,
		arg.BaseUrl,
		arg.FullName,
		arg.ExternalID,
		arg.WebUrl,
		arg.CloneUrl,
		arg.DefaultBranch,
		arg.AccessTokenEnc,
		arg.WebhookSecretEnc,
		arg.WebhookMode,
		arg.WebhookID,
		arg.ConnectedBy,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Provider,
		&i.BaseUrl,
		&i.FullName,
		&i.ExternalID,
		&i.WebUrl,
		&i.CloneUrl,
		&i.DefaultBranch,
		&i.AccessTokenEnc,
		&i.WebhookSecretEnc,
		&i.WebhookMode,
		&i.WebhookID,
		&i.ConnectedBy,
		&i.LastDeliveryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_deliveries (repository_id, delivery_id, event, ref, commit_sha, signature_valid, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (repository_id, delivery_id) WHERE signature_valid DO NOTHING
RETURNING id
`

type InsertWebhookDeliveryParams struct {
	RepositoryID   uuid.UUID `json:"repository_id"`
	DeliveryID     string    `json:"delivery_id"`
	Event          string    `json:"event"`
	Ref            string    `json:"ref"`
	CommitSha      string    `json:"commit_sha"`
	SignatureValid bool      `json:"signature_valid"`
	Payload        []byte    `json:"payload"`
}

// Returns no row when a valid delivery with the same id was already recorded (a redelivery).
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.RepositoryID,
		arg.DeliveryID,
		arg.Event,
		arg.Ref,
		arg.CommitSha,
		arg.SignatureValid,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, delivery_id, event, ref, commit_sha, signature_valid, received_at
FROM webhook_deliveries
WHERE repository_id = $1
  AND ($2::timestamptz IS NULL
       OR (received_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY received_at DESC, id DESC
LIMIT $4
`

type ListWebhookDeliveriesParams struct {
	RepositoryID uuid.UUID  `json:"repository_id"`
	CursorAt     *time.Time `json:"cursor_at"`
	CursorID     *uuid.UUID `json:"cursor_id"`
	PageSize     int32      `json:"page_size"`
}

type ListWebhookDeliveriesRow struct {
	ID             uuid.UUID `json:"id"`
	DeliveryID     string    `json:"delivery_id"`
	Event          string    `json:"event"`
	Ref            string    `json:"ref"`
	CommitSha      string    `json:"commit_sha"`
	SignatureValid bool      `json:"signature_valid"`
	ReceivedAt     time.Time `json:"received_at"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries,
		arg.RepositoryID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.Event,
			&i.Ref,
			&i.CommitSha,
			&i.SignatureValid,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRepositoryDelivery = `-- name: TouchRepositoryDelivery :exec
UPDATE repositories SET last_delivery_at = now() WHERE id = $1
`

func (q *Queries) TouchRepositoryDelivery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRepositoryDelivery, id)
	return err
}

const updateRepositoryDefaultBranch = `-- name: UpdateRepositoryDefaultBranch :exec
UPDATE repositories SET default_branch = $1 WHERE id = $2
`

type UpdateRepositoryDefaultBranchParams struct {
	DefaultBranch string    `json:"default_branch"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRepositoryDefaultBranch(ctx context.Context, arg UpdateRepositoryDefaultBranchParams) error {
	_, err := q.db.Exec(ctx, updateRepositoryDefaultBranch, arg.DefaultBranch, arg.ID)
	return err
}
