// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRunningJobs = `-- name: CountRunningJobs :one
SELECT count(*) FROM pipeline_jobs WHERE runner_id = $1 AND status = 'running'
`

func (q *Queries) CountRunningJobs(ctx context.Context, runnerID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunningJobs, runnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :one
INSERT INTO runner_registration_tokens (organization_id, token_hash, labels, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, token_hash, labels, created_by, expires_at, used_at, runner_id, created_at
`

type CreateRegistrationTokenParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	TokenHash      []byte     `json:"token_hash"`
	Labels         []string   `json:"labels"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	ExpiresAt      time.Time  `json:"expires_at"`
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) (RunnerRegistrationToken, error) {
	row := q.db.QueryRow(ctx, createRegistrationToken,
		arg.OrganizationID,
		arg.TokenHash,
		arg.Labels,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i RunnerRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Labels,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RunnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createRunner = `-- name: CreateRunner :one
INSERT INTO runners (organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, created_by, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now())
RETURNING id, organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, last_seen_at, disabled_at, created_by, row_version, created_at, updated_at
`

type CreateRunnerParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Labels         []string   `json:"labels"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	Version        string     `json:"version"`
	Os             string     `json:"os"`
	Arch           string     `json:"arch"`
	MaxConcurrency int32      `json:"max_concurrency"`
	CreatedBy      *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, createRunner,
		arg.OrganizationID,
		arg.Name,
		arg.Labels,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Version,
		arg.Os,
		arg.Arch,
		arg.MaxConcurrency,
		arg.CreatedBy,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Labels,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.MaxConcurrency,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredJobTokens = `-- name: DeleteExpiredJobTokens :execrows
DELETE FROM job_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredJobTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredJobTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRegistrationTokens = `-- name: DeleteExpiredRegistrationTokens :execrows
DELETE FROM runner_registration_tokens WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRegistrationTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRegistrationTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRunner = `-- name: DeleteRunner :execrows
DELETE FROM runners WHERE id = $1
`

func (q *Queries) DeleteRunner(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dependencyArtifacts = `-- name: DependencyArtifacts :many
SELECT a.id, a.job_id, a.project_id, a.organization_id, a.name, a.size_bytes, a.sha256, a.storage_key, a.expires_at, a.created_at, j.name AS job_name FROM artifacts a
JOIN pipeline_jobs j ON j.id = a.job_id
WHERE j.run_id = $1 AND j.name = ANY($2::text[]) AND j.status = 'succeeded' AND a.expires_at > now()
  AND j.attempt = (SELECT max(j2.attempt) FROM pipeline_jobs j2 WHERE j2.run_id = j.run_id AND j2.name = j.name)
ORDER BY j.name
`

type DependencyArtifactsParams struct {
	RunID uuid.UUID `json:"run_id"`
	Names []string  `json:"names"`
}

type DependencyArtifactsRow struct {
	ID             uuid.UUID `json:"id"`
	JobID          uuid.UUID `json:"job_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	SizeBytes      int64     `json:"size_bytes"`
	Sha256         []byte    `json:"sha256"`
	StorageKey     string    `json:"storage_key"`
	ExpiresAt      time.Time `json:"expires_at"`
	CreatedAt      time.Time `json:"created_at"`
	JobName        string    `json:"job_name"`
}

// Artifacts of the latest successful attempt of each named job in a run.
func (q *Queries) DependencyArtifacts(ctx context.Context, arg DependencyArtifactsParams) ([]DependencyArtifactsRow, error) {
	rows, err := q.db.Query(ctx, dependencyArtifacts, arg.RunID, arg.Names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DependencyArtifactsRow{}
	for rows.Next() {
		var i DependencyArtifactsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ProjectID,
			&i.OrganizationID,
			&i.Name,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.JobName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const evictCache = `-- name: EvictCache :many
DELETE FROM cache_entries c
WHERE c.id IN (
  SELECT id FROM (
    SELECT id, sum(size_bytes) OVER (PARTITION BY project_id ORDER BY last_used_at DESC, id DESC) AS running_total
    FROM cache_entries
  ) ranked WHERE running_total > $1::bigint
)
RETURNING storage_key
`

// Removes the least recently used entries beyond a project's quota.
func (q *Queries) EvictCache(ctx context.Context, quotaBytes int64) ([]string, error) {
	rows, err := q.db.Query(ctx, evictCache, quotaBytes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredArtifacts = `-- name: ExpiredArtifacts :many
DELETE FROM artifacts WHERE expires_at <= now() RETURNING storage_key
`

func (q *Queries) ExpiredArtifacts(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, expiredArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, job_id, project_id, organization_id, name, size_bytes, sha256, storage_key, expires_at, created_at FROM artifacts WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCacheEntry = `-- name: GetCacheEntry :one
UPDATE cache_entries SET last_used_at = now() WHERE project_id = $1 AND key = $2 RETURNING id, project_id, key, storage_key, size_bytes, sha256, last_used_at, created_at
`

type GetCacheEntryParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
}

func (q *Queries) GetCacheEntry(ctx context.Context, arg GetCacheEntryParams) (CacheEntry, error) {
	row := q.db.QueryRow(ctx, getCacheEntry, arg.ProjectID, arg.Key)
	var i CacheEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.StorageKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByToken = `-- name: GetJobByToken :one
SELECT j.id, j.run_id, j.project_id, j.organization_id, j.name, j.stage, j.stage_index, j.needs, j.condition, j.environment, j.environment_id, j.runs_on, j.spec, j.status, j.attempt, j.runner_id, j.timeout_seconds, j.exit_code, j.failure_reason, j.log_bytes, j.queued_at, j.started_at, j.finished_at, j.created_at, j.updated_at FROM job_tokens t JOIN pipeline_jobs j ON j.id = t.job_id
WHERE t.token_hash = $1 AND t.expires_at > now()
`

func (q *Queries) GetJobByToken(ctx context.Context, tokenHash []byte) (PipelineJob, error) {
	row := q.db.QueryRow(ctx, getJobByToken, tokenHash)
	var i PipelineJob
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.Stage,
		&i.StageIndex,
		&i.Needs,
		&i.Condition,
		&i.Environment,
		&i.EnvironmentID,
		&i.RunsOn,
		&i.Spec,
		&i.Status,
		&i.Attempt,
		&i.RunnerID,
		&i.TimeoutSeconds,
		&i.ExitCode,
		&i.FailureReason,
		&i.LogBytes,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, last_seen_at, disabled_at, created_by, row_version, created_at, updated_at FROM runners WHERE id = $1
`

func (q *Queries) GetRunner(ctx context.Context, id uuid.UUID) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Labels,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.MaxConcurrency,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunnerByTokenHash = `-- name: GetRunnerByTokenHash :one
SELECT id, organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, last_seen_at, disabled_at, created_by, row_version, created_at, updated_at FROM runners WHERE token_hash = $1
`

func (q *Queries) GetRunnerByTokenHash(ctx context.Context, tokenHash []byte) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunnerByTokenHash, tokenHash)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Labels,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.MaxConcurrency,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (job_id, project_id, organization_id, name, size_bytes, sha256, storage_key, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (job_id) DO NOTHING
RETURNING id, job_id, project_id, organization_id, name, size_bytes, sha256, storage_key, expires_at, created_at
`

type InsertArtifactParams struct {
	JobID          uuid.UUID `json:"job_id"`
	ProjectID      uuid.UUID `json:"project_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	SizeBytes      int64     `json:"size_bytes"`
	Sha256         []byte    `json:"sha256"`
	StorageKey     string    `json:"storage_key"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.JobID,
		arg.ProjectID,
		arg.OrganizationID,
		arg.Name,
		arg.SizeBytes,
		arg.Sha256,
		arg.StorageKey,
		arg.ExpiresAt,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ProjectID,
		&i.OrganizationID,
		&i.Name,
		&i.SizeBytes,
		&i.Sha256,
		&i.StorageKey,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkRegistrationToken = `-- name: LinkRegistrationToken :exec
UPDATE runner_registration_tokens SET runner_id = $1 WHERE id = $2
`

type LinkRegistrationTokenParams struct {
	RunnerID *uuid.UUID `json:"runner_id"`
	ID       uuid.UUID  `json:"id"`
}

func (q *Queries) LinkRegistrationToken(ctx context.Context, arg LinkRegistrationTokenParams) error {
	_, err := q.db.Exec(ctx, linkRegistrationToken, arg.RunnerID, arg.ID)
	return err
}

const listJobArtifacts = `-- name: ListJobArtifacts :many
SELECT id, job_id, project_id, organization_id, name, size_bytes, sha256, storage_key, expires_at, created_at FROM artifacts WHERE job_id = $1 AND expires_at > now() ORDER BY created_at
`

func (q *Queries) ListJobArtifacts(ctx context.Context, jobID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listJobArtifacts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ProjectID,
			&i.OrganizationID,
			&i.Name,
			&i.SizeBytes,
			&i.Sha256,
			&i.StorageKey,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunners = `-- name: ListRunners :many
SELECT r.id, r.organization_id, r.name, r.labels, r.token_hash, r.token_prefix, r.version, r.os, r.arch, r.max_concurrency, r.last_seen_at, r.disabled_at, r.created_by, r.row_version, r.created_at, r.updated_at,
       (SELECT count(*) FROM pipeline_jobs j WHERE j.runner_id = r.id AND j.status = 'running')::bigint AS running_jobs
FROM runners r
WHERE r.organization_id = $1
ORDER BY r.name, r.id
`

type ListRunnersRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Name           string     `json:"name"`
	Labels         []string   `json:"labels"`
	TokenHash      []byte     `json:"token_hash"`
	TokenPrefix    string     `json:"token_prefix"`
	Version        string     `json:"version"`
	Os             string     `json:"os"`
	Arch           string     `json:"arch"`
	MaxConcurrency int32      `json:"max_concurrency"`
	LastSeenAt     *time.Time `json:"last_seen_at"`
	DisabledAt     *time.Time `json:"disabled_at"`
	CreatedBy      *uuid.UUID `json:"created_by"`
	RowVersion     int32      `json:"row_version"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	RunningJobs    int64      `json:"running_jobs"`
}

func (q *Queries) ListRunners(ctx context.Context, organizationID uuid.UUID) ([]ListRunnersRow, error) {
	rows, err := q.db.Query(ctx, listRunners, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunnersRow{}
	for rows.Next() {
		var i ListRunnersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Labels,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Version,
			&i.Os,
			&i.Arch,
			&i.MaxConcurrency,
			&i.LastSeenAt,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.RowVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunningJobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRunner = `-- name: LockRunner :one
SELECT id, organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, last_seen_at, disabled_at, created_by, row_version, created_at, updated_at FROM runners WHERE id = $1 FOR NO KEY UPDATE
`

// Serializes job claims per runner so max_concurrency holds under concurrent requests.
func (q *Queries) LockRunner(ctx context.Context, id uuid.UUID) (Runner, error) {
	row := q.db.QueryRow(ctx, lockRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Labels,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.MaxConcurrency,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lostRunnerJobs = `-- name: LostRunnerJobs :many
SELECT j.id FROM pipeline_jobs j
JOIN runners r ON r.id = j.runner_id
WHERE j.status = 'running' AND (r.last_seen_at IS NULL OR r.last_seen_at < now() - make_interval(secs => $1::integer))
LIMIT 100
`

// Running jobs whose runner stopped sending heartbeats.
func (q *Queries) LostRunnerJobs(ctx context.Context, staleSeconds int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lostRunnerJobs, staleSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orphanedRunnerJobs = `-- name: OrphanedRunnerJobs :many
SELECT id FROM pipeline_jobs
WHERE runner_id = $1 AND status = 'running' AND NOT (id = ANY($2::uuid[]))
  AND started_at < now() - make_interval(secs => $3::integer)
`

type OrphanedRunnerJobsParams struct {
	RunnerID     *uuid.UUID  `json:"runner_id"`
	JobIds       []uuid.UUID `json:"job_ids"`
	GraceSeconds int32       `json:"grace_seconds"`
}

// Running jobs assigned to a runner that it no longer reports (the agent restarted, or
// never received the assignment). The grace period covers a claim racing a heartbeat.
func (q *Queries) OrphanedRunnerJobs(ctx context.Context, arg OrphanedRunnerJobsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, orphanedRunnerJobs, arg.RunnerID, arg.JobIds, arg.GraceSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runningJobsForRunner = `-- name: RunningJobsForRunner :many
SELECT id FROM pipeline_jobs WHERE runner_id = $1 AND status = 'running'
`

func (q *Queries) RunningJobsForRunner(ctx context.Context, runnerID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, runningJobsForRunner, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRunner = `-- name: TouchRunner :exec
UPDATE runners SET last_seen_at = now(), version = $1, os = $2, arch = $3 WHERE id = $4
`

type TouchRunnerParams struct {
	Version string    `json:"version"`
	Os      string    `json:"os"`
	Arch    string    `json:"arch"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) TouchRunner(ctx context.Context, arg TouchRunnerParams) error {
	_, err := q.db.Exec(ctx, touchRunner,
		arg.Version,
		arg.Os,
		arg.Arch,
		arg.ID,
	)
	return err
}

const updateRunner = `-- name: UpdateRunner :one
UPDATE runners SET name = $1, labels = $2, max_concurrency = $3,
  disabled_at = CASE WHEN $4::boolean THEN coalesce(disabled_at, now()) ELSE NULL END,
  row_version = row_version + 1
WHERE id = $5 AND row_version = $6
RETURNING id, organization_id, name, labels, token_hash, token_prefix, version, os, arch, max_concurrency, last_seen_at, disabled_at, created_by, row_version, created_at, updated_at
`

type UpdateRunnerParams struct {
	Name           string    `json:"name"`
	Labels         []string  `json:"labels"`
	MaxConcurrency int32     `json:"max_concurrency"`
	Disabled       bool      `json:"disabled"`
	ID             uuid.UUID `json:"id"`
	RowVersion     int32     `json:"row_version"`
}

func (q *Queries) UpdateRunner(ctx context.Context, arg UpdateRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, updateRunner,
		arg.Name,
		arg.Labels,
		arg.MaxConcurrency,
		arg.Disabled,
		arg.ID,
		arg.RowVersion,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Labels,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Version,
		&i.Os,
		&i.Arch,
		&i.MaxConcurrency,
		&i.LastSeenAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.RowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCacheEntry = `-- name: UpsertCacheEntry :one
WITH old AS (SELECT storage_key FROM cache_entries WHERE project_id = $1 AND key = $2)
INSERT INTO cache_entries (project_id, key, storage_key, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, key) DO UPDATE SET storage_key = EXCLUDED.storage_key, size_bytes = EXCLUDED.size_bytes,
  sha256 = EXCLUDED.sha256, last_used_at = now()
RETURNING coalesce((SELECT storage_key FROM old), '')::text AS previous_key
`

type UpsertCacheEntryParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Key        string    `json:"key"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	Sha256     []byte    `json:"sha256"`
}

// Returns the replaced blob's key (if any) so the caller can delete it.
func (q *Queries) UpsertCacheEntry(ctx context.Context, arg UpsertCacheEntryParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertCacheEntry,
		arg.ProjectID,
		arg.Key,
		arg.StorageKey,
		arg.SizeBytes,
		arg.Sha256,
	)
	var previous_key string
	err := row.Scan(&previous_key)
	return previous_key, err
}

const upsertJobToken = `-- name: UpsertJobToken :exec
INSERT INTO job_tokens (job_id, token_hash, expires_at) VALUES ($1, $2, $3)
ON CONFLICT (job_id) DO UPDATE SET token_hash = EXCLUDED.token_hash, expires_at = EXCLUDED.expires_at
`

type UpsertJobTokenParams struct {
	JobID     uuid.UUID `json:"job_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpsertJobToken(ctx context.Context, arg UpsertJobTokenParams) error {
	_, err := q.db.Exec(ctx, upsertJobToken, arg.JobID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const useRegistrationToken = `-- name: UseRegistrationToken :one
UPDATE runner_registration_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, organization_id, token_hash, labels, created_by, expires_at, used_at, runner_id, created_at
`

// Consumes an unused, unexpired token (one-time).
func (q *Queries) UseRegistrationToken(ctx context.Context, tokenHash []byte) (RunnerRegistrationToken, error) {
	row := q.db.QueryRow(ctx, useRegistrationToken, tokenHash)
	var i RunnerRegistrationToken
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Labels,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RunnerID,
		&i.CreatedAt,
	)
	return i, err
}
