// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpSecretVersion = `-- name: BumpSecretVersion :one
UPDATE secrets SET current_version = current_version + 1, version = version + 1
WHERE id = $1 AND version = $2 AND deleted_at IS NULL
RETURNING id, project_id, environment_id, name, description, current_version, created_by, version, created_at, updated_at, deleted_at
`

type BumpSecretVersionParams struct {
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

// Rotation: the next value version, also a new ETag version.
func (q *Queries) BumpSecretVersion(ctx context.Context, arg BumpSecretVersionParams) (Secret, error) {
	row := q.db.QueryRow(ctx, bumpSecretVersion, arg.ID, arg.ExpectedVersion)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countSecrets = `-- name: CountSecrets :one
SELECT count(*) FROM secrets WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountSecrets(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSecrets, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSecret = `-- name: CreateSecret :one
INSERT INTO secrets (project_id, environment_id, name, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, environment_id, name, description, current_version, created_by, version, created_at, updated_at, deleted_at
`

type CreateSecretParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	CreatedBy     *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRow(ctx, createSecret,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const destroySecretValues = `-- name: DestroySecretValues :execrows
UPDATE secret_versions SET ciphertext = NULL, nonce = NULL, dek_enc = NULL, kek_id = NULL, destroyed_at = now()
WHERE secret_id = $1 AND destroyed_at IS NULL AND ($2::integer = 0 OR version < $2)
`

type DestroySecretValuesParams struct {
	SecretID      uuid.UUID `json:"secret_id"`
	BeforeVersion int32     `json:"before_version"`
}

// Destroys the values of every version below before_version (all of them when it is 0).
func (q *Queries) DestroySecretValues(ctx context.Context, arg DestroySecretValuesParams) (int64, error) {
	result, err := q.db.Exec(ctx, destroySecretValues, arg.SecretID, arg.BeforeVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJobMasks = `-- name: GetJobMasks :one
SELECT masks_enc FROM job_tokens WHERE job_id = $1
`

func (q *Queries) GetJobMasks(ctx context.Context, jobID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getJobMasks, jobID)
	var masks_enc []byte
	err := row.Scan(&masks_enc)
	return masks_enc, err
}

const getSecret = `-- name: GetSecret :one
SELECT s.id, s.project_id, s.environment_id, s.name, s.description, s.current_version, s.created_by, s.version, s.created_at, s.updated_at, s.deleted_at,
       e.name AS environment_name,
       (pr.environment_id IS NOT NULL)::boolean AS protected,
       v.created_at AS rotated_at
FROM secrets s
LEFT JOIN environments e ON e.id = s.environment_id
LEFT JOIN protection_rules pr ON pr.environment_id = s.environment_id
JOIN secret_versions v ON v.secret_id = s.id AND v.version = s.current_version
WHERE s.id = $1 AND s.deleted_at IS NULL AND (s.environment_id IS NULL OR e.deleted_at IS NULL)
`

type GetSecretRow struct {
	Secret          Secret    `json:"secret"`
	EnvironmentName *string   `json:"environment_name"`
	Protected       bool      `json:"protected"`
	RotatedAt       time.Time `json:"rotated_at"`
}

// A live secret with its scope; environments deleted since hide their secrets.
func (q *Queries) GetSecret(ctx context.Context, id uuid.UUID) (GetSecretRow, error) {
	row := q.db.QueryRow(ctx, getSecret, id)
	var i GetSecretRow
	err := row.Scan(
		&i.Secret.ID,
		&i.Secret.ProjectID,
		&i.Secret.EnvironmentID,
		&i.Secret.Name,
		&i.Secret.Description,
		&i.Secret.CurrentVersion,
		&i.Secret.CreatedBy,
		&i.Secret.Version,
		&i.Secret.CreatedAt,
		&i.Secret.UpdatedAt,
		&i.Secret.DeletedAt,
		&i.EnvironmentName,
		&i.Protected,
		&i.RotatedAt,
	)
	return i, err
}

const insertSecretVersion = `-- name: InsertSecretVersion :exec
INSERT INTO secret_versions (secret_id, version, ciphertext, nonce, dek_enc, kek_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSecretVersionParams struct {
	SecretID   uuid.UUID  `json:"secret_id"`
	Version    int32      `json:"version"`
	Ciphertext []byte     `json:"ciphertext"`
	Nonce      []byte     `json:"nonce"`
	DekEnc     []byte     `json:"dek_enc"`
	KekID      *string    `json:"kek_id"`
	CreatedBy  *uuid.UUID `json:"created_by"`
}

func (q *Queries) InsertSecretVersion(ctx context.Context, arg InsertSecretVersionParams) error {
	_, err := q.db.Exec(ctx, insertSecretVersion,
		arg.SecretID,
		arg.Version,
		arg.Ciphertext,
		arg.Nonce,
		arg.DekEnc,
		arg.KekID,
		arg.CreatedBy,
	)
	return err
}

const jobSecretNames = `-- name: JobSecretNames :many
SELECT DISTINCT s.name
FROM secrets s
WHERE s.project_id = $1 AND s.deleted_at IS NULL
  AND s.name = ANY ($2::text[])
  AND (s.environment_id IS NULL OR s.environment_id = $3::uuid)
`

type JobSecretNamesParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	Names         []string   `json:"names"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
}

// The subset of names a job can be given (no decryption: used when the job becomes ready).
func (q *Queries) JobSecretNames(ctx context.Context, arg JobSecretNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, jobSecretNames, arg.ProjectID, arg.Names, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersions = `-- name: ListSecretVersions :many
SELECT v.version, v.created_at, v.destroyed_at, v.kek_id, v.created_by,
       u.display_name AS created_by_name
FROM secret_versions v
LEFT JOIN users u ON u.id = v.created_by
WHERE v.secret_id = $1
ORDER BY v.version DESC
`

type ListSecretVersionsRow struct {
	Version       int32      `json:"version"`
	CreatedAt     time.Time  `json:"created_at"`
	DestroyedAt   *time.Time `json:"destroyed_at"`
	KekID         *string    `json:"kek_id"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	CreatedByName *string    `json:"created_by_name"`
}

func (q *Queries) ListSecretVersions(ctx context.Context, secretID uuid.UUID) ([]ListSecretVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSecretVersions, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretVersionsRow{}
	for rows.Next() {
		var i ListSecretVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.CreatedAt,
			&i.DestroyedAt,
			&i.KekID,
			&i.CreatedBy,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT s.id, s.project_id, s.environment_id, s.name, s.description, s.current_version, s.created_by, s.version, s.created_at, s.updated_at, s.deleted_at,
       e.name AS environment_name,
       (pr.environment_id IS NOT NULL)::boolean AS protected,
       v.created_at AS rotated_at
FROM secrets s
LEFT JOIN environments e ON e.id = s.environment_id
LEFT JOIN protection_rules pr ON pr.environment_id = s.environment_id
JOIN secret_versions v ON v.secret_id = s.id AND v.version = s.current_version
WHERE s.project_id = $1 AND s.deleted_at IS NULL
  AND (s.environment_id IS NULL OR e.deleted_at IS NULL)
  AND ($2::uuid IS NULL OR s.environment_id = $2)
  AND (NOT $3::boolean OR s.environment_id IS NULL)
ORDER BY s.environment_id IS NOT NULL, e.name NULLS FIRST, s.name
`

type ListSecretsParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
	ProjectWide   bool       `json:"project_wide"`
}

type ListSecretsRow struct {
	Secret          Secret    `json:"secret"`
	EnvironmentName *string   `json:"environment_name"`
	Protected       bool      `json:"protected"`
	RotatedAt       time.Time `json:"rotated_at"`
}

// Project-wide first, then by environment and name. project_wide = true lists only
// project-wide secrets; environment_id lists only that environment's.
func (q *Queries) ListSecrets(ctx context.Context, arg ListSecretsParams) ([]ListSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSecrets, arg.ProjectID, arg.EnvironmentID, arg.ProjectWide)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.Secret.ID,
			&i.Secret.ProjectID,
			&i.Secret.EnvironmentID,
			&i.Secret.Name,
			&i.Secret.Description,
			&i.Secret.CurrentVersion,
			&i.Secret.CreatedBy,
			&i.Secret.Version,
			&i.Secret.CreatedAt,
			&i.Secret.UpdatedAt,
			&i.Secret.DeletedAt,
			&i.EnvironmentName,
			&i.Protected,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveJobSecrets = `-- name: ResolveJobSecrets :many
SELECT DISTINCT ON (s.name)
       s.id, s.name, s.environment_id, v.version, v.ciphertext, v.nonce, v.dek_enc
FROM secrets s
JOIN secret_versions v ON v.secret_id = s.id AND v.version = s.current_version
WHERE s.project_id = $1 AND s.deleted_at IS NULL AND v.destroyed_at IS NULL
  AND s.name = ANY ($2::text[])
  AND (s.environment_id IS NULL OR s.environment_id = $3::uuid)
ORDER BY s.name, s.environment_id NULLS LAST
`

type ResolveJobSecretsParams struct {
	ProjectID     uuid.UUID  `json:"project_id"`
	Names         []string   `json:"names"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
}

type ResolveJobSecretsRow struct {
	ID            uuid.UUID  `json:"id"`
	Name          string     `json:"name"`
	EnvironmentID *uuid.UUID `json:"environment_id"`
	Version       int32      `json:"version"`
	Ciphertext    []byte     `json:"ciphertext"`
	Nonce         []byte     `json:"nonce"`
	DekEnc        []byte     `json:"dek_enc"`
}

// The live secrets a job may receive, by name: the job's environment's secret wins over a
// project-wide one of the same name. environment_id NULL = a job without an environment.
func (q *Queries) ResolveJobSecrets(ctx context.Context, arg ResolveJobSecretsParams) ([]ResolveJobSecretsRow, error) {
	rows, err := q.db.Query(ctx, resolveJobSecrets, arg.ProjectID, arg.Names, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveJobSecretsRow{}
	for rows.Next() {
		var i ResolveJobSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EnvironmentID,
			&i.Version,
			&i.Ciphertext,
			&i.Nonce,
			&i.DekEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSecret = `-- name: SoftDeleteSecret :execrows
UPDATE secrets SET deleted_at = now(), version = version + 1
WHERE id = $1 AND version = $2 AND deleted_at IS NULL
`

type SoftDeleteSecretParams struct {
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) SoftDeleteSecret(ctx context.Context, arg SoftDeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSecret, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSecretDescription = `-- name: UpdateSecretDescription :one
UPDATE secrets SET description = $1, version = version + 1
WHERE id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING id, project_id, environment_id, name, description, current_version, created_by, version, created_at, updated_at, deleted_at
`

type UpdateSecretDescriptionParams struct {
	Description     string    `json:"description"`
	ID              uuid.UUID `json:"id"`
	ExpectedVersion int32     `json:"expected_version"`
}

func (q *Queries) UpdateSecretDescription(ctx context.Context, arg UpdateSecretDescriptionParams) (Secret, error) {
	row := q.db.QueryRow(ctx, updateSecretDescription, arg.Description, arg.ID, arg.ExpectedVersion)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.Name,
		&i.Description,
		&i.CurrentVersion,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
