// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createMFAChallenge = `-- name: CreateMFAChallenge :exec
INSERT INTO mfa_challenges (user_id, token_hash, auth_method, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateMFAChallengeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TokenHash  []byte    `json:"token_hash"`
	AuthMethod string    `json:"auth_method"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) error {
	_, err := q.db.Exec(ctx, createMFAChallenge,
		arg.UserID,
		arg.TokenHash,
		arg.AuthMethod,
		arg.ExpiresAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (session_id, parent_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, parent_id, token_hash, expires_at, used_at, created_at
`

type CreateRefreshTokenParams struct {
	SessionID uuid.UUID  `json:"session_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.SessionID,
		arg.ParentID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, auth_method, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, auth_method, ip, user_agent, expires_at, last_used_at, revoked_at, revoke_reason, created_at
`

type CreateSessionParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	AuthMethod string      `json:"auth_method"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	ExpiresAt  time.Time   `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.AuthMethod,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthMethod,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthRecords = `-- name: DeleteExpiredAuthRecords :exec
WITH s AS (
  DELETE FROM sessions WHERE coalesce(revoked_at, expires_at) < now() - interval '30 days'
), m AS (
  DELETE FROM mfa_challenges WHERE expires_at < now() - interval '1 day'
)
DELETE FROM email_tokens WHERE expires_at < now() - interval '7 days'
`

// Periodic cleanup. Sessions are kept 30 days after expiry/revocation for the security page history.
func (q *Queries) DeleteExpiredAuthRecords(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthRecords)
	return err
}

const getMFAChallengeForUpdate = `-- name: GetMFAChallengeForUpdate :one
SELECT id, user_id, token_hash, auth_method, attempts, expires_at, used_at, created_at FROM mfa_challenges WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetMFAChallengeForUpdate(ctx context.Context, tokenHash []byte) (MfaChallenge, error) {
	row := q.db.QueryRow(ctx, getMFAChallengeForUpdate, tokenHash)
	var i MfaChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.AuthMethod,
		&i.Attempts,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT rt.id, rt.session_id, rt.expires_at, rt.used_at,
       s.user_id, s.revoked_at AS session_revoked_at, s.expires_at AS session_expires_at
FROM refresh_tokens rt
JOIN sessions s ON s.id = rt.session_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt, s
`

type GetRefreshTokenForUpdateRow struct {
	ID               uuid.UUID  `json:"id"`
	SessionID        uuid.UUID  `json:"session_id"`
	ExpiresAt        time.Time  `json:"expires_at"`
	UsedAt           *time.Time `json:"used_at"`
	UserID           uuid.UUID  `json:"user_id"`
	SessionRevokedAt *time.Time `json:"session_revoked_at"`
	SessionExpiresAt time.Time  `json:"session_expires_at"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UserID,
		&i.SessionRevokedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const incrementMFAAttempts = `-- name: IncrementMFAAttempts :exec
UPDATE mfa_challenges SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementMFAAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementMFAAttempts, id)
	return err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, auth_method, ip, user_agent, expires_at, last_used_at, revoked_at, revoke_reason, created_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListActiveSessionsParams struct {
	UserID          uuid.UUID  `json:"user_id"`
	CursorCreatedAt *time.Time `json:"cursor_created_at"`
	CursorID        *uuid.UUID `json:"cursor_id"`
	PageSize        int32      `json:"page_size"`
}

// Keyset pagination (newest first).
func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthMethod,
			&i.Ip,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeSession = `-- name: RevokeSession :one
UPDATE sessions SET revoked_at = now(), revoke_reason = $1
WHERE id = $2 AND user_id = $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeSessionParams struct {
	Reason *string   `json:"reason"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.Reason, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now(), revoke_reason = $1
WHERE user_id = $2 AND revoked_at IS NULL
  AND ($3::uuid IS NULL OR id <> $3::uuid)
`

type RevokeUserSessionsParams struct {
	Reason *string    `json:"reason"`
	UserID uuid.UUID  `json:"user_id"`
	KeepID *uuid.UUID `json:"keep_id"`
}

// Revokes every session of a user, optionally keeping one (the caller's).
func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.Reason, arg.UserID, arg.KeepID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now(), ip = coalesce($1, ip), user_agent = $2
WHERE id = $3
`

type TouchSessionParams struct {
	Ip        *netip.Addr `json:"ip"`
	UserAgent *string     `json:"user_agent"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Ip, arg.UserAgent, arg.ID)
	return err
}

const useMFAChallenge = `-- name: UseMFAChallenge :exec
UPDATE mfa_challenges SET used_at = now() WHERE id = $1
`

func (q *Queries) UseMFAChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, useMFAChallenge, id)
	return err
}
