// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (team_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.TeamID, arg.UserID)
	return err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (organization_id, slug, name, description) VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, slug, name, created_at, updated_at, deleted_at, description, version
`

type CreateTeamParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Slug           string    `json:"slug"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrganizationID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, organization_id, slug, name, created_at, updated_at, deleted_at, description, version FROM teams WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT u.id AS user_id, u.email, u.display_name, tm.created_at AS added_at
FROM team_members tm
JOIN users u ON u.id = tm.user_id AND u.deleted_at IS NULL
WHERE tm.team_id = $1
ORDER BY u.display_name, u.id
`

type ListTeamMembersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	AddedAt     time.Time `json:"added_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT t.id, t.organization_id, t.slug, t.name, t.created_at, t.updated_at, t.deleted_at, t.description, t.version, (SELECT count(*) FROM team_members tm WHERE tm.team_id = t.id)::bigint AS member_count
FROM teams t
WHERE t.organization_id = $1 AND t.deleted_at IS NULL
  AND ($2::text IS NULL
       OR (t.name, t.id) > ($2::text, $3::uuid))
ORDER BY t.name, t.id
LIMIT $4
`

type ListTeamsParams struct {
	OrganizationID uuid.UUID  `json:"organization_id"`
	CursorName     *string    `json:"cursor_name"`
	CursorID       *uuid.UUID `json:"cursor_id"`
	PageSize       int32      `json:"page_size"`
}

type ListTeamsRow struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Slug           string     `json:"slug"`
	Name           string     `json:"name"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
	Description    string     `json:"description"`
	Version        int32      `json:"version"`
	MemberCount    int64      `json:"member_count"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]ListTeamsRow, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.OrganizationID,
		arg.CursorName,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsRow{}
	for rows.Next() {
		var i ListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Description,
			&i.Version,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :execrows
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTeam = `-- name: SoftDeleteTeam :exec
UPDATE teams SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeam, id)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET name = $1, description = $2, version = version + 1
WHERE id = $3 AND version = $4 AND deleted_at IS NULL
RETURNING id, organization_id, slug, name, created_at, updated_at, deleted_at, description, version
`

type UpdateTeamParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	ID          uuid.UUID `json:"id"`
	Version     int32     `json:"version"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.Description,
		arg.ID,
		arg.Version,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Description,
		&i.Version,
	)
	return i, err
}
