// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, password_hash, locale, timezone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, password_hash, email_verified_at, locale, timezone, khmer_numerals, totp_secret_enc, totp_enabled_at, is_platform_admin, disabled_at, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	DisplayName  string  `json:"display_name"`
	PasswordHash *string `json:"password_hash"`
	Locale       string  `json:"locale"`
	Timezone     string  `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.Timezone,
		&i.KhmerNumerals,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, password_hash, email_verified_at, locale, timezone, khmer_numerals, totp_secret_enc, totp_enabled_at, is_platform_admin, disabled_at, last_login_at, created_at, updated_at, deleted_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.Timezone,
		&i.KhmerNumerals,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, password_hash, email_verified_at, locale, timezone, khmer_numerals, totp_secret_enc, totp_enabled_at, is_platform_admin, disabled_at, last_login_at, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.Timezone,
		&i.KhmerNumerals,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE users
SET locale = $1, timezone = $2, khmer_numerals = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, email, display_name, password_hash, email_verified_at, locale, timezone, khmer_numerals, totp_secret_enc, totp_enabled_at, is_platform_admin, disabled_at, last_login_at, created_at, updated_at, deleted_at
`

type UpdateUserPreferencesParams struct {
	Locale        string    `json:"locale"`
	Timezone      string    `json:"timezone"`
	KhmerNumerals bool      `json:"khmer_numerals"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.Locale,
		arg.Timezone,
		arg.KhmerNumerals,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.Timezone,
		&i.KhmerNumerals,
		&i.TotpSecretEnc,
		&i.TotpEnabledAt,
		&i.IsPlatformAdmin,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
